<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['name']='client_locations_c';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['type']='text';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['rows']=NULL;
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['cols']=NULL;
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['vname']='LBL_CLIENT_LOCATIONS_C';
$dictionary['sa_Fluency_One']['fields']['client_locations_c']['source']='custom_fields';

 ?>