<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['name']='unusual_tos_tats_c';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['type']='text';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['rows']=NULL;
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['cols']=NULL;
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['vname']='LBL_UNUSUAL_TOS_TATS_C';
$dictionary['sa_Fluency_One']['fields']['unusual_tos_tats_c']['source']='custom_fields';

 ?>