<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['name']='sf_id_c';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['len']='18';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['type']='varchar';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['vname']='LBL_SF_ID_C';
$dictionary['sa_Fluency_One']['fields']['sf_id_c']['source']='custom_fields';

 ?>