<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['name']='lastreferenceddate';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['default']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['len']='255';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['required']=false;
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['type']='timestamp';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['options']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['help']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['comments']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['vname']='LBL_LASTREFERENCEDDATE';
$dictionary['sa_Fluency_One']['fields']['lastreferenceddate']['source']='custom_fields';

 ?>