<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['name']='workflowelfstage_c';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['len']='50';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['type']='varchar';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['vname']='LBL_WORKFLOWELFSTAGE_C';
$dictionary['sa_Fluency_One']['fields']['workflowelfstage_c']['source']='custom_fields';

 ?>