<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['name']='if_yes_please_explain_c';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['type']='text';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['rows']=NULL;
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['cols']=NULL;
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['vname']='LBL_IF_YES_PLEASE_EXPLAIN_C';
$dictionary['sa_Fluency_One']['fields']['if_yes_please_explain_c']['source']='custom_fields';

 ?>