<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['name']='number_of_clinics_c';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['type']='real';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['vname']='LBL_NUMBER_OF_CLINICS_C';
$dictionary['sa_Fluency_One']['fields']['number_of_clinics_c']['source']='custom_fields';

 ?>