<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['name']='capd_key_drivers_c';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['len']='4099';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['type']='text';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['rows']=NULL;
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['cols']=NULL;
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['vname']='LBL_CAPD_KEY_DRIVERS_C';
$dictionary['sa_Fluency_One']['fields']['capd_key_drivers_c']['source']='custom_fields';

 ?>