<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['name']='proposed_global_line_rate_c';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['type']='float';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['enable_range_search']='';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['precision']='8';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['vname']='LBL_PROPOSED_GLOBAL_LINE_RATE_C';
$dictionary['sa_Fluency_One']['fields']['proposed_global_line_rate_c']['source']='custom_fields';

 ?>