<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['name']='volume_with_m_modal_c';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['type']='float';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['enable_range_search']='';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['precision']='8';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['vname']='LBL_VOLUME_WITH_M_MODAL_C';
$dictionary['sa_Fluency_One']['fields']['volume_with_m_modal_c']['source']='custom_fields';

 ?>