<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['name']='tos_value_c';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['type']='real';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['vname']='LBL_TOS_VALUE_C';
$dictionary['sa_Fluency_One']['fields']['tos_value_c']['source']='custom_fields';

 ?>