<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['name']='reason_customer_declined_c';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['type']='text';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['rows']=NULL;
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['cols']=NULL;
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['vname']='LBL_REASON_CUSTOMER_DECLINED_C';
$dictionary['sa_Fluency_One']['fields']['reason_customer_declined_c']['source']='custom_fields';

 ?>