<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['name']['name']='name';
$dictionary['sa_Fluency_One']['fields']['name']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['name']['default']='';
$dictionary['sa_Fluency_One']['fields']['name']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['name']['len']='80';
$dictionary['sa_Fluency_One']['fields']['name']['required']=false;
$dictionary['sa_Fluency_One']['fields']['name']['type']='varchar';
$dictionary['sa_Fluency_One']['fields']['name']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['name']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['name']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['name']['options']='';
$dictionary['sa_Fluency_One']['fields']['name']['help']='';
$dictionary['sa_Fluency_One']['fields']['name']['comments']='';
$dictionary['sa_Fluency_One']['fields']['name']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['name']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['name']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['name']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['name']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['name']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['name']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['name']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['name']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['name']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['name']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['name']['vname']='LBL_NAME';
$dictionary['sa_Fluency_One']['fields']['name']['source']='custom_fields';

 ?>