<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['name']='systemmodstamp';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['default']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['len']='255';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['required']=false;
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['type']='datetime';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['options']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['help']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['comments']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['enable_range_search']='';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['vname']='LBL_SYSTEMMODSTAMP';
$dictionary['sa_Fluency_One']['fields']['systemmodstamp']['source']='custom_fields';

 ?>