<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['name']='client_s_buying_timeframe_c';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['type']='varchar';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['vname']='LBL_CLIENT_S_BUYING_TIMEFRAME_C';
$dictionary['sa_Fluency_One']['fields']['client_s_buying_timeframe_c']['source']='custom_fields';

 ?>