<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['name']='key_contact_titles_c';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['len']='150';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['type']='varchar';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['vname']='LBL_KEY_CONTACT_TITLES_C';
$dictionary['sa_Fluency_One']['fields']['key_contact_titles_c']['source']='custom_fields';

 ?>