<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['name']='current_m_modal_installed_products_c';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['len']='4099';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['type']='varchar';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['vname']='LBL_CURRENT_M_MODAL_INSTALLED_PRODUCTS_C';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_installed_products_c']['source']='custom_fields';

 ?>