<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['name']='mtso_3_volume_c';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['type']='float';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['enable_range_search']='';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['precision']='8';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['vname']='LBL_MTSO_3_VOLUME_C';
$dictionary['sa_Fluency_One']['fields']['mtso_3_volume_c']['source']='custom_fields';

 ?>