<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['name']='volume_insourced_c';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['type']='float';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['enable_range_search']='';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['precision']='8';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['vname']='LBL_VOLUME_INSOURCED_C';
$dictionary['sa_Fluency_One']['fields']['volume_insourced_c']['source']='custom_fields';

 ?>