<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['name']='number_of_doctors_c';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['type']='float';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['enable_range_search']='';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['precision']='8';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['vname']='LBL_NUMBER_OF_DOCTORS_C';
$dictionary['sa_Fluency_One']['fields']['number_of_doctors_c']['source']='custom_fields';

 ?>