<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['beds_c']['name']='beds_c';
$dictionary['sa_Fluency_One']['fields']['beds_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['beds_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['beds_c']['type']='float';
$dictionary['sa_Fluency_One']['fields']['beds_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['beds_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['beds_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['beds_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['beds_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['beds_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['beds_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['beds_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['beds_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['enable_range_search']='';
$dictionary['sa_Fluency_One']['fields']['beds_c']['precision']='8';
$dictionary['sa_Fluency_One']['fields']['beds_c']['vname']='LBL_BEDS_C';
$dictionary['sa_Fluency_One']['fields']['beds_c']['source']='custom_fields';

 ?>