<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['name']='lastvieweddate';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['default']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['len']='255';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['required']=false;
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['type']='datetime';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['options']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['help']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['comments']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['enable_range_search']='';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['vname']='LBL_LASTVIEWEDDATE';
$dictionary['sa_Fluency_One']['fields']['lastvieweddate']['source']='custom_fields';

 ?>