<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['name']='reason_for_not_a_good_fit_c';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['type']='text';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['rows']=NULL;
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['cols']=NULL;
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['vname']='LBL_REASON_FOR_NOT_A_GOOD_FIT_C';
$dictionary['sa_Fluency_One']['fields']['reason_for_not_a_good_fit_c']['source']='custom_fields';

 ?>