<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['name']='includes_pricedown_c';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['type']='text';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['rows']=NULL;
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['cols']=NULL;
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['vname']='LBL_INCLUDES_PRICEDOWN_C';
$dictionary['sa_Fluency_One']['fields']['includes_pricedown_c']['source']='custom_fields';

 ?>