<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['name']='current_m_modal_client_c';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['type']='bool';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['vname']='LBL_CURRENT_M_MODAL_CLIENT_C';
$dictionary['sa_Fluency_One']['fields']['current_m_modal_client_c']['source']='custom_fields';

 ?>