<?php
 // Vardefs from Fields_meta_data table - created:
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['name']='assigned_security_group_id';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['default']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['len']='36';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['required']=false;
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['type']='varchar';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['options']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['help']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['comments']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['rows']=NULL;
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['cols']=NULL;
$dictionary['sa_Fluency_One']['fields']['assigned_security_group_id']['vname']='LBL_ASSIGNED_SECURITY_GROUP';
 ?>