<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['name']='current_ehr_c';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['type']='text';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['rows']=NULL;
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['cols']=NULL;
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['vname']='LBL_CURRENT_EHR_C';
$dictionary['sa_Fluency_One']['fields']['current_ehr_c']['source']='custom_fields';

 ?>