<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['name']='estimate_asr_mix_c';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['type']='real';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['vname']='LBL_ESTIMATE_ASR_MIX_C';
$dictionary['sa_Fluency_One']['fields']['estimate_asr_mix_c']['source']='custom_fields';

 ?>