<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['name']='desired_pricing_model_c';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['type']='text';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['rows']=NULL;
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['cols']=NULL;
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['vname']='LBL_DESIRED_PRICING_MODEL_C';
$dictionary['sa_Fluency_One']['fields']['desired_pricing_model_c']['source']='custom_fields';

 ?>