<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['name']='outsource_mtso_3_c';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['len']='18';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['type']='varchar';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['vname']='LBL_OUTSOURCE_MTSO_3_C';
$dictionary['sa_Fluency_One']['fields']['outsource_mtso_3_c']['source']='custom_fields';

 ?>