<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['name']='client_currently_uses_dragon_c';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['type']='bool';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['vname']='LBL_CLIENT_CURRENTLY_USES_DRAGON_C';
$dictionary['sa_Fluency_One']['fields']['client_currently_uses_dragon_c']['source']='custom_fields';

 ?>