<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['name']='f1radtosopp_c';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['len']='18';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['type']='varchar';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['vname']='LBL_F1RADTOSOPP_C';
$dictionary['sa_Fluency_One']['fields']['f1radtosopp_c']['source']='custom_fields';

 ?>