<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['name']='number_of_credentialed_users_c';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['type']='real';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['vname']='LBL_NUMBER_OF_CREDENTIALED_USERS_C';
$dictionary['sa_Fluency_One']['fields']['number_of_credentialed_users_c']['source']='custom_fields';

 ?>