<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['name']='gpo_affiliation_c';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['len']='18';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['type']='varchar';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['vname']='LBL_GPO_AFFILIATION_C';
$dictionary['sa_Fluency_One']['fields']['gpo_affiliation_c']['source']='custom_fields';

 ?>