<?php
 // Vardefs from Fields_meta_data table - created:
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['name']='request_submit_date_c';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['len']='255';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['type']='datetimecombo';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['dbType']='datetime';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['vname']='LBL_REQUEST_SUBMIT_DATE_C';
$dictionary['sa_Fluency_One']['fields']['request_submit_date_c']['source']='custom_fields';

 ?>