<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['name']='eb_elf_opp_c';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['default_value']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['default']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['display_default']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['len']='18';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['required']=false;
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['type']='varchar';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['audited']=0;
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['inline_edit']=1;
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['massupdate']=0;
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['options']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['help']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['comments']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['importable']='true';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['duplicate_merge']=0;
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['duplicate_merge_dom_value']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['merge_filter']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['reportable']=true;
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['ext2']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['ext4']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['ext3']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['labelValue']=NULL;
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['unified_search']=0;
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['full_text_search']='';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['vname']='LBL_EB_ELF_OPP_C';
$dictionary['sa_Fluency_One']['fields']['eb_elf_opp_c']['source']='custom_fields';

 ?>