<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['name']='apttus_ff_amend_c';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['vname']='LBL_APTTUS_FF_AMEND_C';
$dictionary['AOS_Contracts']['fields']['apttus_ff_amend_c']['source']='custom_fields';

 ?>