<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['requires_po_c']['name']='requires_po_c';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['default']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['requires_po_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['requires_po_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['requires_po_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['requires_po_c']['options']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['help']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['requires_po_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['requires_po_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['requires_po_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['requires_po_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['vname']='LBL_REQUIRES_PO_C';
$dictionary['AOS_Contracts']['fields']['requires_po_c']['source']='custom_fields';

 ?>