<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['name']='awaiting_information_detail_c';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['default']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['options']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['help']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['vname']='LBL_AWAITING_INFORMATION_DETAIL_C';
$dictionary['AOS_Contracts']['fields']['awaiting_information_detail_c']['source']='custom_fields';

 ?>