<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['name']='dq_paymentterms_c';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['default']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['options']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['help']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['vname']='LBL_DQ_PAYMENTTERMS_C';
$dictionary['AOS_Contracts']['fields']['dq_paymentterms_c']['source']='custom_fields';

 ?>