<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['name']='facility_contact_phone_number_billing_c';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['default']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['options']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['help']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['vname']='LBL_FACILITY_CONTACT_PHONE_NUMBER_BILLING_C';
$dictionary['AOS_Contracts']['fields']['facility_contact_phone_number_billing_c']['source']='custom_fields';

 ?>