<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['ucid_c']['name']='ucid_c';
$dictionary['AOS_Contracts']['fields']['ucid_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['default']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['len']='5';
$dictionary['AOS_Contracts']['fields']['ucid_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['ucid_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['ucid_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['ucid_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['ucid_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['ucid_c']['options']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['help']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['ucid_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['ucid_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['ucid_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['ucid_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['ucid_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['ucid_c']['vname']='LBL_UCID_C';
$dictionary['AOS_Contracts']['fields']['ucid_c']['source']='custom_fields';

 ?>