<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['name']='apttus_subtype_c';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['vname']='LBL_APTTUS_SUBTYPE_C';
$dictionary['AOS_Contracts']['fields']['apttus_subtype_c']['source']='custom_fields';

 ?>