<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['name']='client_responsibl_for_collection_cost_c';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['default']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['options']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['help']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['vname']='LBL_CLIENT_RESPONSIBL_FOR_COLLECTION_COST_C';
$dictionary['AOS_Contracts']['fields']['client_responsibl_for_collection_cost_c']['source']='custom_fields';

 ?>