<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['name']='software_pricing_discount_picklist_c';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['default']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['options']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['help']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['vname']='LBL_SOFTWARE_PRICING_DISCOUNT_PICKLIST_C';
$dictionary['AOS_Contracts']['fields']['software_pricing_discount_picklist_c']['source']='custom_fields';

 ?>