<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['name']='apttus_retentionpolicyid_c';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['len']='18';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['vname']='LBL_APTTUS_RETENTIONPOLICYID_C';
$dictionary['AOS_Contracts']['fields']['apttus_retentionpolicyid_c']['source']='custom_fields';

 ?>