<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['chevron_c']['name']='chevron_c';
$dictionary['AOS_Contracts']['fields']['chevron_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['default']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['chevron_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['chevron_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['chevron_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['chevron_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['chevron_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['chevron_c']['options']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['help']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['chevron_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['chevron_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['chevron_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['chevron_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['chevron_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['chevron_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['chevron_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['chevron_c']['vname']='LBL_CHEVRON_C';
$dictionary['AOS_Contracts']['fields']['chevron_c']['source']='custom_fields';

 ?>