<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['name']='m_modal_travel_living_policy_c';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['default']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['options']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['help']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['vname']='LBL_M_MODAL_TRAVEL_LIVING_POLICY_C';
$dictionary['AOS_Contracts']['fields']['m_modal_travel_living_policy_c']['source']='custom_fields';

 ?>