<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['name']='product_maintenance_and_support_service_c';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['default']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['options']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['help']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['vname']='LBL_PRODUCT_MAINTENANCE_AND_SUPPORT_SERVICE_C';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_service_c']['source']='custom_fields';

 ?>