<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['name']='gpo_idn_c';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['default']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['options']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['help']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['vname']='LBL_GPO_IDN_C';
$dictionary['AOS_Contracts']['fields']['gpo_idn_c']['source']='custom_fields';

 ?>