<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['name']='apttus_allowableoutputformats_c';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['len']='4099';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['vname']='LBL_APTTUS_ALLOWABLEOUTPUTFORMATS_C';
$dictionary['AOS_Contracts']['fields']['apttus_allowableoutputformats_c']['source']='custom_fields';

 ?>