<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['name']='tat_credits_c';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['default']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['options']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['help']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['vname']='LBL_TAT_CREDITS_C';
$dictionary['AOS_Contracts']['fields']['tat_credits_c']['source']='custom_fields';

 ?>