<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['name']='enhanced_data_use_rights_language_c';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['default']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['options']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['help']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['vname']='LBL_ENHANCED_DATA_USE_RIGHTS_LANGUAGE_C';
$dictionary['AOS_Contracts']['fields']['enhanced_data_use_rights_language_c']['source']='custom_fields';

 ?>