<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['name']='coding_implementation_training_fees_c';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['default']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['options']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['help']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['vname']='LBL_CODING_IMPLEMENTATION_TRAINING_FEES_C';
$dictionary['AOS_Contracts']['fields']['coding_implementation_training_fees_c']['source']='custom_fields';

 ?>