<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['name']='t_c_version_c';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['default']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['type']='date';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['options']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['help']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['vname']='LBL_T_C_VERSION_C';
$dictionary['AOS_Contracts']['fields']['t_c_version_c']['source']='custom_fields';

 ?>