<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['name']='apttus_workflow_trigger_viewed_final_c';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['vname']='LBL_APTTUS_WORKFLOW_TRIGGER_VIEWED_FINAL_C';
$dictionary['AOS_Contracts']['fields']['apttus_workflow_trigger_viewed_final_c']['source']='custom_fields';

 ?>