<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['name']='fft_pricing_other_c';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['default']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['options']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['help']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['vname']='LBL_FFT_PRICING_OTHER_C';
$dictionary['AOS_Contracts']['fields']['fft_pricing_other_c']['source']='custom_fields';

 ?>