<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['name']='recordtypeid_c';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['default']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['len']='18';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['options']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['help']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['vname']='LBL_RECORDTYPEID';
$dictionary['AOS_Contracts']['fields']['recordtypeid_c']['source']='custom_fields';

 ?>