<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['name']='product_term_for_convenience_c';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['default']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['options']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['help']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['vname']='LBL_PRODUCT_TERM_FOR_CONVENIENCE_C';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenience_c']['source']='custom_fields';

 ?>