<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['name']='tos_price_book_rate_c';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['default']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['options']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['help']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['vname']='LBL_TOS_PRICE_BOOK_RATE_C';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_c']['source']='custom_fields';

 ?>