<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['name']='dq_f1_prod_pricing_incr_c';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['default']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['options']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['help']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['vname']='LBL_DQ_F1_PROD_PRICING_INCR_C';
$dictionary['AOS_Contracts']['fields']['dq_f1_prod_pricing_incr_c']['source']='custom_fields';

 ?>