<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['name']='coding_pricing_c';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['default']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['options']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['help']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['vname']='LBL_CODING_PRICING_C';
$dictionary['AOS_Contracts']['fields']['coding_pricing_c']['source']='custom_fields';

 ?>