<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['name']='governing_law_state_c';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['default']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['options']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['help']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['vname']='LBL_GOVERNING_LAW_STATE_C';
$dictionary['AOS_Contracts']['fields']['governing_law_state_c']['source']='custom_fields';

 ?>