<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['name']='legal_notices_c';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['default']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['len']='4099';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['options']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['help']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['vname']='LBL_LEGAL_NOTICES_C';
$dictionary['AOS_Contracts']['fields']['legal_notices_c']['source']='custom_fields';

 ?>