<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['name']='maintenance_and_support_attachment_effec_c';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['default']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['type']='date';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['options']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['help']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['vname']='LBL_MAINTENANCE_AND_SUPPORT_ATTACHMENT_EFFEC_C';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_attachment_effec_c']['source']='custom_fields';

 ?>