<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['name']='product_maintenance_and_support_expirati_c';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['default']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['type']='date';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['options']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['help']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['vname']='LBL_PRODUCT_MAINTENANCE_AND_SUPPORT_EXPIRATI_C';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_expirati_c']['source']='custom_fields';

 ?>