<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['name']='tos_evergreen_c';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['default']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['options']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['help']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['vname']='LBL_TOS_EVERGREEN_C';
$dictionary['AOS_Contracts']['fields']['tos_evergreen_c']['source']='custom_fields';

 ?>