<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['name']='passive_adaptation_c';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['default']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['options']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['help']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['vname']='LBL_PASSIVE_ADAPTATION_C';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_c']['source']='custom_fields';

 ?>