<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['name']='facility_city_state_and_zip_code_c';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['default']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['len']='80';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['options']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['help']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['vname']='LBL_FACILITY_CITY_STATE_AND_ZIP_CODE_C';
$dictionary['AOS_Contracts']['fields']['facility_city_state_and_zip_code_c']['source']='custom_fields';

 ?>