<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['name']='comm_ops_age_c';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['default']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['options']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['help']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['vname']='LBL_COMM_OPS_AGE_C';
$dictionary['AOS_Contracts']['fields']['comm_ops_age_c']['source']='custom_fields';

 ?>