<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['name']='transcription_platform_c';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['default']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['options']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['help']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['vname']='LBL_TRANSCRIPTION_PLATFORM_C';
$dictionary['AOS_Contracts']['fields']['transcription_platform_c']['source']='custom_fields';

 ?>