<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['facility_name_c']['name']='facility_name_c';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['default']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['facility_name_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['facility_name_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['facility_name_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['facility_name_c']['options']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['help']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['facility_name_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['facility_name_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['facility_name_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['facility_name_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['facility_name_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['facility_name_c']['vname']='LBL_FACILITY_NAME_C';
$dictionary['AOS_Contracts']['fields']['facility_name_c']['source']='custom_fields';

 ?>