<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['shipping_c']['name']='shipping_c';
$dictionary['AOS_Contracts']['fields']['shipping_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['default']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['shipping_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['shipping_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['shipping_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['shipping_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['shipping_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['shipping_c']['options']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['help']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['shipping_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['shipping_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['shipping_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['shipping_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['shipping_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['shipping_c']['vname']='LBL_SHIPPING_C';
$dictionary['AOS_Contracts']['fields']['shipping_c']['source']='custom_fields';

 ?>