<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['name']='attachment_to_master_c';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['default']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['options']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['help']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['vname']='LBL_ATTACHMENT_TO_MASTER_C';
$dictionary['AOS_Contracts']['fields']['attachment_to_master_c']['source']='custom_fields';

 ?>