<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['name']='maintenance_and_support_year_2_c';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['default']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['options']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['help']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['vname']='LBL_MAINTENANCE_AND_SUPPORT_YEAR_2_C';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_2_c']['source']='custom_fields';

 ?>