<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['name']='apttus_company_signed_title_c';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['len']='80';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['vname']='LBL_APTTUS_COMPANY_SIGNED_TITLE_C';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_title_c']['source']='custom_fields';

 ?>