<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['name']='baa_template_source_c';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['default']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['options']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['help']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['vname']='LBL_BAA_TEMPLATE_SOURCE_C';
$dictionary['AOS_Contracts']['fields']['baa_template_source_c']['source']='custom_fields';

 ?>