<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['stage_c']['name']='stage_c';
$dictionary['AOS_Contracts']['fields']['stage_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['default']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['stage_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['stage_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['stage_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['stage_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['stage_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['stage_c']['options']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['help']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['stage_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['stage_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['stage_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['stage_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['stage_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['stage_c']['vname']='LBL_STAGE_C';
$dictionary['AOS_Contracts']['fields']['stage_c']['source']='custom_fields';

 ?>