<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['name']='apttus_latestdocid_c';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['vname']='LBL_APTTUS_LATESTDOCID_C';
$dictionary['AOS_Contracts']['fields']['apttus_latestdocid_c']['source']='custom_fields';

 ?>