<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['name']='apttus_ff_generate_supporting_document_c';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['vname']='LBL_APTTUS_FF_GENERATE_SUPPORTING_DOCUMENT_C';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_supporting_document_c']['source']='custom_fields';

 ?>