<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['name']='apttus_company_signed_date_c';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['type']='date';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['vname']='LBL_APTTUS_COMPANY_SIGNED_DATE_C';
$dictionary['AOS_Contracts']['fields']['apttus_company_signed_date_c']['source']='custom_fields';

 ?>