<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['name']='apttus_ff_generate_unprotected_agreement_c';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['vname']='LBL_APTTUS_FF_GENERATE_UNPROTECTED_AGREEMENT_C';
$dictionary['AOS_Contracts']['fields']['apttus_ff_generate_unprotected_agreement_c']['source']='custom_fields';

 ?>