<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['name']='apttus_other_party_signed_by_unlisted_c';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['vname']='LBL_APTTUS_OTHER_PARTY_SIGNED_BY_UNLISTED_C';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_unlisted_c']['source']='custom_fields';

 ?>