<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['name']='primary_contact_phone_number_c';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['default']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['options']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['help']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['vname']='LBL_PRIMARY_CONTACT_PHONE_NUMBER_C';
$dictionary['AOS_Contracts']['fields']['primary_contact_phone_number_c']['source']='custom_fields';

 ?>