<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['name']='right_to_dispute_waiver_c';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['default']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['options']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['help']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['vname']='LBL_RIGHT_TO_DISPUTE_WAIVER_C';
$dictionary['AOS_Contracts']['fields']['right_to_dispute_waiver_c']['source']='custom_fields';

 ?>