<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['name']='apttus_isinternalreview_c';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['vname']='LBL_APTTUS_ISINTERNALREVIEW_C';
$dictionary['AOS_Contracts']['fields']['apttus_isinternalreview_c']['source']='custom_fields';

 ?>