<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['name']='general_terms_and_conditions_c';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['default']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['options']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['help']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['vname']='LBL_GENERAL_TERMS_AND_CONDITIONS_C';
$dictionary['AOS_Contracts']['fields']['general_terms_and_conditions_c']['source']='custom_fields';

 ?>