<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['name']='extended_voice_retention_c';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['default']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['options']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['help']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['vname']='LBL_EXTENDED_VOICE_RETENTION_C';
$dictionary['AOS_Contracts']['fields']['extended_voice_retention_c']['source']='custom_fields';

 ?>