<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['name']='coding_global_permissions_c';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['default']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['options']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['help']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['vname']='LBL_CODING_GLOBAL_PERMISSIONS_C';
$dictionary['AOS_Contracts']['fields']['coding_global_permissions_c']['source']='custom_fields';

 ?>