<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['name']='cancellation_reason_c';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['default']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['options']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['help']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['vname']='LBL_CANCELLATION_REASON_C';
$dictionary['AOS_Contracts']['fields']['cancellation_reason_c']['source']='custom_fields';

 ?>