<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['name']='apttus_other_party_signed_by_c';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['len']='18';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['vname']='LBL_APTTUS_OTHER_PARTY_SIGNED_BY_C';
$dictionary['AOS_Contracts']['fields']['apttus_other_party_signed_by_c']['source']='custom_fields';

 ?>