<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['name']='tos_term_mm_c';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['default']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['options']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['help']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['vname']='LBL_TOS_TERM_MM_C';
$dictionary['AOS_Contracts']['fields']['tos_term_mm_c']['source']='custom_fields';

 ?>