<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['name']='gma_service_level_c';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['default']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['len']='4099';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['options']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['help']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['vname']='LBL_GMA_SERVICE_LEVEL_C';
$dictionary['AOS_Contracts']['fields']['gma_service_level_c']['source']='custom_fields';

 ?>