<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['name']='ff_fix_send_to_other_party_signatures_c';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['default']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['options']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['help']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['vname']='LBL_FF_FIX_SEND_TO_OTHER_PARTY_SIGNATURES_C';
$dictionary['AOS_Contracts']['fields']['ff_fix_send_to_other_party_signatures_c']['source']='custom_fields';

 ?>