<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['name']='limitation_of_liability_c';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['default']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['options']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['help']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['vname']='LBL_LIMITATION_OF_LIABILITY_C';
$dictionary['AOS_Contracts']['fields']['limitation_of_liability_c']['source']='custom_fields';

 ?>