<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['name']='type_of_product_services_c';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['default']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['len']='4099';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['options']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['help']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['vname']='LBL_TYPE_OF_PRODUCT_SERVICES_C';
$dictionary['AOS_Contracts']['fields']['type_of_product_services_c']['source']='custom_fields';

 ?>