<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['name']='product_term_for_convenien_c';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['default']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['options']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['help']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['vname']='LBL_PRODUCT_TERM_FOR_CONVENIEN_C';
$dictionary['AOS_Contracts']['fields']['product_term_for_convenien_c']['source']='custom_fields';

 ?>