<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['name']='record_type_id_c';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['default']='';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['len']='18';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['type']='enum';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['options']='record_type_dom';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['help']='';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['vname']='LBL_RECORD_TYPE_ID';
$dictionary['AOS_Contracts']['fields']['record_type_id_c']['source']='custom_fields';

?>