<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['name']='apttus_submit_request_mode_c';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['vname']='LBL_APTTUS_SUBMIT_REQUEST_MODE_C';
$dictionary['AOS_Contracts']['fields']['apttus_submit_request_mode_c']['source']='custom_fields';

 ?>