<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['name']='stat_report_tat_c';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['default']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['options']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['help']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['vname']='LBL_STAT_REPORT_TAT_C';
$dictionary['AOS_Contracts']['fields']['stat_report_tat_c']['source']='custom_fields';

 ?>