<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['name']='union_mt_s_c';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['default']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['options']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['help']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['vname']='LBL_UNION_MT_S_C';
$dictionary['AOS_Contracts']['fields']['union_mt_s_c']['source']='custom_fields';

 ?>