<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['name']='apttus_risk_rating_c';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['vname']='LBL_APTTUS_RISK_RATING_C';
$dictionary['AOS_Contracts']['fields']['apttus_risk_rating_c']['source']='custom_fields';

 ?>