<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['name']='confidentiality_default_cure_period_c';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['default']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['options']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['help']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['vname']='LBL_CONFIDENTIALITY_DEFAULT_CURE_PERIOD_C';
$dictionary['AOS_Contracts']['fields']['confidentiality_default_cure_period_c']['source']='custom_fields';

 ?>