<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['name']='product_maintenance_and_support_auto_ren_c';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['default']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['options']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['help']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['vname']='LBL_PRODUCT_MAINTENANCE_AND_SUPPORT_AUTO_REN_C';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_auto_ren_c']['source']='custom_fields';

 ?>