<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['name']='progress_bar_c';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['default']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['options']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['help']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['vname']='LBL_PROGRESS_BAR_C';
$dictionary['AOS_Contracts']['fields']['progress_bar_c']['source']='custom_fields';

 ?>