<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['name']='passive_adaptation_type_c';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['default']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['options']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['help']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['vname']='LBL_PASSIVE_ADAPTATION_TYPE_C';
$dictionary['AOS_Contracts']['fields']['passive_adaptation_type_c']['source']='custom_fields';

 ?>