<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['product_cia_c']['name']='product_cia_c';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['default']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['product_cia_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['product_cia_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['product_cia_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['product_cia_c']['options']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['help']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['product_cia_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['product_cia_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['product_cia_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['product_cia_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['vname']='LBL_PRODUCT_CIA_C';
$dictionary['AOS_Contracts']['fields']['product_cia_c']['source']='custom_fields';

 ?>