<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['name']='apttus_account_search_field_c';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['vname']='LBL_APTTUS_ACCOUNT_SEARCH_FIELD_C';
$dictionary['AOS_Contracts']['fields']['apttus_account_search_field_c']['source']='custom_fields';

 ?>