<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['name']='dq_tos_price_increase_c';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['default']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['options']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['help']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['vname']='LBL_DQ_TOS_PRICE_INCREASE_C';
$dictionary['AOS_Contracts']['fields']['dq_tos_price_increase_c']['source']='custom_fields';

 ?>