<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['name']='decimalerest_on_late_payments_c';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['default']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['options']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['help']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['vname']='LBL_DECIMALEREST_ON_LATE_PAYMENTS_C';
$dictionary['AOS_Contracts']['fields']['decimalerest_on_late_payments_c']['source']='custom_fields';

 ?>