<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['name']='apttus_related_opportunity_c';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['len']='18';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['vname']='LBL_APTTUS_RELATED_OPPORTUNITY_C';
$dictionary['AOS_Contracts']['fields']['apttus_related_opportunity_c']['source']='custom_fields';

 ?>