<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['name']='product_maintenance_and_support_term_mo_c';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['default']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['options']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['help']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['vname']='LBL_PRODUCT_MAINTENANCE_AND_SUPPORT_TERM_MO_C';
$dictionary['AOS_Contracts']['fields']['product_maintenance_and_support_term_mo_c']['source']='custom_fields';

 ?>