<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['name']='apttus_ff_view_draft_contract_c';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['vname']='LBL_APTTUS_FF_VIEW_DRAFT_CONTRACT_C';
$dictionary['AOS_Contracts']['fields']['apttus_ff_view_draft_contract_c']['source']='custom_fields';

 ?>