<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['name']='maintenance_and_support_year_1_c';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['default']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['options']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['help']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['vname']='LBL_MAINTENANCE_AND_SUPPORT_YEAR_1_C';
$dictionary['AOS_Contracts']['fields']['maintenance_and_support_year_1_c']['source']='custom_fields';

 ?>