<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['owner_id']['name']='owner_id';
$dictionary['AOS_Contracts']['fields']['owner_id']['default_value']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['default']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['display_default']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['len']='18';
$dictionary['AOS_Contracts']['fields']['owner_id']['required']=false;
$dictionary['AOS_Contracts']['fields']['owner_id']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['owner_id']['audited']=0;
$dictionary['AOS_Contracts']['fields']['owner_id']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['owner_id']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['owner_id']['options']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['help']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['comments']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['importable']='true';
$dictionary['AOS_Contracts']['fields']['owner_id']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['owner_id']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['owner_id']['ext2']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['ext4']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['ext3']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['owner_id']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['owner_id']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['owner_id']['vname']='LBL_OWNER_ID';
$dictionary['AOS_Contracts']['fields']['owner_id']['source']='custom_fields';

 ?>