<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['name']='dq_cap_software_pricing_disc_c';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['default']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['options']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['help']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['vname']='LBL_DQ_CAP_SOFTWARE_PRICING_DISC_C';
$dictionary['AOS_Contracts']['fields']['dq_cap_software_pricing_disc_c']['source']='custom_fields';

 ?>