<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['name']='apttus_owner_expiration_notice_c';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['vname']='LBL_APTTUS_OWNER_EXPIRATION_NOTICE_C';
$dictionary['AOS_Contracts']['fields']['apttus_owner_expiration_notice_c']['source']='custom_fields';

 ?>