<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['name']='apttus_ff_submit_for_changes_c';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['vname']='LBL_APTTUS_FF_SUBMIT_FOR_CHANGES_C';
$dictionary['AOS_Contracts']['fields']['apttus_ff_submit_for_changes_c']['source']='custom_fields';

 ?>