<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['name']='tos_revenue_c';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['default']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['options']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['help']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['vname']='LBL_TOS_REVENUE_C';
$dictionary['AOS_Contracts']['fields']['tos_revenue_c']['source']='custom_fields';

 ?>