<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['name']='apttus_total_contract_value_c';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['vname']='LBL_APTTUS_TOTAL_CONTRACT_VALUE_C';
$dictionary['AOS_Contracts']['fields']['apttus_total_contract_value_c']['source']='custom_fields';

 ?>