<?php
// Vardefs from Fields_meta_data table - created:
$dictionary['AOS_Contracts']['fields']['requested_user_id']['name']='requested_user_id';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['default_value']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['default']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['display_default']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['len']='36';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['required']=false;
$dictionary['AOS_Contracts']['fields']['requested_user_id']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['audited']=0;
$dictionary['AOS_Contracts']['fields']['requested_user_id']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['requested_user_id']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['requested_user_id']['options']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['help']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['comments']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['importable']='true';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['requested_user_id']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['requested_user_id']['ext2']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['ext4']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['ext3']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['requested_user_id']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['requested_user_id']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['requested_user_id']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['requested_user_id']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['requested_user_id']['vname']='LBL_REQUESTED_USER_ID';
//$dictionary['AOS_Contracts']['fields']['requested_user_id']['source']='custom_fields';
?>