<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['name']='tos_termination_for_convenience_notice_c';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['default']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['options']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['help']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['vname']='LBL_TOS_TERMINATION_FOR_CONVENIENCE_NOTICE_C';
$dictionary['AOS_Contracts']['fields']['tos_termination_for_convenience_notice_c']['source']='custom_fields';

 ?>