<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['name']='mutual_default_c';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['default']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['options']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['help']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['vname']='LBL_MUTUAL_DEFAULT_C';
$dictionary['AOS_Contracts']['fields']['mutual_default_c']['source']='custom_fields';

 ?>