<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['name']='estimated_fft_new_volume_c';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['default']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['options']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['help']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['vname']='LBL_ESTIMATED_FFT_NEW_VOLUME_C';
$dictionary['AOS_Contracts']['fields']['estimated_fft_new_volume_c']['source']='custom_fields';

 ?>