<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['last_modified_date']['name']='last_modified_date';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['default_value']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['default']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['display_default']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['len']='255';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['required']=false;
$dictionary['AOS_Contracts']['fields']['last_modified_date']['type']='date';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['audited']=0;
$dictionary['AOS_Contracts']['fields']['last_modified_date']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['last_modified_date']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['last_modified_date']['options']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['help']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['comments']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['importable']='true';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['last_modified_date']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['last_modified_date']['ext2']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['ext4']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['ext3']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['last_modified_date']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['last_modified_date']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['vname']='LBL_LAST_MODIFIED_DATE';
$dictionary['AOS_Contracts']['fields']['last_modified_date']['source']='custom_fields';

 ?>