<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['name']='tax_exempt_c';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['default']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['options']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['help']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['vname']='LBL_TAX_EXEMPT_C';
$dictionary['AOS_Contracts']['fields']['tax_exempt_c']['source']='custom_fields';

 ?>