<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['name']='decimalellectual_property_general_informatio_c';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['default']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['options']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['help']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['vname']='LBL_DECIMALELLECTUAL_PROPERTY_GENERAL_INFORMATIO_C';
$dictionary['AOS_Contracts']['fields']['decimalellectual_property_general_informatio_c']['source']='custom_fields';

 ?>