<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['name']='tos_price_book_rate_v2_c';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['default']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['options']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['help']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['vname']='LBL_TOS_PRICE_BOOK_RATE_V2_C';
$dictionary['AOS_Contracts']['fields']['tos_price_book_rate_v2_c']['source']='custom_fields';

 ?>