<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['name']='ts_submitted_to_comm_ops_c';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['default']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['type']='datetimecombo';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['options']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['help']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['dbType']='datetime';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['vname']='LBL_TS_SUBMITTED_TO_COMM_OPS_C';
$dictionary['AOS_Contracts']['fields']['ts_submitted_to_comm_ops_c']['source']='custom_fields';

 ?>