<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['name']='use_of_data_continuous_improvement_c';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['default']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['options']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['help']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['vname']='LBL_USE_OF_DATA_CONTINUOUS_IMPROVEMENT_C';
$dictionary['AOS_Contracts']['fields']['use_of_data_continuous_improvement_c']['source']='custom_fields';

 ?>