<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['name']='apttus_remaining_contracted_days_c';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['vname']='LBL_APTTUS_REMAINING_CONTRACTED_DAYS_C';
$dictionary['AOS_Contracts']['fields']['apttus_remaining_contracted_days_c']['source']='custom_fields';

 ?>