<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['created_date']['name']='created_date';
$dictionary['AOS_Contracts']['fields']['created_date']['default_value']='';
$dictionary['AOS_Contracts']['fields']['created_date']['default']='';
$dictionary['AOS_Contracts']['fields']['created_date']['display_default']='';
$dictionary['AOS_Contracts']['fields']['created_date']['len']='255';
$dictionary['AOS_Contracts']['fields']['created_date']['required']=false;
$dictionary['AOS_Contracts']['fields']['created_date']['type']='date';
$dictionary['AOS_Contracts']['fields']['created_date']['audited']=0;
$dictionary['AOS_Contracts']['fields']['created_date']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['created_date']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['created_date']['options']='';
$dictionary['AOS_Contracts']['fields']['created_date']['help']='';
$dictionary['AOS_Contracts']['fields']['created_date']['comments']='';
$dictionary['AOS_Contracts']['fields']['created_date']['importable']='true';
$dictionary['AOS_Contracts']['fields']['created_date']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['created_date']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['created_date']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['created_date']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['created_date']['ext2']='';
$dictionary['AOS_Contracts']['fields']['created_date']['ext4']='';
$dictionary['AOS_Contracts']['fields']['created_date']['ext3']='';
$dictionary['AOS_Contracts']['fields']['created_date']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['created_date']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['created_date']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['created_date']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['created_date']['vname']='LBL_CREATED_DATE';
$dictionary['AOS_Contracts']['fields']['created_date']['source']='custom_fields';

 ?>