<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['name']='software_maintenance_and_support_c';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['default']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['options']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['help']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['vname']='LBL_SOFTWARE_MAINTENANCE_AND_SUPPORT_C';
$dictionary['AOS_Contracts']['fields']['software_maintenance_and_support_c']['source']='custom_fields';

 ?>