<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['name']='limited_liability_cap_c';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['default']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['options']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['help']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['vname']='LBL_LIMITED_LIABILITY_CAP_C';
$dictionary['AOS_Contracts']['fields']['limited_liability_cap_c']['source']='custom_fields';

 ?>