<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['name']='included_optional_system_components_c';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['default']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['len']='4099';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['options']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['help']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['vname']='LBL_INCLUDED_OPTIONAL_SYSTEM_COMPONENTS_C';
$dictionary['AOS_Contracts']['fields']['included_optional_system_components_c']['source']='custom_fields';

 ?>