<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['name']='last_modified_by_id';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['default_value']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['default']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['display_default']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['len']='18';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['required']=false;
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['audited']=0;
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['options']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['help']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['comments']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['importable']='true';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['ext2']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['ext4']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['ext3']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['vname']='LBL_LAST_MODIFIED_BY_ID';
$dictionary['AOS_Contracts']['fields']['last_modified_by_id']['source']='custom_fields';

 ?>