<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['name']='legal_entity_c';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['default']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['options']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['help']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['vname']='LBL_LEGAL_ENTITY_C';
$dictionary['AOS_Contracts']['fields']['legal_entity_c']['source']='custom_fields';

 ?>