<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['probability_c']['name']='probability_c';
$dictionary['AOS_Contracts']['fields']['probability_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['default']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['probability_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['probability_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['probability_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['probability_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['probability_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['probability_c']['options']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['help']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['probability_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['probability_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['probability_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['probability_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['probability_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['probability_c']['vname']='LBL_PROBABILITY_C';
$dictionary['AOS_Contracts']['fields']['probability_c']['source']='custom_fields';

 ?>