<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['name']='apttus_ff_execute_c';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['len']='1300';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['vname']='LBL_APTTUS_FF_EXECUTE_C';
$dictionary['AOS_Contracts']['fields']['apttus_ff_execute_c']['source']='custom_fields';

 ?>