<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['name']='dq_coding_commitment_c';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['default']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['len']='19';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['type']='int';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['options']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['help']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['autoinc_next']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['autoinc_start']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['auto_increment']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['min']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['max']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['disable_num_format']=NULL;
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['vname']='LBL_DQ_CODING_COMMITMENT_C';
$dictionary['AOS_Contracts']['fields']['dq_coding_commitment_c']['source']='custom_fields';

 ?>