<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['name']='ts_partially_executed_received_c';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['default']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['type']='date';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['options']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['help']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['vname']='LBL_TS_PARTIALLY_EXECUTED_RECEIVED_C';
$dictionary['AOS_Contracts']['fields']['ts_partially_executed_received_c']['source']='custom_fields';

 ?>