<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['name']='apttus_requestor_c';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['len']='18';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['vname']='LBL_APTTUS_REQUESTOR_C';
$dictionary['AOS_Contracts']['fields']['apttus_requestor_c']['source']='custom_fields';

 ?>