<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['record_type_id']['name']='record_type_id';
$dictionary['AOS_Contracts']['fields']['record_type_id']['default_value']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['default']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['display_default']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['len']='18';
$dictionary['AOS_Contracts']['fields']['record_type_id']['required']=false;
$dictionary['AOS_Contracts']['fields']['record_type_id']['type']='varchar';
$dictionary['AOS_Contracts']['fields']['record_type_id']['audited']=0;
$dictionary['AOS_Contracts']['fields']['record_type_id']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['record_type_id']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['record_type_id']['options']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['help']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['comments']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['importable']='true';
$dictionary['AOS_Contracts']['fields']['record_type_id']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['record_type_id']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['record_type_id']['ext2']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['ext4']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['ext3']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['record_type_id']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['record_type_id']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['record_type_id']['vname']='LBL_RECORD_TYPE_ID';
$dictionary['AOS_Contracts']['fields']['record_type_id']['source']='custom_fields';

 ?>