<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['name']='agreement_summary_c';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['default']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['options']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['help']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['vname']='LBL_AGREEMENT_SUMMARY_C';
$dictionary['AOS_Contracts']['fields']['agreement_summary_c']['source']='custom_fields';

 ?>