<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['name']='gpo_affiliation_verified_c';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['default']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['options']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['help']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['vname']='LBL_GPO_AFFILIATION_VERIFIED_C';
$dictionary['AOS_Contracts']['fields']['gpo_affiliation_verified_c']['source']='custom_fields';

 ?>