<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['name']='coding_renewal_terms_c';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['default']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['type']='text';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['options']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['help']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['rows']=NULL;
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['cols']=NULL;
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['vname']='LBL_CODING_RENEWAL_TERMS_C';
$dictionary['AOS_Contracts']['fields']['coding_renewal_terms_c']['source']='custom_fields';

 ?>