<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['name']='coding_global_permitted_c';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['default']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['options']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['help']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['vname']='LBL_CODING_GLOBAL_PERMITTED_C';
$dictionary['AOS_Contracts']['fields']['coding_global_permitted_c']['source']='custom_fields';

 ?>