<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['name']='strategic_deal_c';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['default']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['type']='bool';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['options']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['help']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['vname']='LBL_STRATEGIC_DEAL_C';
$dictionary['AOS_Contracts']['fields']['strategic_deal_c']['source']='custom_fields';

 ?>