<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['name']='apttus_retentiondate_c';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['default_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['default']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['display_default']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['len']='255';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['required']=false;
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['type']='datetimecombo';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['audited']=0;
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['inline_edit']=1;
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['massupdate']=0;
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['options']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['help']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['comments']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['importable']='true';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['duplicate_merge']=0;
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['duplicate_merge_dom_value']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['merge_filter']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['reportable']=true;
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['ext2']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['ext4']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['ext3']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['labelValue']=NULL;
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['unified_search']=0;
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['full_text_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['enable_range_search']='';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['dbType']='datetime';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['vname']='LBL_APTTUS_RETENTIONDATE_C';
$dictionary['AOS_Contracts']['fields']['apttus_retentiondate_c']['source']='custom_fields';

 ?>