<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['name']='maintenance_general_notes_c';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['default_value']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['default']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['display_default']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['len']='255';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['required']=false;
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['type']='text';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['audited']=0;
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['inline_edit']=1;
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['massupdate']=0;
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['options']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['help']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['comments']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['importable']='true';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['duplicate_merge']=0;
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['merge_filter']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['reportable']=true;
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['ext2']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['ext4']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['ext3']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['labelValue']=NULL;
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['unified_search']=0;
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['full_text_search']='';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['rows']=NULL;
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['cols']=NULL;
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['vname']='LBL_MAINTENANCE_GENERAL_NOTES_C';
$dictionary['SA_Products']['fields']['maintenance_general_notes_c']['source']='custom_fields';

 ?>