<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['name']='product_gma_renewal_term_c';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['default_value']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['default']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['display_default']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['len']='19';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['required']=false;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['type']='int';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['audited']=0;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['inline_edit']=1;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['massupdate']=0;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['options']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['help']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['comments']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['importable']='true';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['duplicate_merge']=0;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['merge_filter']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['reportable']=true;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['ext2']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['ext4']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['ext3']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['labelValue']=NULL;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['unified_search']=0;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['full_text_search']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['enable_range_search']='';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['autoinc_next']=NULL;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['autoinc_start']=NULL;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['auto_increment']=NULL;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['min']=NULL;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['max']=NULL;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['disable_num_format']=NULL;
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['vname']='LBL_PRODUCT_GMA_RENEWAL_TERM_C';
$dictionary['SA_Products']['fields']['product_gma_renewal_term_c']['source']='custom_fields';

 ?>