<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Products']['fields']['product_hosted_c']['name']='product_hosted_c';
$dictionary['SA_Products']['fields']['product_hosted_c']['default_value']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['default']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['display_default']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['len']='255';
$dictionary['SA_Products']['fields']['product_hosted_c']['required']=false;
$dictionary['SA_Products']['fields']['product_hosted_c']['type']='bool';
$dictionary['SA_Products']['fields']['product_hosted_c']['audited']=0;
$dictionary['SA_Products']['fields']['product_hosted_c']['inline_edit']=1;
$dictionary['SA_Products']['fields']['product_hosted_c']['massupdate']=0;
$dictionary['SA_Products']['fields']['product_hosted_c']['options']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['help']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['comments']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['importable']='true';
$dictionary['SA_Products']['fields']['product_hosted_c']['duplicate_merge']=0;
$dictionary['SA_Products']['fields']['product_hosted_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['merge_filter']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['reportable']=true;
$dictionary['SA_Products']['fields']['product_hosted_c']['ext2']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['ext4']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['ext3']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['labelValue']=NULL;
$dictionary['SA_Products']['fields']['product_hosted_c']['unified_search']=0;
$dictionary['SA_Products']['fields']['product_hosted_c']['full_text_search']='';
$dictionary['SA_Products']['fields']['product_hosted_c']['vname']='LBL_PRODUCT_HOSTED_C';
$dictionary['SA_Products']['fields']['product_hosted_c']['source']='custom_fields';

 ?>