<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Products']['fields']['cac_services_c']['name']='cac_services_c';
$dictionary['SA_Products']['fields']['cac_services_c']['default_value']='';
$dictionary['SA_Products']['fields']['cac_services_c']['default']='';
$dictionary['SA_Products']['fields']['cac_services_c']['display_default']='';
$dictionary['SA_Products']['fields']['cac_services_c']['len']='255';
$dictionary['SA_Products']['fields']['cac_services_c']['required']=false;
$dictionary['SA_Products']['fields']['cac_services_c']['type']='bool';
$dictionary['SA_Products']['fields']['cac_services_c']['audited']=0;
$dictionary['SA_Products']['fields']['cac_services_c']['inline_edit']=1;
$dictionary['SA_Products']['fields']['cac_services_c']['massupdate']=0;
$dictionary['SA_Products']['fields']['cac_services_c']['options']='';
$dictionary['SA_Products']['fields']['cac_services_c']['help']='';
$dictionary['SA_Products']['fields']['cac_services_c']['comments']='';
$dictionary['SA_Products']['fields']['cac_services_c']['importable']='true';
$dictionary['SA_Products']['fields']['cac_services_c']['duplicate_merge']=0;
$dictionary['SA_Products']['fields']['cac_services_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Products']['fields']['cac_services_c']['merge_filter']='';
$dictionary['SA_Products']['fields']['cac_services_c']['reportable']=true;
$dictionary['SA_Products']['fields']['cac_services_c']['ext2']='';
$dictionary['SA_Products']['fields']['cac_services_c']['ext4']='';
$dictionary['SA_Products']['fields']['cac_services_c']['ext3']='';
$dictionary['SA_Products']['fields']['cac_services_c']['labelValue']=NULL;
$dictionary['SA_Products']['fields']['cac_services_c']['unified_search']=0;
$dictionary['SA_Products']['fields']['cac_services_c']['full_text_search']='';
$dictionary['SA_Products']['fields']['cac_services_c']['vname']='LBL_CAC_SERVICES_C';
$dictionary['SA_Products']['fields']['cac_services_c']['source']='custom_fields';

 ?>