<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['name']='product_subscription_auto_renewal_c';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['default_value']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['default']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['display_default']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['len']='255';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['required']=false;
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['type']='bool';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['audited']=0;
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['inline_edit']=1;
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['massupdate']=0;
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['options']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['help']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['comments']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['importable']='true';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['duplicate_merge']=0;
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['merge_filter']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['reportable']=true;
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['ext2']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['ext4']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['ext3']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['labelValue']=NULL;
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['unified_search']=0;
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['full_text_search']='';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['vname']='LBL_PRODUCT_SUBSCRIPTION_AUTO_RENEWAL_C';
$dictionary['SA_Products']['fields']['product_subscription_auto_renewal_c']['source']='custom_fields';

 ?>