<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Products']['fields']['product_billing_terms_c']['name']='product_billing_terms_c';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['default_value']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['default']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['display_default']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['len']='255';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['required']=false;
$dictionary['SA_Products']['fields']['product_billing_terms_c']['type']='bool';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['audited']=0;
$dictionary['SA_Products']['fields']['product_billing_terms_c']['inline_edit']=1;
$dictionary['SA_Products']['fields']['product_billing_terms_c']['massupdate']=0;
$dictionary['SA_Products']['fields']['product_billing_terms_c']['options']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['help']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['comments']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['importable']='true';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['duplicate_merge']=0;
$dictionary['SA_Products']['fields']['product_billing_terms_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['merge_filter']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['reportable']=true;
$dictionary['SA_Products']['fields']['product_billing_terms_c']['ext2']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['ext4']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['ext3']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['labelValue']=NULL;
$dictionary['SA_Products']['fields']['product_billing_terms_c']['unified_search']=0;
$dictionary['SA_Products']['fields']['product_billing_terms_c']['full_text_search']='';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['vname']='LBL_PRODUCT_BILLING_TERMS_C';
$dictionary['SA_Products']['fields']['product_billing_terms_c']['source']='custom_fields';

 ?>