<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Products']['fields']['product_billing_c']['name']='product_billing_c';
$dictionary['SA_Products']['fields']['product_billing_c']['default_value']='';
$dictionary['SA_Products']['fields']['product_billing_c']['default']='';
$dictionary['SA_Products']['fields']['product_billing_c']['display_default']='';
$dictionary['SA_Products']['fields']['product_billing_c']['len']='255';
$dictionary['SA_Products']['fields']['product_billing_c']['required']=false;
$dictionary['SA_Products']['fields']['product_billing_c']['type']='text';
$dictionary['SA_Products']['fields']['product_billing_c']['audited']=0;
$dictionary['SA_Products']['fields']['product_billing_c']['inline_edit']=1;
$dictionary['SA_Products']['fields']['product_billing_c']['massupdate']=0;
$dictionary['SA_Products']['fields']['product_billing_c']['options']='';
$dictionary['SA_Products']['fields']['product_billing_c']['help']='';
$dictionary['SA_Products']['fields']['product_billing_c']['comments']='';
$dictionary['SA_Products']['fields']['product_billing_c']['importable']='true';
$dictionary['SA_Products']['fields']['product_billing_c']['duplicate_merge']=0;
$dictionary['SA_Products']['fields']['product_billing_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Products']['fields']['product_billing_c']['merge_filter']='';
$dictionary['SA_Products']['fields']['product_billing_c']['reportable']=true;
$dictionary['SA_Products']['fields']['product_billing_c']['ext2']='';
$dictionary['SA_Products']['fields']['product_billing_c']['ext4']='';
$dictionary['SA_Products']['fields']['product_billing_c']['ext3']='';
$dictionary['SA_Products']['fields']['product_billing_c']['labelValue']=NULL;
$dictionary['SA_Products']['fields']['product_billing_c']['unified_search']=0;
$dictionary['SA_Products']['fields']['product_billing_c']['full_text_search']='';
$dictionary['SA_Products']['fields']['product_billing_c']['rows']=NULL;
$dictionary['SA_Products']['fields']['product_billing_c']['cols']=NULL;
$dictionary['SA_Products']['fields']['product_billing_c']['vname']='LBL_PRODUCT_BILLING_C';
$dictionary['SA_Products']['fields']['product_billing_c']['source']='custom_fields';

 ?>