<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['name']='fluency_for_coding_platform_c';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['default_value']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['default']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['display_default']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['len']='255';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['required']=false;
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['type']='bool';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['audited']=0;
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['inline_edit']=1;
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['massupdate']=0;
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['options']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['help']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['comments']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['importable']='true';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['duplicate_merge']=0;
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['merge_filter']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['reportable']=true;
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['ext2']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['ext4']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['ext3']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['labelValue']=NULL;
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['unified_search']=0;
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['full_text_search']='';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['vname']='LBL_FLUENCY_FOR_CODING_PLATFORM_C';
$dictionary['SA_Products']['fields']['fluency_for_coding_platform_c']['source']='custom_fields';

 ?>