//V3.0
QCRM.UnifiedSearch=['Accounts','Opportunities','Meetings'];QCRM.users_dropdown=false;
QCRM.share_search='All';
QCRM.native_cal=true;
QCRM.AOS_show_image=true;
QCRM.forceLock=true;
QCRM.AudioNotes=true;
QCRM.enableBeans(['Accounts','C1_Cust_Contacts1','A4_SITES','A4_SITE_ROLES','Calls','Meetings','Tasks','Cases','Notes','Documents','Opportunities']);
Beans['Accounts'].AdditionalFields = ['phone_office','website','$ADDbilling','date_entered','date_modified','himss_id_c','defintive_id_c','ucid_c','facility_type_dd_c','assigned_user_name'];
Beans['Accounts'].SearchFields = ['parent_name','himss_id_c','defintive_id_c','ucid_c','facility_type_dd_c'];
Beans['Accounts'].CustomListFields = ['parent_name','billing_address_city','facility_type_dd_c','ucid_c','defintive_id_c','himss_id_c','billing_address_state'];
Beans['Accounts'].CustomLinks = {'members':{title:'LBL_MEMBERS'},'c1_cust_contacts1_accounts':{title:'C1_Cust_Contacts1'},'accounts_a4_sites_1':{title:'A4_SITES'},'cases':{title:'Cases'},'calls':{title:'Calls'},'meetings':{title:'Meetings'},'tasks':{title:'Tasks'}};
Beans['Accounts'].ColoredField = 'facility_type_dd_c';
Beans['C1_Cust_Contacts1'].AdditionalFields = ['title','email1','phone_home','phone_mobile','phone_work','phone_other','contact_type','contact_association','survey'];
Beans['C1_Cust_Contacts1'].SearchFields = ['contact_association','email1','survey'];
Beans['C1_Cust_Contacts1'].CustomListFields = ['title','email1','contact_type','contact_association'];
Beans['C1_Cust_Contacts1'].TitleFields = ['first_name','last_name'];
Beans['C1_Cust_Contacts1'].CustomLinks = {'c1_cust_contacts1_accounts':{title:'Accounts'}};
Beans['A4_SITES'].AdditionalFields = ['accounts_a4_sites_1_name','parent','customer_no_c','ucid','himss_id','aplatform_c','definitive_id','cc_region_dd_c','active_date','tier_dd_c','term_date','fd_c','fvm_c','ff_c','fm_c','b2b_c','ffi_c','ffc_c','cdia_c','cdie_c','cdic_c','dwi_c'];
Beans['A4_SITES'].SearchFields = ['customer_no_c','parent','ucid','aplatform_c','tier_dd_c','cc_region_dd_c'];
Beans['A4_SITES'].CustomLinks = {'a4_sites_a4_site_roles_1':{title:'A4_SITE_ROLES'},'accounts_a4_sites_1':{title:'LBL_ACCOUNTS_A4_SITES_1_FROM_ACCOUNTS_TITLE'}};
Beans['A4_SITE_ROLES'].AdditionalFields = ['a4_sites_a4_site_roles_1_name','assigned_user_name','active_c'];
Beans['A4_SITE_ROLES'].SearchFields = ['a4_sites_a4_site_roles_1_name','assigned_user_name','active_c'];
Beans['A4_SITE_ROLES'].CustomListFields = ['a4_sites_a4_site_roles_1_name','assigned_user_name','active_c'];
Beans['A4_SITE_ROLES'].CustomLinks = {'a4_sites_a4_site_roles_1':{title:'LBL_A4_SITES_A4_SITE_ROLES_1_FROM_A4_SITES_TITLE'}};
Beans['Calls'].AdditionalFields = ['direction','status','date_start','duration_hours','duration_minutes','description','parent_name'];
Beans['Calls'].SearchFields = ['status','date_start'];
Beans['Calls'].CustomListFields = ['status','parent_name','date_start'];
Beans['Calls'].CustomLinks = {'users':{title:'Users'},'notes':{title:'Notes'}};
Beans['Meetings'].AdditionalFields = ['status','date_start','duration_hours','duration_minutes','description','parent_name'];
Beans['Meetings'].SearchFields = ['status','date_start'];
Beans['Meetings'].CustomListFields = ['status','parent_name','date_start'];
Beans['Meetings'].CustomLinks = {'users':{title:'Users'},'notes':{title:'Notes'}};
Beans['Tasks'].AdditionalFields = ['status','date_start','date_due','priority','description','contact_name','parent_name'];
Beans['Tasks'].SearchFields = ['status','date_due','priority'];
Beans['Tasks'].CustomListFields = ['status','date_start','date_due','priority'];
Beans['Tasks'].CustomLinks = {'notes':{title:'Notes'}};
Beans['Cases'].AdditionalFields = ['remedy_ticket_no_c','description','account_name','priority','status','product_c','jira_issue_id_c','assigned_user_name'];
Beans['Cases'].DetailFields = ['name','case_number','status','priority','description','account_name','aop_case_updates_threaded'];
Beans['Cases'].SearchFields = ['remedy_ticket_no_c','description','account_name','product_c','jira_issue_id_c','status','priority'];
Beans['Cases'].CustomListFields = ['remedy_ticket_no_c','description','account_name','priority','status','product_c','jira_issue_id_c','assigned_user_name'];
Beans['Cases'].CustomLinks = [];
Beans['Cases'].ColoredField = 'status';
Beans['Notes'].AdditionalFields = ['description','filename'];
Beans['Notes'].CustomListFields = ['filename'];
Beans['Notes'].CustomLinks = [];
Beans['Documents'].AdditionalFields = ['description','status_id','category_id'];
Beans['Documents'].SearchFields = ['status_id','category_id'];
Beans['Documents'].TitleFields = ['document_name'];
Beans['Documents'].CustomLinks = [];
Beans['Opportunities'].AdditionalFields = ['amount','date_closed','sales_stage','account_name','description'];
Beans['Opportunities'].SearchFields = ['date_closed','sales_stage'];
Beans['Opportunities'].CustomListFields = ['amount','account_name','sales_stage','date_closed'];
Beans['Opportunities'].CustomLinks = {'calls':{title:'Calls'},'meetings':{title:'Meetings'},'tasks':{title:'Tasks'},'notes':{title:'Notes'}};
QCRM.Profiles={};QCRM.ProfileMode='SecurityGroups';
RowsPerPage=20;RowsPerDashlet=5;RowsPerSubPanel=5;
SimpleBeans['Users'].query += 'AND (users.is_group=0 OR users.is_group IS NULL)';
QCRM.addressFields=['street','city','state','postalcode','country'];
QCRM.google_addressFields=['street','city','state','postalcode','country'];
