<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['name']='fft_pricing_category_rate_c';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['default_value']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['default']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['display_default']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['len']='19';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['required']=false;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['type']='int';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['audited']=0;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['options']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['help']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['comments']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['importable']='true';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['reportable']=true;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['ext2']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['ext4']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['ext3']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['enable_range_search']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['autoinc_next']=NULL;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['autoinc_start']=NULL;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['auto_increment']=NULL;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['min']=NULL;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['max']=NULL;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['disable_num_format']=NULL;
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['vname']='LBL_FFT_PRICING_CATEGORY_RATE_C';
$dictionary['SA_Services']['fields']['fft_pricing_category_rate_c']['source']='custom_fields';

 ?>