<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['name']='tos_pricing_category_c';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['default_value']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['default']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['display_default']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['len']='4099';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['required']=false;
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['type']='text';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['audited']=0;
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['options']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['help']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['comments']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['importable']='true';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['reportable']=true;
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['ext2']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['ext4']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['ext3']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['rows']=NULL;
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['cols']=NULL;
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['vname']='LBL_TOS_PRICING_CATEGORY_C';
$dictionary['SA_Services']['fields']['tos_pricing_category_c']['source']='custom_fields';

 ?>