<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['name']='tos_price_increase_during_initial_term_c';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['default_value']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['default']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['display_default']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['len']='255';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['required']=false;
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['type']='bool';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['audited']=0;
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['options']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['help']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['comments']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['importable']='true';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['reportable']=true;
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['ext2']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['ext4']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['ext3']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['vname']='LBL_TOS_PRICE_INCREASE_DURING_INITIAL_TERM_C';
$dictionary['SA_Services']['fields']['tos_price_increase_during_initial_term_c']['source']='custom_fields';

 ?>