<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['name']='fft_pricing_category_uom_c';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['default_value']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['default']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['display_default']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['len']='255';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['required']=false;
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['type']='text';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['audited']=0;
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['options']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['help']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['comments']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['importable']='true';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['reportable']=true;
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['ext2']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['ext4']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['ext3']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['rows']=NULL;
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['cols']=NULL;
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['vname']='LBL_FFT_PRICING_CATEGORY_UOM_C';
$dictionary['SA_Services']['fields']['fft_pricing_category_uom_c']['source']='custom_fields';

 ?>