<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['name']='tat_credit_standard_c';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['default_value']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['default']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['display_default']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['len']='255';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['required']=false;
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['type']='bool';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['audited']=0;
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['options']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['help']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['comments']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['importable']='true';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['reportable']=true;
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['ext2']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['ext4']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['ext3']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['vname']='LBL_TAT_CREDIT_STANDARD_C';
$dictionary['SA_Services']['fields']['tat_credit_standard_c']['source']='custom_fields';

 ?>