<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['name']='tos_renewal_notification_period_dd_c';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['default_value']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['default']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['display_default']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['len']='19';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['required']=false;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['type']='int';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['audited']=0;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['options']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['help']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['comments']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['importable']='true';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['reportable']=true;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['ext2']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['ext4']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['ext3']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['enable_range_search']='';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['autoinc_next']=NULL;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['autoinc_start']=NULL;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['auto_increment']=NULL;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['min']=NULL;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['max']=NULL;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['disable_num_format']=NULL;
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['vname']='LBL_TOS_RENEWAL_NOTIFICATION_PERIOD_DD_C';
$dictionary['SA_Services']['fields']['tos_renewal_notification_period_dd_c']['source']='custom_fields';

 ?>