<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['name']='number_of_mt_s_for_hire_c';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['default_value']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['default']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['display_default']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['len']='19';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['required']=false;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['type']='int';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['audited']=0;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['options']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['help']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['comments']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['importable']='true';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['reportable']=true;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['ext2']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['ext4']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['ext3']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['enable_range_search']='';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['autoinc_next']=NULL;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['autoinc_start']=NULL;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['auto_increment']=NULL;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['min']=NULL;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['max']=NULL;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['disable_num_format']=NULL;
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['vname']='LBL_NUMBER_OF_MT_S_FOR_HIRE_C';
$dictionary['SA_Services']['fields']['number_of_mt_s_for_hire_c']['source']='custom_fields';

 ?>