<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['name']='coding_renewal_consent_c';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['default_value']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['default']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['display_default']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['len']='255';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['required']=false;
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['type']='bool';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['audited']=0;
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['options']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['help']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['comments']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['importable']='true';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['reportable']=true;
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['ext2']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['ext4']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['ext3']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['vname']='LBL_CODING_RENEWAL_CONSENT_C';
$dictionary['SA_Services']['fields']['coding_renewal_consent_c']['source']='custom_fields';

 ?>