<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['name']='service_or_product_warranty_c';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['default_value']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['default']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['display_default']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['len']='255';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['required']=false;
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['type']='text';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['audited']=0;
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['options']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['help']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['comments']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['importable']='true';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['reportable']=true;
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['ext2']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['ext4']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['ext3']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['rows']=NULL;
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['cols']=NULL;
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['vname']='LBL_SERVICE_OR_PRODUCT_WARRANTY_C';
$dictionary['SA_Services']['fields']['service_or_product_warranty_c']['source']='custom_fields';

 ?>