<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['name']='tos_attachment_number_c';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['default_value']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['default']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['display_default']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['len']='19';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['required']=false;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['type']='int';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['audited']=0;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['options']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['help']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['comments']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['importable']='true';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['reportable']=true;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['ext2']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['ext4']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['ext3']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['enable_range_search']='';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['autoinc_next']=NULL;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['autoinc_start']=NULL;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['auto_increment']=NULL;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['min']=NULL;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['max']=NULL;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['disable_num_format']=NULL;
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['vname']='LBL_TOS_ATTACHMENT_NUMBER_C';
$dictionary['SA_Services']['fields']['tos_attachment_number_c']['source']='custom_fields';

 ?>