<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['name']='qa_penalty_details_c';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['default_value']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['default']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['display_default']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['len']='2000';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['required']=false;
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['type']='text';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['audited']=0;
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['options']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['help']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['comments']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['importable']='true';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['reportable']=true;
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['ext2']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['ext4']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['ext3']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['rows']=NULL;
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['cols']=NULL;
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['vname']='LBL_QA_PENALTY_DETAILS_C';
$dictionary['SA_Services']['fields']['qa_penalty_details_c']['source']='custom_fields';

 ?>