<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['name']='fft_auto_renew_c';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['default_value']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['default']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['display_default']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['len']='255';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['required']=false;
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['type']='bool';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['audited']=0;
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['options']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['help']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['comments']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['importable']='true';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['reportable']=true;
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['ext2']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['ext4']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['ext3']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['vname']='LBL_FFT_AUTO_RENEW_C';
$dictionary['SA_Services']['fields']['fft_auto_renew_c']['source']='custom_fields';

 ?>