<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['SA_Services']['fields']['fft_evergreen_c']['name']='fft_evergreen_c';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['default_value']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['default']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['display_default']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['len']='255';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['required']=false;
$dictionary['SA_Services']['fields']['fft_evergreen_c']['type']='bool';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['audited']=0;
$dictionary['SA_Services']['fields']['fft_evergreen_c']['inline_edit']=1;
$dictionary['SA_Services']['fields']['fft_evergreen_c']['massupdate']=0;
$dictionary['SA_Services']['fields']['fft_evergreen_c']['options']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['help']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['comments']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['importable']='true';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['duplicate_merge']=0;
$dictionary['SA_Services']['fields']['fft_evergreen_c']['duplicate_merge_dom_value']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['merge_filter']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['reportable']=true;
$dictionary['SA_Services']['fields']['fft_evergreen_c']['ext2']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['ext4']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['ext3']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['labelValue']=NULL;
$dictionary['SA_Services']['fields']['fft_evergreen_c']['unified_search']=0;
$dictionary['SA_Services']['fields']['fft_evergreen_c']['full_text_search']='';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['vname']='LBL_FFT_EVERGREEN_C';
$dictionary['SA_Services']['fields']['fft_evergreen_c']['source']='custom_fields';

 ?>