<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['name']='adoption_services_term_length_c';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['default_value']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['default']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['display_default']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['len']='255';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['required']=false;
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['type']='real';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['audited']=0;
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['options']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['help']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['comments']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['importable']='true';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['reportable']=true;
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['ext2']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['ext4']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['ext3']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['vname']='LBL_ADOPTION_SERVICES_TERM_LENGTH_C';
$dictionary['Opportunity']['fields']['adoption_services_term_length_c']['source']='custom_fields';

 ?>