<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['mq_unit_price_c']['name']='mq_unit_price_c';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['default_value']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['default']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['display_default']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['len']='255';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['required']=false;
$dictionary['Opportunity']['fields']['mq_unit_price_c']['type']='real';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['audited']=0;
$dictionary['Opportunity']['fields']['mq_unit_price_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['mq_unit_price_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['mq_unit_price_c']['options']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['help']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['comments']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['importable']='true';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['mq_unit_price_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['reportable']=true;
$dictionary['Opportunity']['fields']['mq_unit_price_c']['ext2']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['ext4']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['ext3']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['mq_unit_price_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['mq_unit_price_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['vname']='LBL_MQ_UNIT_PRICE_C';
$dictionary['Opportunity']['fields']['mq_unit_price_c']['source']='custom_fields';

 ?>