<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['co_third_party_software_c']['name']='co_third_party_software_c';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['default_value']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['default']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['display_default']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['len']='255';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['required']=false;
$dictionary['Opportunity']['fields']['co_third_party_software_c']['type']='real';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['audited']=0;
$dictionary['Opportunity']['fields']['co_third_party_software_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['co_third_party_software_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['co_third_party_software_c']['options']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['help']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['comments']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['importable']='true';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['co_third_party_software_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['reportable']=true;
$dictionary['Opportunity']['fields']['co_third_party_software_c']['ext2']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['ext4']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['ext3']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['co_third_party_software_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['co_third_party_software_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['vname']='LBL_CO_THIRD_PARTY_SOFTWARE_C';
$dictionary['Opportunity']['fields']['co_third_party_software_c']['source']='custom_fields';

 ?>