<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['count_c']['name']='count_c';
$dictionary['Opportunity']['fields']['count_c']['default_value']='';
$dictionary['Opportunity']['fields']['count_c']['default']='';
$dictionary['Opportunity']['fields']['count_c']['display_default']='';
$dictionary['Opportunity']['fields']['count_c']['len']='255';
$dictionary['Opportunity']['fields']['count_c']['required']=false;
$dictionary['Opportunity']['fields']['count_c']['type']='real';
$dictionary['Opportunity']['fields']['count_c']['audited']=0;
$dictionary['Opportunity']['fields']['count_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['count_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['count_c']['options']='';
$dictionary['Opportunity']['fields']['count_c']['help']='';
$dictionary['Opportunity']['fields']['count_c']['comments']='';
$dictionary['Opportunity']['fields']['count_c']['importable']='true';
$dictionary['Opportunity']['fields']['count_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['count_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['count_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['count_c']['reportable']=true;
$dictionary['Opportunity']['fields']['count_c']['ext2']='';
$dictionary['Opportunity']['fields']['count_c']['ext4']='';
$dictionary['Opportunity']['fields']['count_c']['ext3']='';
$dictionary['Opportunity']['fields']['count_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['count_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['count_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['count_c']['vname']='LBL_COUNT_C';
$dictionary['Opportunity']['fields']['count_c']['source']='custom_fields';

 ?>