<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['contract_document_c']['name']='contract_document_c';
$dictionary['Opportunity']['fields']['contract_document_c']['default_value']='';
$dictionary['Opportunity']['fields']['contract_document_c']['default']='';
$dictionary['Opportunity']['fields']['contract_document_c']['display_default']='';
$dictionary['Opportunity']['fields']['contract_document_c']['len']='255';
$dictionary['Opportunity']['fields']['contract_document_c']['required']=false;
$dictionary['Opportunity']['fields']['contract_document_c']['type']='text';
$dictionary['Opportunity']['fields']['contract_document_c']['audited']=0;
$dictionary['Opportunity']['fields']['contract_document_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['contract_document_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['contract_document_c']['options']='';
$dictionary['Opportunity']['fields']['contract_document_c']['help']='';
$dictionary['Opportunity']['fields']['contract_document_c']['comments']='';
$dictionary['Opportunity']['fields']['contract_document_c']['importable']='true';
$dictionary['Opportunity']['fields']['contract_document_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['contract_document_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['contract_document_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['contract_document_c']['reportable']=true;
$dictionary['Opportunity']['fields']['contract_document_c']['ext2']='';
$dictionary['Opportunity']['fields']['contract_document_c']['ext4']='';
$dictionary['Opportunity']['fields']['contract_document_c']['ext3']='';
$dictionary['Opportunity']['fields']['contract_document_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['contract_document_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['contract_document_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['contract_document_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['contract_document_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['contract_document_c']['vname']='LBL_CONTRACT_DOCUMENT_C';
$dictionary['Opportunity']['fields']['contract_document_c']['source']='custom_fields';

 ?>