<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['id']['name']='id';
$dictionary['Opportunity']['fields']['id']['default_value']='';
$dictionary['Opportunity']['fields']['id']['default']='';
$dictionary['Opportunity']['fields']['id']['display_default']='';
$dictionary['Opportunity']['fields']['id']['len']='18';
$dictionary['Opportunity']['fields']['id']['required']=false;
$dictionary['Opportunity']['fields']['id']['type']='varchar';
$dictionary['Opportunity']['fields']['id']['audited']=0;
$dictionary['Opportunity']['fields']['id']['inline_edit']=1;
$dictionary['Opportunity']['fields']['id']['massupdate']=0;
$dictionary['Opportunity']['fields']['id']['options']='';
$dictionary['Opportunity']['fields']['id']['help']='';
$dictionary['Opportunity']['fields']['id']['comments']='';
$dictionary['Opportunity']['fields']['id']['importable']='true';
$dictionary['Opportunity']['fields']['id']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['id']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['id']['merge_filter']='';
$dictionary['Opportunity']['fields']['id']['reportable']=true;
$dictionary['Opportunity']['fields']['id']['ext2']='';
$dictionary['Opportunity']['fields']['id']['ext4']='';
$dictionary['Opportunity']['fields']['id']['ext3']='';
$dictionary['Opportunity']['fields']['id']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['id']['unified_search']=0;
$dictionary['Opportunity']['fields']['id']['full_text_search']='';
$dictionary['Opportunity']['fields']['id']['vname']='LBL_ID';
$dictionary['Opportunity']['fields']['id']['source']='custom_fields';

 ?>