<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['co_annual_gma_c']['name']='co_annual_gma_c';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['default_value']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['default']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['display_default']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['len']='255';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['required']=false;
$dictionary['Opportunity']['fields']['co_annual_gma_c']['type']='real';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['audited']=0;
$dictionary['Opportunity']['fields']['co_annual_gma_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['co_annual_gma_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['co_annual_gma_c']['options']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['help']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['comments']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['importable']='true';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['co_annual_gma_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['reportable']=true;
$dictionary['Opportunity']['fields']['co_annual_gma_c']['ext2']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['ext4']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['ext3']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['co_annual_gma_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['co_annual_gma_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['vname']='LBL_CO_ANNUAL_GMA_C';
$dictionary['Opportunity']['fields']['co_annual_gma_c']['source']='custom_fields';

 ?>