<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['commit_c']['name']='commit_c';
$dictionary['Opportunity']['fields']['commit_c']['default_value']='';
$dictionary['Opportunity']['fields']['commit_c']['default']='';
$dictionary['Opportunity']['fields']['commit_c']['display_default']='';
$dictionary['Opportunity']['fields']['commit_c']['len']='255';
$dictionary['Opportunity']['fields']['commit_c']['required']=false;
$dictionary['Opportunity']['fields']['commit_c']['type']='real';
$dictionary['Opportunity']['fields']['commit_c']['audited']=0;
$dictionary['Opportunity']['fields']['commit_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['commit_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['commit_c']['options']='';
$dictionary['Opportunity']['fields']['commit_c']['help']='';
$dictionary['Opportunity']['fields']['commit_c']['comments']='';
$dictionary['Opportunity']['fields']['commit_c']['importable']='true';
$dictionary['Opportunity']['fields']['commit_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['commit_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['commit_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['commit_c']['reportable']=true;
$dictionary['Opportunity']['fields']['commit_c']['ext2']='';
$dictionary['Opportunity']['fields']['commit_c']['ext4']='';
$dictionary['Opportunity']['fields']['commit_c']['ext3']='';
$dictionary['Opportunity']['fields']['commit_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['commit_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['commit_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['commit_c']['vname']='LBL_COMMIT_C';
$dictionary['Opportunity']['fields']['commit_c']['source']='custom_fields';

 ?>