<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['name']='blank_related_item_code_c';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['default_value']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['default']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['display_default']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['len']='50';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['required']=false;
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['type']='varchar';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['audited']=0;
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['options']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['help']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['comments']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['importable']='true';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['reportable']=true;
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['ext2']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['ext4']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['ext3']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['vname']='LBL_BLANK_RELATED_ITEM_CODE_C';
$dictionary['Opportunity']['fields']['blank_related_item_code_c']['source']='custom_fields';

 ?>