<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['pricedown_variance_c']['name']='pricedown_variance_c';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['default_value']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['default']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['display_default']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['len']='255';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['required']=false;
$dictionary['Opportunity']['fields']['pricedown_variance_c']['type']='real';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['audited']=0;
$dictionary['Opportunity']['fields']['pricedown_variance_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['pricedown_variance_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['pricedown_variance_c']['options']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['help']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['comments']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['importable']='true';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['pricedown_variance_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['reportable']=true;
$dictionary['Opportunity']['fields']['pricedown_variance_c']['ext2']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['ext4']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['ext3']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['pricedown_variance_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['pricedown_variance_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['vname']='LBL_PRICEDOWN_VARIANCE_C';
$dictionary['Opportunity']['fields']['pricedown_variance_c']['source']='custom_fields';

 ?>