<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['di_c']['name']='di_c';
$dictionary['Opportunity']['fields']['di_c']['default_value']='';
$dictionary['Opportunity']['fields']['di_c']['default']='';
$dictionary['Opportunity']['fields']['di_c']['display_default']='';
$dictionary['Opportunity']['fields']['di_c']['len']='1300';
$dictionary['Opportunity']['fields']['di_c']['required']=false;
$dictionary['Opportunity']['fields']['di_c']['type']='text';
$dictionary['Opportunity']['fields']['di_c']['audited']=0;
$dictionary['Opportunity']['fields']['di_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['di_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['di_c']['options']='';
$dictionary['Opportunity']['fields']['di_c']['help']='';
$dictionary['Opportunity']['fields']['di_c']['comments']='';
$dictionary['Opportunity']['fields']['di_c']['importable']='true';
$dictionary['Opportunity']['fields']['di_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['di_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['di_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['di_c']['reportable']=true;
$dictionary['Opportunity']['fields']['di_c']['ext2']='';
$dictionary['Opportunity']['fields']['di_c']['ext4']='';
$dictionary['Opportunity']['fields']['di_c']['ext3']='';
$dictionary['Opportunity']['fields']['di_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['di_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['di_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['di_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['di_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['di_c']['vname']='LBL_DI_C';
$dictionary['Opportunity']['fields']['di_c']['source']='custom_fields';

 ?>