<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['co_hosting_c']['name']='co_hosting_c';
$dictionary['Opportunity']['fields']['co_hosting_c']['default_value']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['default']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['display_default']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['len']='255';
$dictionary['Opportunity']['fields']['co_hosting_c']['required']=false;
$dictionary['Opportunity']['fields']['co_hosting_c']['type']='real';
$dictionary['Opportunity']['fields']['co_hosting_c']['audited']=0;
$dictionary['Opportunity']['fields']['co_hosting_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['co_hosting_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['co_hosting_c']['options']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['help']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['comments']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['importable']='true';
$dictionary['Opportunity']['fields']['co_hosting_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['co_hosting_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['reportable']=true;
$dictionary['Opportunity']['fields']['co_hosting_c']['ext2']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['ext4']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['ext3']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['co_hosting_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['co_hosting_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['co_hosting_c']['vname']='LBL_CO_HOSTING_C';
$dictionary['Opportunity']['fields']['co_hosting_c']['source']='custom_fields';

 ?>