<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['product_capital_c']['name']='product_capital_c';
$dictionary['Opportunity']['fields']['product_capital_c']['default_value']='';
$dictionary['Opportunity']['fields']['product_capital_c']['default']='';
$dictionary['Opportunity']['fields']['product_capital_c']['display_default']='';
$dictionary['Opportunity']['fields']['product_capital_c']['len']='1300';
$dictionary['Opportunity']['fields']['product_capital_c']['required']=false;
$dictionary['Opportunity']['fields']['product_capital_c']['type']='text';
$dictionary['Opportunity']['fields']['product_capital_c']['audited']=0;
$dictionary['Opportunity']['fields']['product_capital_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['product_capital_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['product_capital_c']['options']='';
$dictionary['Opportunity']['fields']['product_capital_c']['help']='';
$dictionary['Opportunity']['fields']['product_capital_c']['comments']='';
$dictionary['Opportunity']['fields']['product_capital_c']['importable']='true';
$dictionary['Opportunity']['fields']['product_capital_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['product_capital_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['product_capital_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['product_capital_c']['reportable']=true;
$dictionary['Opportunity']['fields']['product_capital_c']['ext2']='';
$dictionary['Opportunity']['fields']['product_capital_c']['ext4']='';
$dictionary['Opportunity']['fields']['product_capital_c']['ext3']='';
$dictionary['Opportunity']['fields']['product_capital_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['product_capital_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['product_capital_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['product_capital_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['product_capital_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['product_capital_c']['vname']='LBL_PRODUCT_CAPITAL_C';
$dictionary['Opportunity']['fields']['product_capital_c']['source']='custom_fields';

 ?>