<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['fiscalyear']['name']='fiscalyear';
$dictionary['Opportunity']['fields']['fiscalyear']['default_value']='';
$dictionary['Opportunity']['fields']['fiscalyear']['default']='';
$dictionary['Opportunity']['fields']['fiscalyear']['display_default']='';
$dictionary['Opportunity']['fields']['fiscalyear']['len']='255';
$dictionary['Opportunity']['fields']['fiscalyear']['required']=false;
$dictionary['Opportunity']['fields']['fiscalyear']['type']='int';
$dictionary['Opportunity']['fields']['fiscalyear']['audited']=0;
$dictionary['Opportunity']['fields']['fiscalyear']['inline_edit']=1;
$dictionary['Opportunity']['fields']['fiscalyear']['massupdate']=0;
$dictionary['Opportunity']['fields']['fiscalyear']['options']='';
$dictionary['Opportunity']['fields']['fiscalyear']['help']='';
$dictionary['Opportunity']['fields']['fiscalyear']['comments']='';
$dictionary['Opportunity']['fields']['fiscalyear']['importable']='true';
$dictionary['Opportunity']['fields']['fiscalyear']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['fiscalyear']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['fiscalyear']['merge_filter']='';
$dictionary['Opportunity']['fields']['fiscalyear']['reportable']=true;
$dictionary['Opportunity']['fields']['fiscalyear']['ext2']='';
$dictionary['Opportunity']['fields']['fiscalyear']['ext4']='';
$dictionary['Opportunity']['fields']['fiscalyear']['ext3']='';
$dictionary['Opportunity']['fields']['fiscalyear']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['fiscalyear']['unified_search']=0;
$dictionary['Opportunity']['fields']['fiscalyear']['full_text_search']='';
$dictionary['Opportunity']['fields']['fiscalyear']['enable_range_search']='';
$dictionary['Opportunity']['fields']['fiscalyear']['autoinc_next']=NULL;
$dictionary['Opportunity']['fields']['fiscalyear']['autoinc_start']=NULL;
$dictionary['Opportunity']['fields']['fiscalyear']['auto_increment']=NULL;
$dictionary['Opportunity']['fields']['fiscalyear']['min']=NULL;
$dictionary['Opportunity']['fields']['fiscalyear']['max']=NULL;
$dictionary['Opportunity']['fields']['fiscalyear']['disable_num_format']=NULL;
$dictionary['Opportunity']['fields']['fiscalyear']['vname']='LBL_FISCALYEAR';
$dictionary['Opportunity']['fields']['fiscalyear']['source']='custom_fields';

 ?>