<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['channel_rep_c']['name']='channel_rep_c';
$dictionary['Opportunity']['fields']['channel_rep_c']['default_value']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['default']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['display_default']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['len']='18';
$dictionary['Opportunity']['fields']['channel_rep_c']['required']=false;
$dictionary['Opportunity']['fields']['channel_rep_c']['type']='varchar';
$dictionary['Opportunity']['fields']['channel_rep_c']['audited']=0;
$dictionary['Opportunity']['fields']['channel_rep_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['channel_rep_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['channel_rep_c']['options']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['help']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['comments']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['importable']='true';
$dictionary['Opportunity']['fields']['channel_rep_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['channel_rep_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['reportable']=true;
$dictionary['Opportunity']['fields']['channel_rep_c']['ext2']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['ext4']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['ext3']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['channel_rep_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['channel_rep_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['channel_rep_c']['vname']='LBL_CHANNEL_REP_C';
$dictionary['Opportunity']['fields']['channel_rep_c']['source']='custom_fields';

 ?>