<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['blank_discount_c']['name']='blank_discount_c';
$dictionary['Opportunity']['fields']['blank_discount_c']['default_value']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['default']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['display_default']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['len']='50';
$dictionary['Opportunity']['fields']['blank_discount_c']['required']=false;
$dictionary['Opportunity']['fields']['blank_discount_c']['type']='varchar';
$dictionary['Opportunity']['fields']['blank_discount_c']['audited']=0;
$dictionary['Opportunity']['fields']['blank_discount_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['blank_discount_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['blank_discount_c']['options']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['help']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['comments']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['importable']='true';
$dictionary['Opportunity']['fields']['blank_discount_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['blank_discount_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['reportable']=true;
$dictionary['Opportunity']['fields']['blank_discount_c']['ext2']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['ext4']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['ext3']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['blank_discount_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['blank_discount_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['blank_discount_c']['vname']='LBL_BLANK_DISCOUNT_C';
$dictionary['Opportunity']['fields']['blank_discount_c']['source']='custom_fields';

 ?>