<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['imaging_spiff_c']['name']='imaging_spiff_c';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['default_value']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['default']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['display_default']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['len']='3';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['required']=false;
$dictionary['Opportunity']['fields']['imaging_spiff_c']['type']='varchar';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['audited']=0;
$dictionary['Opportunity']['fields']['imaging_spiff_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['imaging_spiff_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['imaging_spiff_c']['options']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['help']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['comments']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['importable']='true';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['imaging_spiff_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['reportable']=true;
$dictionary['Opportunity']['fields']['imaging_spiff_c']['ext2']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['ext4']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['ext3']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['imaging_spiff_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['imaging_spiff_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['vname']='LBL_IMAGING_SPIFF_C';
$dictionary['Opportunity']['fields']['imaging_spiff_c']['source']='custom_fields';

 ?>