<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['commissions_ps_c']['name']='commissions_ps_c';
$dictionary['Opportunity']['fields']['commissions_ps_c']['default_value']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['default']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['display_default']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['len']='255';
$dictionary['Opportunity']['fields']['commissions_ps_c']['required']=false;
$dictionary['Opportunity']['fields']['commissions_ps_c']['type']='real';
$dictionary['Opportunity']['fields']['commissions_ps_c']['audited']=0;
$dictionary['Opportunity']['fields']['commissions_ps_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['commissions_ps_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['commissions_ps_c']['options']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['help']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['comments']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['importable']='true';
$dictionary['Opportunity']['fields']['commissions_ps_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['commissions_ps_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['reportable']=true;
$dictionary['Opportunity']['fields']['commissions_ps_c']['ext2']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['ext4']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['ext3']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['commissions_ps_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['commissions_ps_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['commissions_ps_c']['vname']='LBL_COMMISSIONS_PS_C';
$dictionary['Opportunity']['fields']['commissions_ps_c']['source']='custom_fields';

 ?>