<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['forecastcategory']['name']='forecastcategory';
$dictionary['Opportunity']['fields']['forecastcategory']['default_value']='';
$dictionary['Opportunity']['fields']['forecastcategory']['default']='';
$dictionary['Opportunity']['fields']['forecastcategory']['display_default']='';
$dictionary['Opportunity']['fields']['forecastcategory']['len']='40';
$dictionary['Opportunity']['fields']['forecastcategory']['required']=false;
$dictionary['Opportunity']['fields']['forecastcategory']['type']='varchar';
$dictionary['Opportunity']['fields']['forecastcategory']['audited']=0;
$dictionary['Opportunity']['fields']['forecastcategory']['inline_edit']=1;
$dictionary['Opportunity']['fields']['forecastcategory']['massupdate']=0;
$dictionary['Opportunity']['fields']['forecastcategory']['options']='';
$dictionary['Opportunity']['fields']['forecastcategory']['help']='';
$dictionary['Opportunity']['fields']['forecastcategory']['comments']='';
$dictionary['Opportunity']['fields']['forecastcategory']['importable']='true';
$dictionary['Opportunity']['fields']['forecastcategory']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['forecastcategory']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['forecastcategory']['merge_filter']='';
$dictionary['Opportunity']['fields']['forecastcategory']['reportable']=true;
$dictionary['Opportunity']['fields']['forecastcategory']['ext2']='';
$dictionary['Opportunity']['fields']['forecastcategory']['ext4']='';
$dictionary['Opportunity']['fields']['forecastcategory']['ext3']='';
$dictionary['Opportunity']['fields']['forecastcategory']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['forecastcategory']['unified_search']=0;
$dictionary['Opportunity']['fields']['forecastcategory']['full_text_search']='';
$dictionary['Opportunity']['fields']['forecastcategory']['vname']='LBL_FORECASTCATEGORY';
$dictionary['Opportunity']['fields']['forecastcategory']['source']='custom_fields';

 ?>