<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['mixed_c']['name']='mixed_c';
$dictionary['Opportunity']['fields']['mixed_c']['default_value']='';
$dictionary['Opportunity']['fields']['mixed_c']['default']='';
$dictionary['Opportunity']['fields']['mixed_c']['display_default']='';
$dictionary['Opportunity']['fields']['mixed_c']['len']='255';
$dictionary['Opportunity']['fields']['mixed_c']['required']=false;
$dictionary['Opportunity']['fields']['mixed_c']['type']='real';
$dictionary['Opportunity']['fields']['mixed_c']['audited']=0;
$dictionary['Opportunity']['fields']['mixed_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['mixed_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['mixed_c']['options']='';
$dictionary['Opportunity']['fields']['mixed_c']['help']='';
$dictionary['Opportunity']['fields']['mixed_c']['comments']='';
$dictionary['Opportunity']['fields']['mixed_c']['importable']='true';
$dictionary['Opportunity']['fields']['mixed_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['mixed_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['mixed_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['mixed_c']['reportable']=true;
$dictionary['Opportunity']['fields']['mixed_c']['ext2']='';
$dictionary['Opportunity']['fields']['mixed_c']['ext4']='';
$dictionary['Opportunity']['fields']['mixed_c']['ext3']='';
$dictionary['Opportunity']['fields']['mixed_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['mixed_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['mixed_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['mixed_c']['vname']='LBL_MIXED_C';
$dictionary['Opportunity']['fields']['mixed_c']['source']='custom_fields';

 ?>