<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['iswon']['name']='iswon';
$dictionary['Opportunity']['fields']['iswon']['default_value']='';
$dictionary['Opportunity']['fields']['iswon']['default']='';
$dictionary['Opportunity']['fields']['iswon']['display_default']='';
$dictionary['Opportunity']['fields']['iswon']['len']='255';
$dictionary['Opportunity']['fields']['iswon']['required']=false;
$dictionary['Opportunity']['fields']['iswon']['type']='bool';
$dictionary['Opportunity']['fields']['iswon']['audited']=0;
$dictionary['Opportunity']['fields']['iswon']['inline_edit']=1;
$dictionary['Opportunity']['fields']['iswon']['massupdate']=0;
$dictionary['Opportunity']['fields']['iswon']['options']='';
$dictionary['Opportunity']['fields']['iswon']['help']='';
$dictionary['Opportunity']['fields']['iswon']['comments']='';
$dictionary['Opportunity']['fields']['iswon']['importable']='true';
$dictionary['Opportunity']['fields']['iswon']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['iswon']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['iswon']['merge_filter']='';
$dictionary['Opportunity']['fields']['iswon']['reportable']=true;
$dictionary['Opportunity']['fields']['iswon']['ext2']='';
$dictionary['Opportunity']['fields']['iswon']['ext4']='';
$dictionary['Opportunity']['fields']['iswon']['ext3']='';
$dictionary['Opportunity']['fields']['iswon']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['iswon']['unified_search']=0;
$dictionary['Opportunity']['fields']['iswon']['full_text_search']='';
$dictionary['Opportunity']['fields']['iswon']['vname']='LBL_ISWON';
$dictionary['Opportunity']['fields']['iswon']['source']='custom_fields';

 ?>