<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['rr_c']['name']='rr_c';
$dictionary['Opportunity']['fields']['rr_c']['default_value']='';
$dictionary['Opportunity']['fields']['rr_c']['default']='';
$dictionary['Opportunity']['fields']['rr_c']['display_default']='';
$dictionary['Opportunity']['fields']['rr_c']['len']='255';
$dictionary['Opportunity']['fields']['rr_c']['required']=false;
$dictionary['Opportunity']['fields']['rr_c']['type']='real';
$dictionary['Opportunity']['fields']['rr_c']['audited']=0;
$dictionary['Opportunity']['fields']['rr_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['rr_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['rr_c']['options']='';
$dictionary['Opportunity']['fields']['rr_c']['help']='';
$dictionary['Opportunity']['fields']['rr_c']['comments']='';
$dictionary['Opportunity']['fields']['rr_c']['importable']='true';
$dictionary['Opportunity']['fields']['rr_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['rr_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['rr_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['rr_c']['reportable']=true;
$dictionary['Opportunity']['fields']['rr_c']['ext2']='';
$dictionary['Opportunity']['fields']['rr_c']['ext4']='';
$dictionary['Opportunity']['fields']['rr_c']['ext3']='';
$dictionary['Opportunity']['fields']['rr_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['rr_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['rr_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['rr_c']['vname']='LBL_RR_C';
$dictionary['Opportunity']['fields']['rr_c']['source']='custom_fields';

 ?>