<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['fiscalquarter']['name']='fiscalquarter';
$dictionary['Opportunity']['fields']['fiscalquarter']['default_value']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['default']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['display_default']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['len']='255';
$dictionary['Opportunity']['fields']['fiscalquarter']['required']=false;
$dictionary['Opportunity']['fields']['fiscalquarter']['type']='int';
$dictionary['Opportunity']['fields']['fiscalquarter']['audited']=0;
$dictionary['Opportunity']['fields']['fiscalquarter']['inline_edit']=1;
$dictionary['Opportunity']['fields']['fiscalquarter']['massupdate']=0;
$dictionary['Opportunity']['fields']['fiscalquarter']['options']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['help']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['comments']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['importable']='true';
$dictionary['Opportunity']['fields']['fiscalquarter']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['fiscalquarter']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['merge_filter']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['reportable']=true;
$dictionary['Opportunity']['fields']['fiscalquarter']['ext2']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['ext4']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['ext3']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['fiscalquarter']['unified_search']=0;
$dictionary['Opportunity']['fields']['fiscalquarter']['full_text_search']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['enable_range_search']='';
$dictionary['Opportunity']['fields']['fiscalquarter']['autoinc_next']=NULL;
$dictionary['Opportunity']['fields']['fiscalquarter']['autoinc_start']=NULL;
$dictionary['Opportunity']['fields']['fiscalquarter']['auto_increment']=NULL;
$dictionary['Opportunity']['fields']['fiscalquarter']['min']=NULL;
$dictionary['Opportunity']['fields']['fiscalquarter']['max']=NULL;
$dictionary['Opportunity']['fields']['fiscalquarter']['disable_num_format']=NULL;
$dictionary['Opportunity']['fields']['fiscalquarter']['vname']='LBL_FISCALQUARTER';
$dictionary['Opportunity']['fields']['fiscalquarter']['source']='custom_fields';

 ?>