<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['name']='exclusivity_formula_c';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['default_value']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['default']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['display_default']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['len']='255';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['required']=false;
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['type']='bool';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['audited']=0;
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['options']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['help']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['comments']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['importable']='true';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['reportable']=true;
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['ext2']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['ext4']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['ext3']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['vname']='LBL_EXCLUSIVITY_FORMULA_C';
$dictionary['Opportunity']['fields']['exclusivity_formula_c']['source']='custom_fields';

 ?>