<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['hit_s_member_c']['name']='hit_s_member_c';
$dictionary['Opportunity']['fields']['hit_s_member_c']['default_value']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['default']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['display_default']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['len']='50';
$dictionary['Opportunity']['fields']['hit_s_member_c']['required']=false;
$dictionary['Opportunity']['fields']['hit_s_member_c']['type']='varchar';
$dictionary['Opportunity']['fields']['hit_s_member_c']['audited']=0;
$dictionary['Opportunity']['fields']['hit_s_member_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['hit_s_member_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['hit_s_member_c']['options']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['help']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['comments']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['importable']='true';
$dictionary['Opportunity']['fields']['hit_s_member_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['hit_s_member_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['reportable']=true;
$dictionary['Opportunity']['fields']['hit_s_member_c']['ext2']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['ext4']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['ext3']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['hit_s_member_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['hit_s_member_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['hit_s_member_c']['vname']='LBL_HIT_S_MEMBER_C';
$dictionary['Opportunity']['fields']['hit_s_member_c']['source']='custom_fields';

 ?>