<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['product_interest_c']['name']='product_interest_c';
$dictionary['Opportunity']['fields']['product_interest_c']['default_value']='';
$dictionary['Opportunity']['fields']['product_interest_c']['default']='';
$dictionary['Opportunity']['fields']['product_interest_c']['display_default']='';
$dictionary['Opportunity']['fields']['product_interest_c']['len']='255';
$dictionary['Opportunity']['fields']['product_interest_c']['required']=false;
$dictionary['Opportunity']['fields']['product_interest_c']['type']='text';
$dictionary['Opportunity']['fields']['product_interest_c']['audited']=0;
$dictionary['Opportunity']['fields']['product_interest_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['product_interest_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['product_interest_c']['options']='';
$dictionary['Opportunity']['fields']['product_interest_c']['help']='';
$dictionary['Opportunity']['fields']['product_interest_c']['comments']='';
$dictionary['Opportunity']['fields']['product_interest_c']['importable']='true';
$dictionary['Opportunity']['fields']['product_interest_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['product_interest_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['product_interest_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['product_interest_c']['reportable']=true;
$dictionary['Opportunity']['fields']['product_interest_c']['ext2']='';
$dictionary['Opportunity']['fields']['product_interest_c']['ext4']='';
$dictionary['Opportunity']['fields']['product_interest_c']['ext3']='';
$dictionary['Opportunity']['fields']['product_interest_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['product_interest_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['product_interest_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['product_interest_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['product_interest_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['product_interest_c']['vname']='LBL_PRODUCT_INTEREST_C';
$dictionary['Opportunity']['fields']['product_interest_c']['source']='custom_fields';

 ?>