<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['primary_business_focus_c']['name']='primary_business_focus_c';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['default_value']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['default']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['display_default']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['len']='100';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['required']=false;
$dictionary['Opportunity']['fields']['primary_business_focus_c']['type']='varchar';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['audited']=0;
$dictionary['Opportunity']['fields']['primary_business_focus_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['primary_business_focus_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['primary_business_focus_c']['options']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['help']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['comments']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['importable']='true';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['primary_business_focus_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['reportable']=true;
$dictionary['Opportunity']['fields']['primary_business_focus_c']['ext2']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['ext4']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['ext3']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['primary_business_focus_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['primary_business_focus_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['vname']='LBL_PRIMARY_BUSINESS_FOCUS_C';
$dictionary['Opportunity']['fields']['primary_business_focus_c']['source']='custom_fields';

 ?>