<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['close_date_range_c']['name']='close_date_range_c';
$dictionary['Opportunity']['fields']['close_date_range_c']['default_value']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['default']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['display_default']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['len']='1300';
$dictionary['Opportunity']['fields']['close_date_range_c']['required']=false;
$dictionary['Opportunity']['fields']['close_date_range_c']['type']='text';
$dictionary['Opportunity']['fields']['close_date_range_c']['audited']=0;
$dictionary['Opportunity']['fields']['close_date_range_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['close_date_range_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['close_date_range_c']['options']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['help']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['comments']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['importable']='true';
$dictionary['Opportunity']['fields']['close_date_range_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['close_date_range_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['reportable']=true;
$dictionary['Opportunity']['fields']['close_date_range_c']['ext2']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['ext4']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['ext3']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['close_date_range_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['close_date_range_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['close_date_range_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['close_date_range_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['close_date_range_c']['vname']='LBL_CLOSE_DATE_RANGE_C';
$dictionary['Opportunity']['fields']['close_date_range_c']['source']='custom_fields';

 ?>