<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['quarter_now_c']['name']='quarter_now_c';
$dictionary['Opportunity']['fields']['quarter_now_c']['default_value']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['default']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['display_default']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['len']='255';
$dictionary['Opportunity']['fields']['quarter_now_c']['required']=false;
$dictionary['Opportunity']['fields']['quarter_now_c']['type']='timestamp';
$dictionary['Opportunity']['fields']['quarter_now_c']['audited']=0;
$dictionary['Opportunity']['fields']['quarter_now_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['quarter_now_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['quarter_now_c']['options']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['help']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['comments']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['importable']='true';
$dictionary['Opportunity']['fields']['quarter_now_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['quarter_now_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['reportable']=true;
$dictionary['Opportunity']['fields']['quarter_now_c']['ext2']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['ext4']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['ext3']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['quarter_now_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['quarter_now_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['quarter_now_c']['vname']='LBL_QUARTER_NOW_C';
$dictionary['Opportunity']['fields']['quarter_now_c']['source']='custom_fields';

 ?>