<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['age_sort_c']['name']='age_sort_c';
$dictionary['Opportunity']['fields']['age_sort_c']['default_value']='';
$dictionary['Opportunity']['fields']['age_sort_c']['default']='';
$dictionary['Opportunity']['fields']['age_sort_c']['display_default']='';
$dictionary['Opportunity']['fields']['age_sort_c']['len']='255';
$dictionary['Opportunity']['fields']['age_sort_c']['required']=false;
$dictionary['Opportunity']['fields']['age_sort_c']['type']='real';
$dictionary['Opportunity']['fields']['age_sort_c']['audited']=0;
$dictionary['Opportunity']['fields']['age_sort_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['age_sort_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['age_sort_c']['options']='';
$dictionary['Opportunity']['fields']['age_sort_c']['help']='';
$dictionary['Opportunity']['fields']['age_sort_c']['comments']='';
$dictionary['Opportunity']['fields']['age_sort_c']['importable']='true';
$dictionary['Opportunity']['fields']['age_sort_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['age_sort_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['age_sort_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['age_sort_c']['reportable']=true;
$dictionary['Opportunity']['fields']['age_sort_c']['ext2']='';
$dictionary['Opportunity']['fields']['age_sort_c']['ext4']='';
$dictionary['Opportunity']['fields']['age_sort_c']['ext3']='';
$dictionary['Opportunity']['fields']['age_sort_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['age_sort_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['age_sort_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['age_sort_c']['vname']='LBL_AGE_SORT_C';
$dictionary['Opportunity']['fields']['age_sort_c']['source']='custom_fields';

 ?>