<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['geostatus_c']['name']='geostatus_c';
$dictionary['Opportunity']['fields']['geostatus_c']['default_value']='';
$dictionary['Opportunity']['fields']['geostatus_c']['default']='';
$dictionary['Opportunity']['fields']['geostatus_c']['display_default']='';
$dictionary['Opportunity']['fields']['geostatus_c']['len']='255';
$dictionary['Opportunity']['fields']['geostatus_c']['required']=false;
$dictionary['Opportunity']['fields']['geostatus_c']['type']='text';
$dictionary['Opportunity']['fields']['geostatus_c']['audited']=0;
$dictionary['Opportunity']['fields']['geostatus_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['geostatus_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['geostatus_c']['options']='';
$dictionary['Opportunity']['fields']['geostatus_c']['help']='';
$dictionary['Opportunity']['fields']['geostatus_c']['comments']='';
$dictionary['Opportunity']['fields']['geostatus_c']['importable']='true';
$dictionary['Opportunity']['fields']['geostatus_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['geostatus_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['geostatus_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['geostatus_c']['reportable']=true;
$dictionary['Opportunity']['fields']['geostatus_c']['ext2']='';
$dictionary['Opportunity']['fields']['geostatus_c']['ext4']='';
$dictionary['Opportunity']['fields']['geostatus_c']['ext3']='';
$dictionary['Opportunity']['fields']['geostatus_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['geostatus_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['geostatus_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['geostatus_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['geostatus_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['geostatus_c']['vname']='LBL_GEOSTATUS_C';
$dictionary['Opportunity']['fields']['geostatus_c']['source']='custom_fields';

 ?>