<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['ig_number_c']['name']='ig_number_c';
$dictionary['Opportunity']['fields']['ig_number_c']['default_value']='';
$dictionary['Opportunity']['fields']['ig_number_c']['default']='';
$dictionary['Opportunity']['fields']['ig_number_c']['display_default']='';
$dictionary['Opportunity']['fields']['ig_number_c']['len']='255';
$dictionary['Opportunity']['fields']['ig_number_c']['required']=false;
$dictionary['Opportunity']['fields']['ig_number_c']['type']='text';
$dictionary['Opportunity']['fields']['ig_number_c']['audited']=0;
$dictionary['Opportunity']['fields']['ig_number_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['ig_number_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['ig_number_c']['options']='';
$dictionary['Opportunity']['fields']['ig_number_c']['help']='';
$dictionary['Opportunity']['fields']['ig_number_c']['comments']='';
$dictionary['Opportunity']['fields']['ig_number_c']['importable']='true';
$dictionary['Opportunity']['fields']['ig_number_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['ig_number_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['ig_number_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['ig_number_c']['reportable']=true;
$dictionary['Opportunity']['fields']['ig_number_c']['ext2']='';
$dictionary['Opportunity']['fields']['ig_number_c']['ext4']='';
$dictionary['Opportunity']['fields']['ig_number_c']['ext3']='';
$dictionary['Opportunity']['fields']['ig_number_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['ig_number_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['ig_number_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['ig_number_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['ig_number_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['ig_number_c']['vname']='LBL_IG_NUMBER_C';
$dictionary['Opportunity']['fields']['ig_number_c']['source']='custom_fields';

 ?>