<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['isclosed']['name']='isclosed';
$dictionary['Opportunity']['fields']['isclosed']['default_value']='';
$dictionary['Opportunity']['fields']['isclosed']['default']='';
$dictionary['Opportunity']['fields']['isclosed']['display_default']='';
$dictionary['Opportunity']['fields']['isclosed']['len']='255';
$dictionary['Opportunity']['fields']['isclosed']['required']=false;
$dictionary['Opportunity']['fields']['isclosed']['type']='bool';
$dictionary['Opportunity']['fields']['isclosed']['audited']=0;
$dictionary['Opportunity']['fields']['isclosed']['inline_edit']=1;
$dictionary['Opportunity']['fields']['isclosed']['massupdate']=0;
$dictionary['Opportunity']['fields']['isclosed']['options']='';
$dictionary['Opportunity']['fields']['isclosed']['help']='';
$dictionary['Opportunity']['fields']['isclosed']['comments']='';
$dictionary['Opportunity']['fields']['isclosed']['importable']='true';
$dictionary['Opportunity']['fields']['isclosed']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['isclosed']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['isclosed']['merge_filter']='';
$dictionary['Opportunity']['fields']['isclosed']['reportable']=true;
$dictionary['Opportunity']['fields']['isclosed']['ext2']='';
$dictionary['Opportunity']['fields']['isclosed']['ext4']='';
$dictionary['Opportunity']['fields']['isclosed']['ext3']='';
$dictionary['Opportunity']['fields']['isclosed']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['isclosed']['unified_search']=0;
$dictionary['Opportunity']['fields']['isclosed']['full_text_search']='';
$dictionary['Opportunity']['fields']['isclosed']['vname']='LBL_ISCLOSED';
$dictionary['Opportunity']['fields']['isclosed']['source']='custom_fields';

 ?>