<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['forecasted_c']['name']='forecasted_c';
$dictionary['Opportunity']['fields']['forecasted_c']['default_value']='';
$dictionary['Opportunity']['fields']['forecasted_c']['default']='';
$dictionary['Opportunity']['fields']['forecasted_c']['display_default']='';
$dictionary['Opportunity']['fields']['forecasted_c']['len']='1300';
$dictionary['Opportunity']['fields']['forecasted_c']['required']=false;
$dictionary['Opportunity']['fields']['forecasted_c']['type']='text';
$dictionary['Opportunity']['fields']['forecasted_c']['audited']=0;
$dictionary['Opportunity']['fields']['forecasted_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['forecasted_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['forecasted_c']['options']='';
$dictionary['Opportunity']['fields']['forecasted_c']['help']='';
$dictionary['Opportunity']['fields']['forecasted_c']['comments']='';
$dictionary['Opportunity']['fields']['forecasted_c']['importable']='true';
$dictionary['Opportunity']['fields']['forecasted_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['forecasted_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['forecasted_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['forecasted_c']['reportable']=true;
$dictionary['Opportunity']['fields']['forecasted_c']['ext2']='';
$dictionary['Opportunity']['fields']['forecasted_c']['ext4']='';
$dictionary['Opportunity']['fields']['forecasted_c']['ext3']='';
$dictionary['Opportunity']['fields']['forecasted_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['forecasted_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['forecasted_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['forecasted_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['forecasted_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['forecasted_c']['vname']='LBL_FORECASTED_C';
$dictionary['Opportunity']['fields']['forecasted_c']['source']='custom_fields';

 ?>