<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['quarterly_quota_c']['name']='quarterly_quota_c';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['default_value']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['default']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['display_default']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['len']='255';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['required']=false;
$dictionary['Opportunity']['fields']['quarterly_quota_c']['type']='real';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['audited']=0;
$dictionary['Opportunity']['fields']['quarterly_quota_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['quarterly_quota_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['quarterly_quota_c']['options']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['help']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['comments']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['importable']='true';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['quarterly_quota_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['reportable']=true;
$dictionary['Opportunity']['fields']['quarterly_quota_c']['ext2']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['ext4']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['ext3']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['quarterly_quota_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['quarterly_quota_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['vname']='LBL_QUARTERLY_QUOTA_C';
$dictionary['Opportunity']['fields']['quarterly_quota_c']['source']='custom_fields';

 ?>