<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['crm_c']['name']='crm_c';
$dictionary['Opportunity']['fields']['crm_c']['default_value']='';
$dictionary['Opportunity']['fields']['crm_c']['default']='';
$dictionary['Opportunity']['fields']['crm_c']['display_default']='';
$dictionary['Opportunity']['fields']['crm_c']['len']='60';
$dictionary['Opportunity']['fields']['crm_c']['required']=false;
$dictionary['Opportunity']['fields']['crm_c']['type']='varchar';
$dictionary['Opportunity']['fields']['crm_c']['audited']=0;
$dictionary['Opportunity']['fields']['crm_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['crm_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['crm_c']['options']='';
$dictionary['Opportunity']['fields']['crm_c']['help']='';
$dictionary['Opportunity']['fields']['crm_c']['comments']='';
$dictionary['Opportunity']['fields']['crm_c']['importable']='true';
$dictionary['Opportunity']['fields']['crm_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['crm_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['crm_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['crm_c']['reportable']=true;
$dictionary['Opportunity']['fields']['crm_c']['ext2']='';
$dictionary['Opportunity']['fields']['crm_c']['ext4']='';
$dictionary['Opportunity']['fields']['crm_c']['ext3']='';
$dictionary['Opportunity']['fields']['crm_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['crm_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['crm_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['crm_c']['vname']='LBL_CRM_C';
$dictionary['Opportunity']['fields']['crm_c']['source']='custom_fields';

 ?>