<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['a3_classification_c']['name']='a3_classification_c';
$dictionary['Opportunity']['fields']['a3_classification_c']['default_value']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['default']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['display_default']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['len']='255';
$dictionary['Opportunity']['fields']['a3_classification_c']['required']=false;
$dictionary['Opportunity']['fields']['a3_classification_c']['type']='text';
$dictionary['Opportunity']['fields']['a3_classification_c']['audited']=0;
$dictionary['Opportunity']['fields']['a3_classification_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['a3_classification_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['a3_classification_c']['options']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['help']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['comments']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['importable']='true';
$dictionary['Opportunity']['fields']['a3_classification_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['a3_classification_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['reportable']=true;
$dictionary['Opportunity']['fields']['a3_classification_c']['ext2']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['ext4']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['ext3']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['a3_classification_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['a3_classification_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['a3_classification_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['a3_classification_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['a3_classification_c']['vname']='LBL_A3_CLASSIFICATION_C';
$dictionary['Opportunity']['fields']['a3_classification_c']['source']='custom_fields';

 ?>