<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['lastactivitydate']['name']='lastactivitydate';
$dictionary['Opportunity']['fields']['lastactivitydate']['default_value']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['default']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['display_default']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['len']='255';
$dictionary['Opportunity']['fields']['lastactivitydate']['required']=false;
$dictionary['Opportunity']['fields']['lastactivitydate']['type']='timestamp';
$dictionary['Opportunity']['fields']['lastactivitydate']['audited']=0;
$dictionary['Opportunity']['fields']['lastactivitydate']['inline_edit']=1;
$dictionary['Opportunity']['fields']['lastactivitydate']['massupdate']=0;
$dictionary['Opportunity']['fields']['lastactivitydate']['options']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['help']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['comments']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['importable']='true';
$dictionary['Opportunity']['fields']['lastactivitydate']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['lastactivitydate']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['merge_filter']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['reportable']=true;
$dictionary['Opportunity']['fields']['lastactivitydate']['ext2']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['ext4']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['ext3']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['lastactivitydate']['unified_search']=0;
$dictionary['Opportunity']['fields']['lastactivitydate']['full_text_search']='';
$dictionary['Opportunity']['fields']['lastactivitydate']['vname']='LBL_LASTACTIVITYDATE';
$dictionary['Opportunity']['fields']['lastactivitydate']['source']='custom_fields';

 ?>