<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['name']='closed_won_qtd_c';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['default_value']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['default']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['display_default']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['len']='255';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['required']=false;
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['type']='real';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['audited']=0;
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['options']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['help']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['comments']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['importable']='true';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['reportable']=true;
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['ext2']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['ext4']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['ext3']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['vname']='LBL_CLOSED_WON_QTD_C';
$dictionary['Opportunity']['fields']['closed_won_qtd_c']['source']='custom_fields';

 ?>