<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['name']='sw_maint_renewal_term_c';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['default_value']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['default']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['display_default']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['len']='40';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['required']=false;
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['type']='varchar';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['audited']=0;
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['options']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['help']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['comments']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['importable']='true';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['reportable']=true;
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['ext2']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['ext4']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['ext3']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['vname']='LBL_SW_MAINT_RENEWAL_TERM_C';
$dictionary['Opportunity']['fields']['sw_maint_renewal_term_c']['source']='custom_fields';

 ?>