<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['forecast_c']['name']='forecast_c';
$dictionary['Opportunity']['fields']['forecast_c']['default_value']='';
$dictionary['Opportunity']['fields']['forecast_c']['default']='';
$dictionary['Opportunity']['fields']['forecast_c']['display_default']='';
$dictionary['Opportunity']['fields']['forecast_c']['len']='255';
$dictionary['Opportunity']['fields']['forecast_c']['required']=false;
$dictionary['Opportunity']['fields']['forecast_c']['type']='bool';
$dictionary['Opportunity']['fields']['forecast_c']['audited']=0;
$dictionary['Opportunity']['fields']['forecast_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['forecast_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['forecast_c']['options']='';
$dictionary['Opportunity']['fields']['forecast_c']['help']='';
$dictionary['Opportunity']['fields']['forecast_c']['comments']='';
$dictionary['Opportunity']['fields']['forecast_c']['importable']='true';
$dictionary['Opportunity']['fields']['forecast_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['forecast_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['forecast_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['forecast_c']['reportable']=true;
$dictionary['Opportunity']['fields']['forecast_c']['ext2']='';
$dictionary['Opportunity']['fields']['forecast_c']['ext4']='';
$dictionary['Opportunity']['fields']['forecast_c']['ext3']='';
$dictionary['Opportunity']['fields']['forecast_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['forecast_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['forecast_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['forecast_c']['vname']='LBL_FORECAST_C';
$dictionary['Opportunity']['fields']['forecast_c']['source']='custom_fields';

 ?>