<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['ilp_c']['name']='ilp_c';
$dictionary['Opportunity']['fields']['ilp_c']['default_value']='';
$dictionary['Opportunity']['fields']['ilp_c']['default']='';
$dictionary['Opportunity']['fields']['ilp_c']['display_default']='';
$dictionary['Opportunity']['fields']['ilp_c']['len']='1300';
$dictionary['Opportunity']['fields']['ilp_c']['required']=false;
$dictionary['Opportunity']['fields']['ilp_c']['type']='text';
$dictionary['Opportunity']['fields']['ilp_c']['audited']=0;
$dictionary['Opportunity']['fields']['ilp_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['ilp_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['ilp_c']['options']='';
$dictionary['Opportunity']['fields']['ilp_c']['help']='';
$dictionary['Opportunity']['fields']['ilp_c']['comments']='';
$dictionary['Opportunity']['fields']['ilp_c']['importable']='true';
$dictionary['Opportunity']['fields']['ilp_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['ilp_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['ilp_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['ilp_c']['reportable']=true;
$dictionary['Opportunity']['fields']['ilp_c']['ext2']='';
$dictionary['Opportunity']['fields']['ilp_c']['ext4']='';
$dictionary['Opportunity']['fields']['ilp_c']['ext3']='';
$dictionary['Opportunity']['fields']['ilp_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['ilp_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['ilp_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['ilp_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['ilp_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['ilp_c']['vname']='LBL_ILP_C';
$dictionary['Opportunity']['fields']['ilp_c']['source']='custom_fields';

 ?>