<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['winloss_description_c']['name']='winloss_description_c';
$dictionary['Opportunity']['fields']['winloss_description_c']['default_value']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['default']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['display_default']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['len']='255';
$dictionary['Opportunity']['fields']['winloss_description_c']['required']=false;
$dictionary['Opportunity']['fields']['winloss_description_c']['type']='text';
$dictionary['Opportunity']['fields']['winloss_description_c']['audited']=0;
$dictionary['Opportunity']['fields']['winloss_description_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['winloss_description_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['winloss_description_c']['options']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['help']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['comments']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['importable']='true';
$dictionary['Opportunity']['fields']['winloss_description_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['winloss_description_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['reportable']=true;
$dictionary['Opportunity']['fields']['winloss_description_c']['ext2']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['ext4']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['ext3']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['winloss_description_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['winloss_description_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['winloss_description_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['winloss_description_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['winloss_description_c']['vname']='LBL_WINLOSS_DESCRIPTION_C';
$dictionary['Opportunity']['fields']['winloss_description_c']['source']='custom_fields';

 ?>