<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['interface_vendor_c']['name']='interface_vendor_c';
$dictionary['Opportunity']['fields']['interface_vendor_c']['default_value']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['default']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['display_default']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['len']='25';
$dictionary['Opportunity']['fields']['interface_vendor_c']['required']=false;
$dictionary['Opportunity']['fields']['interface_vendor_c']['type']='varchar';
$dictionary['Opportunity']['fields']['interface_vendor_c']['audited']=0;
$dictionary['Opportunity']['fields']['interface_vendor_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['interface_vendor_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['interface_vendor_c']['options']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['help']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['comments']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['importable']='true';
$dictionary['Opportunity']['fields']['interface_vendor_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['interface_vendor_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['reportable']=true;
$dictionary['Opportunity']['fields']['interface_vendor_c']['ext2']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['ext4']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['ext3']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['interface_vendor_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['interface_vendor_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['interface_vendor_c']['vname']='LBL_INTERFACE_VENDOR_C';
$dictionary['Opportunity']['fields']['interface_vendor_c']['source']='custom_fields';

 ?>