<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['gpo_c']['name']='gpo_c';
$dictionary['Opportunity']['fields']['gpo_c']['default_value']='';
$dictionary['Opportunity']['fields']['gpo_c']['default']='';
$dictionary['Opportunity']['fields']['gpo_c']['display_default']='';
$dictionary['Opportunity']['fields']['gpo_c']['len']='18';
$dictionary['Opportunity']['fields']['gpo_c']['required']=false;
$dictionary['Opportunity']['fields']['gpo_c']['type']='varchar';
$dictionary['Opportunity']['fields']['gpo_c']['audited']=0;
$dictionary['Opportunity']['fields']['gpo_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['gpo_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['gpo_c']['options']='';
$dictionary['Opportunity']['fields']['gpo_c']['help']='';
$dictionary['Opportunity']['fields']['gpo_c']['comments']='';
$dictionary['Opportunity']['fields']['gpo_c']['importable']='true';
$dictionary['Opportunity']['fields']['gpo_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['gpo_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['gpo_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['gpo_c']['reportable']=true;
$dictionary['Opportunity']['fields']['gpo_c']['ext2']='';
$dictionary['Opportunity']['fields']['gpo_c']['ext4']='';
$dictionary['Opportunity']['fields']['gpo_c']['ext3']='';
$dictionary['Opportunity']['fields']['gpo_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['gpo_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['gpo_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['gpo_c']['vname']='LBL_GPO_C';
$dictionary['Opportunity']['fields']['gpo_c']['source']='custom_fields';

 ?>