<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['fc_c']['name']='fc_c';
$dictionary['Opportunity']['fields']['fc_c']['default_value']='';
$dictionary['Opportunity']['fields']['fc_c']['default']='';
$dictionary['Opportunity']['fields']['fc_c']['display_default']='';
$dictionary['Opportunity']['fields']['fc_c']['len']='1300';
$dictionary['Opportunity']['fields']['fc_c']['required']=false;
$dictionary['Opportunity']['fields']['fc_c']['type']='text';
$dictionary['Opportunity']['fields']['fc_c']['audited']=0;
$dictionary['Opportunity']['fields']['fc_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['fc_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['fc_c']['options']='';
$dictionary['Opportunity']['fields']['fc_c']['help']='';
$dictionary['Opportunity']['fields']['fc_c']['comments']='';
$dictionary['Opportunity']['fields']['fc_c']['importable']='true';
$dictionary['Opportunity']['fields']['fc_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['fc_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['fc_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['fc_c']['reportable']=true;
$dictionary['Opportunity']['fields']['fc_c']['ext2']='';
$dictionary['Opportunity']['fields']['fc_c']['ext4']='';
$dictionary['Opportunity']['fields']['fc_c']['ext3']='';
$dictionary['Opportunity']['fields']['fc_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['fc_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['fc_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['fc_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['fc_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['fc_c']['vname']='LBL_FC_C';
$dictionary['Opportunity']['fields']['fc_c']['source']='custom_fields';

 ?>