<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['name']='after_dom_edit_lr_c';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['default_value']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['default']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['display_default']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['len']='255';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['required']=false;
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['type']='real';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['audited']=0;
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['options']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['help']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['comments']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['importable']='true';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['reportable']=true;
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['ext2']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['ext4']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['ext3']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['vname']='LBL_AFTER_DOM_EDIT_LR_C';
$dictionary['Opportunity']['fields']['after_dom_edit_lr_c']['source']='custom_fields';

 ?>