<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['name']='vendor_of_choice_c';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['default_value']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['default']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['display_default']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['len']='255';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['required']=false;
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['type']='bool';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['audited']=0;
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['options']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['help']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['comments']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['importable']='true';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['reportable']=true;
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['ext2']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['ext4']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['ext3']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['vname']='LBL_VENDOR_OF_CHOICE_C';
$dictionary['Opportunity']['fields']['vendor_of_choice_c']['source']='custom_fields';

 ?>