<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['backup_c']['name']='backup_c';
$dictionary['Opportunity']['fields']['backup_c']['default_value']='';
$dictionary['Opportunity']['fields']['backup_c']['default']='';
$dictionary['Opportunity']['fields']['backup_c']['display_default']='';
$dictionary['Opportunity']['fields']['backup_c']['len']='255';
$dictionary['Opportunity']['fields']['backup_c']['required']=false;
$dictionary['Opportunity']['fields']['backup_c']['type']='real';
$dictionary['Opportunity']['fields']['backup_c']['audited']=0;
$dictionary['Opportunity']['fields']['backup_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['backup_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['backup_c']['options']='';
$dictionary['Opportunity']['fields']['backup_c']['help']='';
$dictionary['Opportunity']['fields']['backup_c']['comments']='';
$dictionary['Opportunity']['fields']['backup_c']['importable']='true';
$dictionary['Opportunity']['fields']['backup_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['backup_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['backup_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['backup_c']['reportable']=true;
$dictionary['Opportunity']['fields']['backup_c']['ext2']='';
$dictionary['Opportunity']['fields']['backup_c']['ext4']='';
$dictionary['Opportunity']['fields']['backup_c']['ext3']='';
$dictionary['Opportunity']['fields']['backup_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['backup_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['backup_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['backup_c']['vname']='LBL_BACKUP_C';
$dictionary['Opportunity']['fields']['backup_c']['source']='custom_fields';

 ?>