<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['name']='co_implementation_training_pro_serv_c';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['default_value']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['default']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['display_default']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['len']='255';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['required']=false;
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['type']='real';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['audited']=0;
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['options']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['help']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['comments']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['importable']='true';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['reportable']=true;
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['ext2']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['ext4']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['ext3']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['vname']='LBL_CO_IMPLEMENTATION_TRAINING_PRO_SERV_C';
$dictionary['Opportunity']['fields']['co_implementation_training_pro_serv_c']['source']='custom_fields';

 ?>