<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['close_date_change_c']['name']='close_date_change_c';
$dictionary['Opportunity']['fields']['close_date_change_c']['default_value']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['default']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['display_default']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['len']='255';
$dictionary['Opportunity']['fields']['close_date_change_c']['required']=false;
$dictionary['Opportunity']['fields']['close_date_change_c']['type']='real';
$dictionary['Opportunity']['fields']['close_date_change_c']['audited']=0;
$dictionary['Opportunity']['fields']['close_date_change_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['close_date_change_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['close_date_change_c']['options']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['help']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['comments']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['importable']='true';
$dictionary['Opportunity']['fields']['close_date_change_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['close_date_change_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['reportable']=true;
$dictionary['Opportunity']['fields']['close_date_change_c']['ext2']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['ext4']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['ext3']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['close_date_change_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['close_date_change_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['close_date_change_c']['vname']='LBL_CLOSE_DATE_CHANGE_C';
$dictionary['Opportunity']['fields']['close_date_change_c']['source']='custom_fields';

 ?>