<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['hardwareimponly_c']['name']='hardwareimponly_c';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['default_value']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['default']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['display_default']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['len']='255';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['required']=false;
$dictionary['Opportunity']['fields']['hardwareimponly_c']['type']='bool';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['audited']=0;
$dictionary['Opportunity']['fields']['hardwareimponly_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['hardwareimponly_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['hardwareimponly_c']['options']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['help']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['comments']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['importable']='true';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['hardwareimponly_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['reportable']=true;
$dictionary['Opportunity']['fields']['hardwareimponly_c']['ext2']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['ext4']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['ext3']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['hardwareimponly_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['hardwareimponly_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['vname']='LBL_HARDWAREIMPONLY_C';
$dictionary['Opportunity']['fields']['hardwareimponly_c']['source']='custom_fields';

 ?>