<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['name']='new_cost_component_sum_c';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['default_value']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['default']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['display_default']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['len']='255';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['required']=false;
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['type']='real';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['audited']=0;
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['options']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['help']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['comments']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['importable']='true';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['reportable']=true;
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['ext2']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['ext4']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['ext3']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['vname']='LBL_NEW_COST_COMPONENT_SUM_C';
$dictionary['Opportunity']['fields']['new_cost_component_sum_c']['source']='custom_fields';

 ?>