<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['business_type_c']['name']='business_type_c';
$dictionary['Opportunity']['fields']['business_type_c']['default_value']='';
$dictionary['Opportunity']['fields']['business_type_c']['default']='';
$dictionary['Opportunity']['fields']['business_type_c']['display_default']='';
$dictionary['Opportunity']['fields']['business_type_c']['len']='4099';
$dictionary['Opportunity']['fields']['business_type_c']['required']=false;
$dictionary['Opportunity']['fields']['business_type_c']['type']='text';
$dictionary['Opportunity']['fields']['business_type_c']['audited']=0;
$dictionary['Opportunity']['fields']['business_type_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['business_type_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['business_type_c']['options']='';
$dictionary['Opportunity']['fields']['business_type_c']['help']='';
$dictionary['Opportunity']['fields']['business_type_c']['comments']='';
$dictionary['Opportunity']['fields']['business_type_c']['importable']='true';
$dictionary['Opportunity']['fields']['business_type_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['business_type_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['business_type_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['business_type_c']['reportable']=true;
$dictionary['Opportunity']['fields']['business_type_c']['ext2']='';
$dictionary['Opportunity']['fields']['business_type_c']['ext4']='';
$dictionary['Opportunity']['fields']['business_type_c']['ext3']='';
$dictionary['Opportunity']['fields']['business_type_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['business_type_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['business_type_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['business_type_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['business_type_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['business_type_c']['vname']='LBL_BUSINESS_TYPE_C';
$dictionary['Opportunity']['fields']['business_type_c']['source']='custom_fields';

 ?>