<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['type_of_interface_c']['name']='type_of_interface_c';
$dictionary['Opportunity']['fields']['type_of_interface_c']['default_value']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['default']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['display_default']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['len']='25';
$dictionary['Opportunity']['fields']['type_of_interface_c']['required']=false;
$dictionary['Opportunity']['fields']['type_of_interface_c']['type']='varchar';
$dictionary['Opportunity']['fields']['type_of_interface_c']['audited']=0;
$dictionary['Opportunity']['fields']['type_of_interface_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['type_of_interface_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['type_of_interface_c']['options']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['help']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['comments']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['importable']='true';
$dictionary['Opportunity']['fields']['type_of_interface_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['type_of_interface_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['reportable']=true;
$dictionary['Opportunity']['fields']['type_of_interface_c']['ext2']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['ext4']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['ext3']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['type_of_interface_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['type_of_interface_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['type_of_interface_c']['vname']='LBL_TYPE_OF_INTERFACE_C';
$dictionary['Opportunity']['fields']['type_of_interface_c']['source']='custom_fields';

 ?>