<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['close_date_copy_c']['name']='close_date_copy_c';
$dictionary['Opportunity']['fields']['close_date_copy_c']['default_value']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['default']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['display_default']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['len']='255';
$dictionary['Opportunity']['fields']['close_date_copy_c']['required']=false;
$dictionary['Opportunity']['fields']['close_date_copy_c']['type']='timestamp';
$dictionary['Opportunity']['fields']['close_date_copy_c']['audited']=0;
$dictionary['Opportunity']['fields']['close_date_copy_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['close_date_copy_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['close_date_copy_c']['options']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['help']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['comments']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['importable']='true';
$dictionary['Opportunity']['fields']['close_date_copy_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['close_date_copy_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['reportable']=true;
$dictionary['Opportunity']['fields']['close_date_copy_c']['ext2']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['ext4']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['ext3']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['close_date_copy_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['close_date_copy_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['close_date_copy_c']['vname']='LBL_CLOSE_DATE_COPY_C';
$dictionary['Opportunity']['fields']['close_date_copy_c']['source']='custom_fields';

 ?>