<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['gp_contract_order_c']['name']='gp_contract_order_c';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['default_value']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['default']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['display_default']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['len']='75';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['required']=false;
$dictionary['Opportunity']['fields']['gp_contract_order_c']['type']='varchar';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['audited']=0;
$dictionary['Opportunity']['fields']['gp_contract_order_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['gp_contract_order_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['gp_contract_order_c']['options']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['help']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['comments']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['importable']='true';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['gp_contract_order_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['reportable']=true;
$dictionary['Opportunity']['fields']['gp_contract_order_c']['ext2']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['ext4']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['ext3']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['gp_contract_order_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['gp_contract_order_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['vname']='LBL_GP_CONTRACT_ORDER_C';
$dictionary['Opportunity']['fields']['gp_contract_order_c']['source']='custom_fields';

 ?>