<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['rolling_months_c']['name']='rolling_months_c';
$dictionary['Opportunity']['fields']['rolling_months_c']['default_value']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['default']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['display_default']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['len']='255';
$dictionary['Opportunity']['fields']['rolling_months_c']['required']=false;
$dictionary['Opportunity']['fields']['rolling_months_c']['type']='real';
$dictionary['Opportunity']['fields']['rolling_months_c']['audited']=0;
$dictionary['Opportunity']['fields']['rolling_months_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['rolling_months_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['rolling_months_c']['options']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['help']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['comments']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['importable']='true';
$dictionary['Opportunity']['fields']['rolling_months_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['rolling_months_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['reportable']=true;
$dictionary['Opportunity']['fields']['rolling_months_c']['ext2']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['ext4']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['ext3']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['rolling_months_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['rolling_months_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['rolling_months_c']['vname']='LBL_ROLLING_MONTHS_C';
$dictionary['Opportunity']['fields']['rolling_months_c']['source']='custom_fields';

 ?>