<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['name']='imaging_collaboration_eligible_c';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['default_value']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['default']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['display_default']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['len']='255';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['required']=false;
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['type']='bool';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['audited']=0;
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['options']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['help']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['comments']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['importable']='true';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['reportable']=true;
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['ext2']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['ext4']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['ext3']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['vname']='LBL_IMAGING_COLLABORATION_ELIGIBLE_C';
$dictionary['Opportunity']['fields']['imaging_collaboration_eligible_c']['source']='custom_fields';

 ?>