<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['ae2_perc_c']['name']='ae2_perc_c';
$dictionary['Opportunity']['fields']['ae2_perc_c']['default_value']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['default']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['display_default']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['len']='255';
$dictionary['Opportunity']['fields']['ae2_perc_c']['required']=false;
$dictionary['Opportunity']['fields']['ae2_perc_c']['type']='real';
$dictionary['Opportunity']['fields']['ae2_perc_c']['audited']=0;
$dictionary['Opportunity']['fields']['ae2_perc_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['ae2_perc_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['ae2_perc_c']['options']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['help']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['comments']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['importable']='true';
$dictionary['Opportunity']['fields']['ae2_perc_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['ae2_perc_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['reportable']=true;
$dictionary['Opportunity']['fields']['ae2_perc_c']['ext2']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['ext4']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['ext3']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['ae2_perc_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['ae2_perc_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['ae2_perc_c']['vname']='LBL_AE2_PERC_C';
$dictionary['Opportunity']['fields']['ae2_perc_c']['source']='custom_fields';

 ?>