<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['reseller_c']['name']='reseller_c';
$dictionary['Opportunity']['fields']['reseller_c']['default_value']='';
$dictionary['Opportunity']['fields']['reseller_c']['default']='';
$dictionary['Opportunity']['fields']['reseller_c']['display_default']='';
$dictionary['Opportunity']['fields']['reseller_c']['len']='255';
$dictionary['Opportunity']['fields']['reseller_c']['required']=false;
$dictionary['Opportunity']['fields']['reseller_c']['type']='bool';
$dictionary['Opportunity']['fields']['reseller_c']['audited']=0;
$dictionary['Opportunity']['fields']['reseller_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['reseller_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['reseller_c']['options']='';
$dictionary['Opportunity']['fields']['reseller_c']['help']='';
$dictionary['Opportunity']['fields']['reseller_c']['comments']='';
$dictionary['Opportunity']['fields']['reseller_c']['importable']='true';
$dictionary['Opportunity']['fields']['reseller_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['reseller_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['reseller_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['reseller_c']['reportable']=true;
$dictionary['Opportunity']['fields']['reseller_c']['ext2']='';
$dictionary['Opportunity']['fields']['reseller_c']['ext4']='';
$dictionary['Opportunity']['fields']['reseller_c']['ext3']='';
$dictionary['Opportunity']['fields']['reseller_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['reseller_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['reseller_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['reseller_c']['vname']='LBL_RESELLER_C';
$dictionary['Opportunity']['fields']['reseller_c']['source']='custom_fields';

 ?>