<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['notifi_c']['name']='notifi_c';
$dictionary['Opportunity']['fields']['notifi_c']['default_value']='';
$dictionary['Opportunity']['fields']['notifi_c']['default']='';
$dictionary['Opportunity']['fields']['notifi_c']['display_default']='';
$dictionary['Opportunity']['fields']['notifi_c']['len']='255';
$dictionary['Opportunity']['fields']['notifi_c']['required']=false;
$dictionary['Opportunity']['fields']['notifi_c']['type']='bool';
$dictionary['Opportunity']['fields']['notifi_c']['audited']=0;
$dictionary['Opportunity']['fields']['notifi_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['notifi_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['notifi_c']['options']='';
$dictionary['Opportunity']['fields']['notifi_c']['help']='';
$dictionary['Opportunity']['fields']['notifi_c']['comments']='';
$dictionary['Opportunity']['fields']['notifi_c']['importable']='true';
$dictionary['Opportunity']['fields']['notifi_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['notifi_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['notifi_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['notifi_c']['reportable']=true;
$dictionary['Opportunity']['fields']['notifi_c']['ext2']='';
$dictionary['Opportunity']['fields']['notifi_c']['ext4']='';
$dictionary['Opportunity']['fields']['notifi_c']['ext3']='';
$dictionary['Opportunity']['fields']['notifi_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['notifi_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['notifi_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['notifi_c']['vname']='LBL_NOTIFI_C';
$dictionary['Opportunity']['fields']['notifi_c']['source']='custom_fields';

 ?>