<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['rfp_required_c']['name']='rfp_required_c';
$dictionary['Opportunity']['fields']['rfp_required_c']['default_value']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['default']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['display_default']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['len']='255';
$dictionary['Opportunity']['fields']['rfp_required_c']['required']=false;
$dictionary['Opportunity']['fields']['rfp_required_c']['type']='bool';
$dictionary['Opportunity']['fields']['rfp_required_c']['audited']=0;
$dictionary['Opportunity']['fields']['rfp_required_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['rfp_required_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['rfp_required_c']['options']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['help']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['comments']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['importable']='true';
$dictionary['Opportunity']['fields']['rfp_required_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['rfp_required_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['reportable']=true;
$dictionary['Opportunity']['fields']['rfp_required_c']['ext2']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['ext4']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['ext3']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['rfp_required_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['rfp_required_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['rfp_required_c']['vname']='LBL_RFP_REQUIRED_C';
$dictionary['Opportunity']['fields']['rfp_required_c']['source']='custom_fields';

 ?>