<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['name']='non_standard_commissions_release_c';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['default_value']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['default']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['display_default']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['len']='255';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['required']=false;
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['type']='bool';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['audited']=0;
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['options']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['help']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['comments']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['importable']='true';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['reportable']=true;
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['ext2']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['ext4']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['ext3']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['vname']='LBL_NON_STANDARD_COMMISSIONS_RELEASE_C';
$dictionary['Opportunity']['fields']['non_standard_commissions_release_c']['source']='custom_fields';

 ?>