<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['name']='number_of_healthcare_partners_c';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['default_value']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['default']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['display_default']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['len']='30';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['required']=false;
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['type']='varchar';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['audited']=0;
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['options']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['help']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['comments']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['importable']='true';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['reportable']=true;
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['ext2']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['ext4']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['ext3']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['vname']='LBL_NUMBER_OF_HEALTHCARE_PARTNERS_C';
$dictionary['Opportunity']['fields']['number_of_healthcare_partners_c']['source']='custom_fields';

 ?>