<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['name']='eb_tos_adjustment_c';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['default_value']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['default']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['display_default']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['len']='255';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['required']=false;
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['type']='real';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['audited']=0;
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['options']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['help']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['comments']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['importable']='true';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['reportable']=true;
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['ext2']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['ext4']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['ext3']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['vname']='LBL_EB_TOS_ADJUSTMENT_C';
$dictionary['Opportunity']['fields']['eb_tos_adjustment_c']['source']='custom_fields';

 ?>