<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['fiscal']['name']='fiscal';
$dictionary['Opportunity']['fields']['fiscal']['default_value']='';
$dictionary['Opportunity']['fields']['fiscal']['default']='';
$dictionary['Opportunity']['fields']['fiscal']['display_default']='';
$dictionary['Opportunity']['fields']['fiscal']['len']='6';
$dictionary['Opportunity']['fields']['fiscal']['required']=false;
$dictionary['Opportunity']['fields']['fiscal']['type']='varchar';
$dictionary['Opportunity']['fields']['fiscal']['audited']=0;
$dictionary['Opportunity']['fields']['fiscal']['inline_edit']=1;
$dictionary['Opportunity']['fields']['fiscal']['massupdate']=0;
$dictionary['Opportunity']['fields']['fiscal']['options']='';
$dictionary['Opportunity']['fields']['fiscal']['help']='';
$dictionary['Opportunity']['fields']['fiscal']['comments']='';
$dictionary['Opportunity']['fields']['fiscal']['importable']='true';
$dictionary['Opportunity']['fields']['fiscal']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['fiscal']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['fiscal']['merge_filter']='';
$dictionary['Opportunity']['fields']['fiscal']['reportable']=true;
$dictionary['Opportunity']['fields']['fiscal']['ext2']='';
$dictionary['Opportunity']['fields']['fiscal']['ext4']='';
$dictionary['Opportunity']['fields']['fiscal']['ext3']='';
$dictionary['Opportunity']['fields']['fiscal']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['fiscal']['unified_search']=0;
$dictionary['Opportunity']['fields']['fiscal']['full_text_search']='';
$dictionary['Opportunity']['fields']['fiscal']['vname']='LBL_FISCAL';
$dictionary['Opportunity']['fields']['fiscal']['source']='custom_fields';

 ?>