<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['co_speech_mics_c']['name']='co_speech_mics_c';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['default_value']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['default']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['display_default']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['len']='255';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['required']=false;
$dictionary['Opportunity']['fields']['co_speech_mics_c']['type']='real';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['audited']=0;
$dictionary['Opportunity']['fields']['co_speech_mics_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['co_speech_mics_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['co_speech_mics_c']['options']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['help']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['comments']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['importable']='true';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['co_speech_mics_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['reportable']=true;
$dictionary['Opportunity']['fields']['co_speech_mics_c']['ext2']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['ext4']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['ext3']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['co_speech_mics_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['co_speech_mics_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['vname']='LBL_CO_SPEECH_MICS_C';
$dictionary['Opportunity']['fields']['co_speech_mics_c']['source']='custom_fields';

 ?>