<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['time_to_close_c']['name']='time_to_close_c';
$dictionary['Opportunity']['fields']['time_to_close_c']['default_value']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['default']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['display_default']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['len']='255';
$dictionary['Opportunity']['fields']['time_to_close_c']['required']=false;
$dictionary['Opportunity']['fields']['time_to_close_c']['type']='real';
$dictionary['Opportunity']['fields']['time_to_close_c']['audited']=0;
$dictionary['Opportunity']['fields']['time_to_close_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['time_to_close_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['time_to_close_c']['options']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['help']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['comments']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['importable']='true';
$dictionary['Opportunity']['fields']['time_to_close_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['time_to_close_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['reportable']=true;
$dictionary['Opportunity']['fields']['time_to_close_c']['ext2']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['ext4']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['ext3']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['time_to_close_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['time_to_close_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['time_to_close_c']['vname']='LBL_TIME_TO_CLOSE_C';
$dictionary['Opportunity']['fields']['time_to_close_c']['source']='custom_fields';

 ?>