<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['lessons_learned_c']['name']='lessons_learned_c';
$dictionary['Opportunity']['fields']['lessons_learned_c']['default_value']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['default']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['display_default']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['len']='100';
$dictionary['Opportunity']['fields']['lessons_learned_c']['required']=false;
$dictionary['Opportunity']['fields']['lessons_learned_c']['type']='varchar';
$dictionary['Opportunity']['fields']['lessons_learned_c']['audited']=0;
$dictionary['Opportunity']['fields']['lessons_learned_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['lessons_learned_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['lessons_learned_c']['options']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['help']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['comments']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['importable']='true';
$dictionary['Opportunity']['fields']['lessons_learned_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['lessons_learned_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['reportable']=true;
$dictionary['Opportunity']['fields']['lessons_learned_c']['ext2']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['ext4']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['ext3']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['lessons_learned_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['lessons_learned_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['lessons_learned_c']['vname']='LBL_LESSONS_LEARNED_C';
$dictionary['Opportunity']['fields']['lessons_learned_c']['source']='custom_fields';

 ?>