<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['statdx_c']['name']='statdx_c';
$dictionary['Opportunity']['fields']['statdx_c']['default_value']='';
$dictionary['Opportunity']['fields']['statdx_c']['default']='';
$dictionary['Opportunity']['fields']['statdx_c']['display_default']='';
$dictionary['Opportunity']['fields']['statdx_c']['len']='255';
$dictionary['Opportunity']['fields']['statdx_c']['required']=false;
$dictionary['Opportunity']['fields']['statdx_c']['type']='bool';
$dictionary['Opportunity']['fields']['statdx_c']['audited']=0;
$dictionary['Opportunity']['fields']['statdx_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['statdx_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['statdx_c']['options']='';
$dictionary['Opportunity']['fields']['statdx_c']['help']='';
$dictionary['Opportunity']['fields']['statdx_c']['comments']='';
$dictionary['Opportunity']['fields']['statdx_c']['importable']='true';
$dictionary['Opportunity']['fields']['statdx_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['statdx_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['statdx_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['statdx_c']['reportable']=true;
$dictionary['Opportunity']['fields']['statdx_c']['ext2']='';
$dictionary['Opportunity']['fields']['statdx_c']['ext4']='';
$dictionary['Opportunity']['fields']['statdx_c']['ext3']='';
$dictionary['Opportunity']['fields']['statdx_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['statdx_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['statdx_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['statdx_c']['vname']='LBL_STATDX_C';
$dictionary['Opportunity']['fields']['statdx_c']['source']='custom_fields';

 ?>