<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['name']='sage_opportunity_id_c';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['default_value']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['default']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['display_default']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['len']='30';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['required']=false;
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['type']='varchar';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['audited']=0;
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['options']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['help']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['comments']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['importable']='true';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['reportable']=true;
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['ext2']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['ext4']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['ext3']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['vname']='LBL_SAGE_OPPORTUNITY_ID_C';
$dictionary['Opportunity']['fields']['sage_opportunity_id_c']['source']='custom_fields';

 ?>