<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['name']='in_rolling_4qs_c';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['default_value']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['default']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['display_default']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['len']='255';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['required']=false;
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['type']='bool';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['audited']=0;
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['options']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['help']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['comments']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['importable']='true';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['reportable']=true;
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['ext2']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['ext4']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['ext3']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['vname']='LBL_IN_ROLLING_4QS_C';
$dictionary['Opportunity']['fields']['in_rolling_4qs_c']['source']='custom_fields';

 ?>