<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['winner_c']['name']='winner_c';
$dictionary['Opportunity']['fields']['winner_c']['default_value']='';
$dictionary['Opportunity']['fields']['winner_c']['default']='';
$dictionary['Opportunity']['fields']['winner_c']['display_default']='';
$dictionary['Opportunity']['fields']['winner_c']['len']='18';
$dictionary['Opportunity']['fields']['winner_c']['required']=false;
$dictionary['Opportunity']['fields']['winner_c']['type']='varchar';
$dictionary['Opportunity']['fields']['winner_c']['audited']=0;
$dictionary['Opportunity']['fields']['winner_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['winner_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['winner_c']['options']='';
$dictionary['Opportunity']['fields']['winner_c']['help']='';
$dictionary['Opportunity']['fields']['winner_c']['comments']='';
$dictionary['Opportunity']['fields']['winner_c']['importable']='true';
$dictionary['Opportunity']['fields']['winner_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['winner_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['winner_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['winner_c']['reportable']=true;
$dictionary['Opportunity']['fields']['winner_c']['ext2']='';
$dictionary['Opportunity']['fields']['winner_c']['ext4']='';
$dictionary['Opportunity']['fields']['winner_c']['ext3']='';
$dictionary['Opportunity']['fields']['winner_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['winner_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['winner_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['winner_c']['vname']='LBL_WINNER_C';
$dictionary['Opportunity']['fields']['winner_c']['source']='custom_fields';

 ?>