<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['channel_c']['name']='channel_c';
$dictionary['Opportunity']['fields']['channel_c']['default_value']='';
$dictionary['Opportunity']['fields']['channel_c']['default']='';
$dictionary['Opportunity']['fields']['channel_c']['display_default']='';
$dictionary['Opportunity']['fields']['channel_c']['len']='100';
$dictionary['Opportunity']['fields']['channel_c']['required']=false;
$dictionary['Opportunity']['fields']['channel_c']['type']='varchar';
$dictionary['Opportunity']['fields']['channel_c']['audited']=0;
$dictionary['Opportunity']['fields']['channel_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['channel_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['channel_c']['options']='';
$dictionary['Opportunity']['fields']['channel_c']['help']='';
$dictionary['Opportunity']['fields']['channel_c']['comments']='';
$dictionary['Opportunity']['fields']['channel_c']['importable']='true';
$dictionary['Opportunity']['fields']['channel_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['channel_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['channel_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['channel_c']['reportable']=true;
$dictionary['Opportunity']['fields']['channel_c']['ext2']='';
$dictionary['Opportunity']['fields']['channel_c']['ext4']='';
$dictionary['Opportunity']['fields']['channel_c']['ext3']='';
$dictionary['Opportunity']['fields']['channel_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['channel_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['channel_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['channel_c']['vname']='LBL_CHANNEL_C';
$dictionary['Opportunity']['fields']['channel_c']['source']='custom_fields';

 ?>