<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['name']='preferred_follow_up_c';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['default_value']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['default']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['display_default']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['len']='100';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['required']=false;
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['type']='varchar';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['audited']=0;
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['options']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['help']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['comments']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['importable']='true';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['reportable']=true;
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['ext2']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['ext4']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['ext3']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['vname']='LBL_PREFERRED_FOLLOW_UP_C';
$dictionary['Opportunity']['fields']['preferred_follow_up_c']['source']='custom_fields';

 ?>