<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['name']='crm_lead_validated_c';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['default_value']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['default']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['display_default']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['len']='255';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['required']=false;
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['type']='bool';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['audited']=0;
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['options']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['help']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['comments']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['importable']='true';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['reportable']=true;
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['ext2']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['ext4']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['ext3']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['vname']='LBL_CRM_LEAD_VALIDATED_C';
$dictionary['Opportunity']['fields']['crm_lead_validated_c']['source']='custom_fields';

 ?>