<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['is_source_c']['name']='is_source_c';
$dictionary['Opportunity']['fields']['is_source_c']['default_value']='';
$dictionary['Opportunity']['fields']['is_source_c']['default']='';
$dictionary['Opportunity']['fields']['is_source_c']['display_default']='';
$dictionary['Opportunity']['fields']['is_source_c']['len']='255';
$dictionary['Opportunity']['fields']['is_source_c']['required']=false;
$dictionary['Opportunity']['fields']['is_source_c']['type']='text';
$dictionary['Opportunity']['fields']['is_source_c']['audited']=0;
$dictionary['Opportunity']['fields']['is_source_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['is_source_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['is_source_c']['options']='';
$dictionary['Opportunity']['fields']['is_source_c']['help']='';
$dictionary['Opportunity']['fields']['is_source_c']['comments']='';
$dictionary['Opportunity']['fields']['is_source_c']['importable']='true';
$dictionary['Opportunity']['fields']['is_source_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['is_source_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['is_source_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['is_source_c']['reportable']=true;
$dictionary['Opportunity']['fields']['is_source_c']['ext2']='';
$dictionary['Opportunity']['fields']['is_source_c']['ext4']='';
$dictionary['Opportunity']['fields']['is_source_c']['ext3']='';
$dictionary['Opportunity']['fields']['is_source_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['is_source_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['is_source_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['is_source_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['is_source_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['is_source_c']['vname']='LBL_IS_SOURCE_C';
$dictionary['Opportunity']['fields']['is_source_c']['source']='custom_fields';

 ?>