<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['blank_ae5_c']['name']='blank_ae5_c';
$dictionary['Opportunity']['fields']['blank_ae5_c']['default_value']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['default']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['display_default']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['len']='50';
$dictionary['Opportunity']['fields']['blank_ae5_c']['required']=false;
$dictionary['Opportunity']['fields']['blank_ae5_c']['type']='varchar';
$dictionary['Opportunity']['fields']['blank_ae5_c']['audited']=0;
$dictionary['Opportunity']['fields']['blank_ae5_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['blank_ae5_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['blank_ae5_c']['options']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['help']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['comments']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['importable']='true';
$dictionary['Opportunity']['fields']['blank_ae5_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['blank_ae5_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['reportable']=true;
$dictionary['Opportunity']['fields']['blank_ae5_c']['ext2']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['ext4']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['ext3']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['blank_ae5_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['blank_ae5_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['blank_ae5_c']['vname']='LBL_BLANK_AE5_C';
$dictionary['Opportunity']['fields']['blank_ae5_c']['source']='custom_fields';

 ?>