<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['rvp2_id_c']['name']='rvp2_id_c';
$dictionary['Opportunity']['fields']['rvp2_id_c']['default_value']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['default']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['display_default']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['len']='1300';
$dictionary['Opportunity']['fields']['rvp2_id_c']['required']=false;
$dictionary['Opportunity']['fields']['rvp2_id_c']['type']='text';
$dictionary['Opportunity']['fields']['rvp2_id_c']['audited']=0;
$dictionary['Opportunity']['fields']['rvp2_id_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['rvp2_id_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['rvp2_id_c']['options']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['help']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['comments']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['importable']='true';
$dictionary['Opportunity']['fields']['rvp2_id_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['rvp2_id_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['reportable']=true;
$dictionary['Opportunity']['fields']['rvp2_id_c']['ext2']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['ext4']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['ext3']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['rvp2_id_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['rvp2_id_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['rvp2_id_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['rvp2_id_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['rvp2_id_c']['vname']='LBL_RVP2_ID_C';
$dictionary['Opportunity']['fields']['rvp2_id_c']['source']='custom_fields';

 ?>