<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['name']='started_as_a_lead_c';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['default_value']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['default']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['display_default']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['len']='255';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['required']=false;
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['type']='bool';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['audited']=0;
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['options']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['help']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['comments']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['importable']='true';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['reportable']=true;
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['ext2']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['ext4']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['ext3']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['vname']='LBL_STARTED_AS_A_LEAD_C';
$dictionary['Opportunity']['fields']['started_as_a_lead_c']['source']='custom_fields';

 ?>