<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['pricedown_target_c']['name']='pricedown_target_c';
$dictionary['Opportunity']['fields']['pricedown_target_c']['default_value']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['default']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['display_default']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['len']='255';
$dictionary['Opportunity']['fields']['pricedown_target_c']['required']=false;
$dictionary['Opportunity']['fields']['pricedown_target_c']['type']='text';
$dictionary['Opportunity']['fields']['pricedown_target_c']['audited']=0;
$dictionary['Opportunity']['fields']['pricedown_target_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['pricedown_target_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['pricedown_target_c']['options']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['help']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['comments']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['importable']='true';
$dictionary['Opportunity']['fields']['pricedown_target_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['pricedown_target_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['reportable']=true;
$dictionary['Opportunity']['fields']['pricedown_target_c']['ext2']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['ext4']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['ext3']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['pricedown_target_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['pricedown_target_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['pricedown_target_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['pricedown_target_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['pricedown_target_c']['vname']='LBL_PRICEDOWN_TARGET_C';
$dictionary['Opportunity']['fields']['pricedown_target_c']['source']='custom_fields';

 ?>