<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['bundle_c']['name']='bundle_c';
$dictionary['Opportunity']['fields']['bundle_c']['default_value']='';
$dictionary['Opportunity']['fields']['bundle_c']['default']='';
$dictionary['Opportunity']['fields']['bundle_c']['display_default']='';
$dictionary['Opportunity']['fields']['bundle_c']['len']='18';
$dictionary['Opportunity']['fields']['bundle_c']['required']=false;
$dictionary['Opportunity']['fields']['bundle_c']['type']='varchar';
$dictionary['Opportunity']['fields']['bundle_c']['audited']=0;
$dictionary['Opportunity']['fields']['bundle_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['bundle_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['bundle_c']['options']='';
$dictionary['Opportunity']['fields']['bundle_c']['help']='';
$dictionary['Opportunity']['fields']['bundle_c']['comments']='';
$dictionary['Opportunity']['fields']['bundle_c']['importable']='true';
$dictionary['Opportunity']['fields']['bundle_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['bundle_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['bundle_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['bundle_c']['reportable']=true;
$dictionary['Opportunity']['fields']['bundle_c']['ext2']='';
$dictionary['Opportunity']['fields']['bundle_c']['ext4']='';
$dictionary['Opportunity']['fields']['bundle_c']['ext3']='';
$dictionary['Opportunity']['fields']['bundle_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['bundle_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['bundle_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['bundle_c']['vname']='LBL_BUNDLE_C';
$dictionary['Opportunity']['fields']['bundle_c']['source']='custom_fields';

 ?>