<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['tbln_c']['name']='tbln_c';
$dictionary['Opportunity']['fields']['tbln_c']['default_value']='';
$dictionary['Opportunity']['fields']['tbln_c']['default']='';
$dictionary['Opportunity']['fields']['tbln_c']['display_default']='';
$dictionary['Opportunity']['fields']['tbln_c']['len']='1300';
$dictionary['Opportunity']['fields']['tbln_c']['required']=false;
$dictionary['Opportunity']['fields']['tbln_c']['type']='text';
$dictionary['Opportunity']['fields']['tbln_c']['audited']=0;
$dictionary['Opportunity']['fields']['tbln_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['tbln_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['tbln_c']['options']='';
$dictionary['Opportunity']['fields']['tbln_c']['help']='';
$dictionary['Opportunity']['fields']['tbln_c']['comments']='';
$dictionary['Opportunity']['fields']['tbln_c']['importable']='true';
$dictionary['Opportunity']['fields']['tbln_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['tbln_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['tbln_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['tbln_c']['reportable']=true;
$dictionary['Opportunity']['fields']['tbln_c']['ext2']='';
$dictionary['Opportunity']['fields']['tbln_c']['ext4']='';
$dictionary['Opportunity']['fields']['tbln_c']['ext3']='';
$dictionary['Opportunity']['fields']['tbln_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['tbln_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['tbln_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['tbln_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['tbln_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['tbln_c']['vname']='LBL_TBLN_C';
$dictionary['Opportunity']['fields']['tbln_c']['source']='custom_fields';

 ?>