<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['stretch_c']['name']='stretch_c';
$dictionary['Opportunity']['fields']['stretch_c']['default_value']='';
$dictionary['Opportunity']['fields']['stretch_c']['default']='';
$dictionary['Opportunity']['fields']['stretch_c']['display_default']='';
$dictionary['Opportunity']['fields']['stretch_c']['len']='255';
$dictionary['Opportunity']['fields']['stretch_c']['required']=false;
$dictionary['Opportunity']['fields']['stretch_c']['type']='real';
$dictionary['Opportunity']['fields']['stretch_c']['audited']=0;
$dictionary['Opportunity']['fields']['stretch_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['stretch_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['stretch_c']['options']='';
$dictionary['Opportunity']['fields']['stretch_c']['help']='';
$dictionary['Opportunity']['fields']['stretch_c']['comments']='';
$dictionary['Opportunity']['fields']['stretch_c']['importable']='true';
$dictionary['Opportunity']['fields']['stretch_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['stretch_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['stretch_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['stretch_c']['reportable']=true;
$dictionary['Opportunity']['fields']['stretch_c']['ext2']='';
$dictionary['Opportunity']['fields']['stretch_c']['ext4']='';
$dictionary['Opportunity']['fields']['stretch_c']['ext3']='';
$dictionary['Opportunity']['fields']['stretch_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['stretch_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['stretch_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['stretch_c']['vname']='LBL_STRETCH_C';
$dictionary['Opportunity']['fields']['stretch_c']['source']='custom_fields';

 ?>