<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['name']='new_ae2_credit_c';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['default_value']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['default']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['display_default']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['len']='255';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['required']=false;
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['type']='real';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['audited']=0;
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['options']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['help']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['comments']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['importable']='true';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['reportable']=true;
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['ext2']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['ext4']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['ext3']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['vname']='LBL_NEW_AE2_CREDIT_C';
$dictionary['Opportunity']['fields']['new_ae2_credit_c']['source']='custom_fields';

 ?>