<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['btl_c']['name']='btl_c';
$dictionary['Opportunity']['fields']['btl_c']['default_value']='';
$dictionary['Opportunity']['fields']['btl_c']['default']='';
$dictionary['Opportunity']['fields']['btl_c']['display_default']='';
$dictionary['Opportunity']['fields']['btl_c']['len']='255';
$dictionary['Opportunity']['fields']['btl_c']['required']=false;
$dictionary['Opportunity']['fields']['btl_c']['type']='bool';
$dictionary['Opportunity']['fields']['btl_c']['audited']=0;
$dictionary['Opportunity']['fields']['btl_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['btl_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['btl_c']['options']='';
$dictionary['Opportunity']['fields']['btl_c']['help']='';
$dictionary['Opportunity']['fields']['btl_c']['comments']='';
$dictionary['Opportunity']['fields']['btl_c']['importable']='true';
$dictionary['Opportunity']['fields']['btl_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['btl_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['btl_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['btl_c']['reportable']=true;
$dictionary['Opportunity']['fields']['btl_c']['ext2']='';
$dictionary['Opportunity']['fields']['btl_c']['ext4']='';
$dictionary['Opportunity']['fields']['btl_c']['ext3']='';
$dictionary['Opportunity']['fields']['btl_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['btl_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['btl_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['btl_c']['vname']='LBL_BTL_C';
$dictionary['Opportunity']['fields']['btl_c']['source']='custom_fields';

 ?>