<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['nb_rollable_c']['name']='nb_rollable_c';
$dictionary['Opportunity']['fields']['nb_rollable_c']['default_value']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['default']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['display_default']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['len']='255';
$dictionary['Opportunity']['fields']['nb_rollable_c']['required']=false;
$dictionary['Opportunity']['fields']['nb_rollable_c']['type']='bool';
$dictionary['Opportunity']['fields']['nb_rollable_c']['audited']=0;
$dictionary['Opportunity']['fields']['nb_rollable_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['nb_rollable_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['nb_rollable_c']['options']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['help']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['comments']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['importable']='true';
$dictionary['Opportunity']['fields']['nb_rollable_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['nb_rollable_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['reportable']=true;
$dictionary['Opportunity']['fields']['nb_rollable_c']['ext2']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['ext4']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['ext3']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['nb_rollable_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['nb_rollable_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['nb_rollable_c']['vname']='LBL_NB_ROLLABLE_C';
$dictionary['Opportunity']['fields']['nb_rollable_c']['source']='custom_fields';

 ?>