<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['name']='blank_imaging_collaboration_c';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['default_value']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['default']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['display_default']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['len']='50';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['required']=false;
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['type']='varchar';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['audited']=0;
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['options']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['help']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['comments']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['importable']='true';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['reportable']=true;
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['ext2']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['ext4']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['ext3']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['vname']='LBL_BLANK_IMAGING_COLLABORATION_C';
$dictionary['Opportunity']['fields']['blank_imaging_collaboration_c']['source']='custom_fields';

 ?>