<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['change_in_mix_c']['name']='change_in_mix_c';
$dictionary['Opportunity']['fields']['change_in_mix_c']['default_value']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['default']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['display_default']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['len']='255';
$dictionary['Opportunity']['fields']['change_in_mix_c']['required']=false;
$dictionary['Opportunity']['fields']['change_in_mix_c']['type']='text';
$dictionary['Opportunity']['fields']['change_in_mix_c']['audited']=0;
$dictionary['Opportunity']['fields']['change_in_mix_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['change_in_mix_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['change_in_mix_c']['options']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['help']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['comments']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['importable']='true';
$dictionary['Opportunity']['fields']['change_in_mix_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['change_in_mix_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['reportable']=true;
$dictionary['Opportunity']['fields']['change_in_mix_c']['ext2']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['ext4']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['ext3']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['change_in_mix_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['change_in_mix_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['change_in_mix_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['change_in_mix_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['change_in_mix_c']['vname']='LBL_CHANGE_IN_MIX_C';
$dictionary['Opportunity']['fields']['change_in_mix_c']['source']='custom_fields';

 ?>