<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['name']='primary_reason_for_winloss_c';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['default_value']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['default']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['display_default']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['len']='4099';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['required']=false;
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['type']='text';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['audited']=0;
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['options']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['help']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['comments']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['importable']='true';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['reportable']=true;
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['ext2']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['ext4']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['ext3']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['rows']=NULL;
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['cols']=NULL;
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['vname']='LBL_PRIMARY_REASON_FOR_WINLOSS_C';
$dictionary['Opportunity']['fields']['primary_reason_for_winloss_c']['source']='custom_fields';

 ?>