<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['adoption_services_c']['name']='adoption_services_c';
$dictionary['Opportunity']['fields']['adoption_services_c']['default_value']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['default']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['display_default']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['len']='255';
$dictionary['Opportunity']['fields']['adoption_services_c']['required']=false;
$dictionary['Opportunity']['fields']['adoption_services_c']['type']='real';
$dictionary['Opportunity']['fields']['adoption_services_c']['audited']=0;
$dictionary['Opportunity']['fields']['adoption_services_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['adoption_services_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['adoption_services_c']['options']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['help']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['comments']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['importable']='true';
$dictionary['Opportunity']['fields']['adoption_services_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['adoption_services_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['reportable']=true;
$dictionary['Opportunity']['fields']['adoption_services_c']['ext2']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['ext4']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['ext3']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['adoption_services_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['adoption_services_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['adoption_services_c']['vname']='LBL_ADOPTION_SERVICES_C';
$dictionary['Opportunity']['fields']['adoption_services_c']['source']='custom_fields';

 ?>