<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['specialist_c']['name']='specialist_c';
$dictionary['Opportunity']['fields']['specialist_c']['default_value']='';
$dictionary['Opportunity']['fields']['specialist_c']['default']='';
$dictionary['Opportunity']['fields']['specialist_c']['display_default']='';
$dictionary['Opportunity']['fields']['specialist_c']['len']='18';
$dictionary['Opportunity']['fields']['specialist_c']['required']=false;
$dictionary['Opportunity']['fields']['specialist_c']['type']='varchar';
$dictionary['Opportunity']['fields']['specialist_c']['audited']=0;
$dictionary['Opportunity']['fields']['specialist_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['specialist_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['specialist_c']['options']='';
$dictionary['Opportunity']['fields']['specialist_c']['help']='';
$dictionary['Opportunity']['fields']['specialist_c']['comments']='';
$dictionary['Opportunity']['fields']['specialist_c']['importable']='true';
$dictionary['Opportunity']['fields']['specialist_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['specialist_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['specialist_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['specialist_c']['reportable']=true;
$dictionary['Opportunity']['fields']['specialist_c']['ext2']='';
$dictionary['Opportunity']['fields']['specialist_c']['ext4']='';
$dictionary['Opportunity']['fields']['specialist_c']['ext3']='';
$dictionary['Opportunity']['fields']['specialist_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['specialist_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['specialist_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['specialist_c']['vname']='LBL_SPECIALIST_C';
$dictionary['Opportunity']['fields']['specialist_c']['source']='custom_fields';

 ?>