<?php
 // Vardefs from Fields_meta_data table - created: 
$dictionary['Opportunity']['fields']['new_partner_c']['name']='new_partner_c';
$dictionary['Opportunity']['fields']['new_partner_c']['default_value']='';
$dictionary['Opportunity']['fields']['new_partner_c']['default']='';
$dictionary['Opportunity']['fields']['new_partner_c']['display_default']='';
$dictionary['Opportunity']['fields']['new_partner_c']['len']='18';
$dictionary['Opportunity']['fields']['new_partner_c']['required']=false;
$dictionary['Opportunity']['fields']['new_partner_c']['type']='varchar';
$dictionary['Opportunity']['fields']['new_partner_c']['audited']=0;
$dictionary['Opportunity']['fields']['new_partner_c']['inline_edit']=1;
$dictionary['Opportunity']['fields']['new_partner_c']['massupdate']=0;
$dictionary['Opportunity']['fields']['new_partner_c']['options']='';
$dictionary['Opportunity']['fields']['new_partner_c']['help']='';
$dictionary['Opportunity']['fields']['new_partner_c']['comments']='';
$dictionary['Opportunity']['fields']['new_partner_c']['importable']='true';
$dictionary['Opportunity']['fields']['new_partner_c']['duplicate_merge']=0;
$dictionary['Opportunity']['fields']['new_partner_c']['duplicate_merge_dom_value']='';
$dictionary['Opportunity']['fields']['new_partner_c']['merge_filter']='';
$dictionary['Opportunity']['fields']['new_partner_c']['reportable']=true;
$dictionary['Opportunity']['fields']['new_partner_c']['ext2']='';
$dictionary['Opportunity']['fields']['new_partner_c']['ext4']='';
$dictionary['Opportunity']['fields']['new_partner_c']['ext3']='';
$dictionary['Opportunity']['fields']['new_partner_c']['labelValue']=NULL;
$dictionary['Opportunity']['fields']['new_partner_c']['unified_search']=0;
$dictionary['Opportunity']['fields']['new_partner_c']['full_text_search']='';
$dictionary['Opportunity']['fields']['new_partner_c']['vname']='LBL_NEW_PARTNER_C';
$dictionary['Opportunity']['fields']['new_partner_c']['source']='custom_fields';

 ?>