var RES_CHECKING='... Проверка',
RES_CONFIRM_LABEL="Сохранить",
RES_CANCEL_LABEL="Отменить",
RES_NEEDHELP='Нужна Помощь?',
RES_SETTINGS='Настройки',
RES_DEMO='Демо Сервер',
RES_OWNSERVER='Мой сервер SugarCRM',
RES_TRIAL='Код пробного доступа',
RES_CHECKTRIAL='Неверный код или пробный доступ окончен<p>Customers of the Full version should leave the Trial Code field empty</p><p>Please visit <a href="#" id="VisitWeb">www.quickcrm.fr/mobile</a> to request a trial version</p>',
RES_VERSION='Данному приложению необходима SugarCRM версии 6.2 или старше<br><br>Вы можете использовать веб-приложение и поключиться при помощи Интернет-браузера к:<br>  ',
RES_PRO_VERSION='Данное приложение ограничено до версии Basic',
RES_URL='Ссылка на SugarCRM :',
RES_CHECKURL='<p>Неверная ссылка на SugarCRM</p>',
RES_QUICKCRMCONF='Установка QuickCRM',
RES_CHECKQUICKCRM='<p>Данному приложению требуется установленный на сервер модуль QuickCRM Mobile Basic или Full 3.2 и старше.</p><p>Вы можете получить дополнительную информацию по QuickCRM Mobile на&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p><br>Если модуль QuickCRM Mobile уже установлен, пожалуйста, проверьте права доступа на директории @ и custom/QuickCRM',
RES_USERCONF='Имя пользователя',
RES_CHECKUSER='<p>Неверное имя пользователя или пароль</p>',
RES_EDITIONCONF='QuickCRM Edition',
RES_CHECKEDITION='<p>QuickCRM Mobile Full предоставляет дополнительный функционал, такой как управление выбранными полями, поиск по любому полю и создание/редактирование записей.<br>Visit <a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a> for more information.</p>',
RES_CONFOK='<h3>Настройка произведена успешно</h3>',
RES_CONFNOK='<h3>Настройка не произведена</h3>',
RES_OLD_APP='Для обеспечения полной совместимости между SugarCRM и QuickCRM Mobile, Ваше приложение необходимо обновить до актуальной версии.',
RES_CHECKCONF='<p>Пожалуйста, проверьте ссылку на SugarCRM URL и убедитесь, что модуль QuickCRM Mobile установлен.</p><p>You can get more information on QuickCRM Mobile Full at&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>';
var RES_MUST_SYNC='SugarCRM должна быть синхронизирована перед @',
 RES_MAX_OFFLINE='Максимальный период в оффлайне прошел',
 RES_NO_LIC='Отсутствует ключ лицензии',
 RES_LIC_MAX='Ключ лицензии должен быть введен в SugarCRM перед @',
 RES_LIC_WILL_EXP='Срок действия лицензии завершится @',
 RES_LIC_EXP='Срок действия лицензии истек';
var RES_LANGUAGE_LABEL='Язык:',
	RES_LANGUAGE_AUTO='Автоматически.',
	RES_CONFIG_PANEL='Вы можете настроить свой сервер нажав на иконку Настройки в левой панели.',
	RES_BASICAUTH='http Basic Authentication Access';
