var RES_CONFIRM_LABEL="Sauvegarder",
RES_CANCEL_LABEL="Annuler",
RES_NEEDHELP='Besoin d\'aide ?',
RES_SETTINGS='Paramètres',
RES_DEMO='Serveur Demo',
RES_OWNSERVER='Mon Serveur SugarCRM',
RES_TRIAL="Code d'essai Full",
RES_CHECKTRIAL='Code incorrect ou essai terminé<p>Les utilisateurs de la version Full doivent laisser le champ Code d\'essai vide.</p><p>Vous pouvez demander une version d\'essai &agrave; <a href="#" id="VisitWeb">www.quickcrm.fr/mobile/fr</a></p>',
RES_VERSION='Cette application nécessite SugarCRM 6.2 ou ultérieure<br><br>Vous pouvez utiliser QuickCRM Mobile en vous connectant depuis votre navigateur à :<br>  ',
RES_PRO_VERSION="L'application sera limitée à la version Basic",
RES_URL='URL SugarCRM :',
RES_CHECKURL='<p>URL SugarCRM Invalide </p>',
RES_CHECKQUICKCRM='<p>Cette application nécessite la version 3.2 ou suivantes de QuickCRM Mobile Basic ou Full sur votre serveur SugarCRM.</p><p>Vous pouvez obtenir plus d\'information sur QuickCRM Mobile à&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile/fr</a>.</p><br>Si vous avez installé QuickCRM Mobile, veuillez vérifier les droits d\'accès des dossiers @ et custom/QuickCRM',
RES_CHECKUSER='<p>Utilisateur ou mot de passe incorrect.</p>',
RES_CHECKEDITION='<p>QuickCRM Mobile Full apporte des fonctionnalités additionnelles comme la gestion des champs custom en affichage ou recherche et l\'édition.<br>Visitez <a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile/fr</a> pour plus d\'information.</p>',
RES_OLD_APP='Votre application doit être mise à jour à la dernière version pour être entièrement compatible avec SugarCRM et QuickCRM Mobile.',
RES_CHECKCONF='<p>Vérifiez votre URL SugarCRM et assurez vous que QuickCRM Mobile est installé.</p><p>Vous pouvez obtenir plus d\'information sur QuickCRM Mobile Full à&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile/fr</a>.</p>',
RES_MUST_SYNC='SugarCRM doit être synchronisé avant le @',
RES_MAX_OFFLINE='Durée offline expirée',
RES_NO_LIC='Pas de clé de licence',
RES_LIC_MAX='La clé de licence doit être saisie dans SugarCRM avant le @',
RES_LIC_WILL_EXP='Votre licence expirera le @',
RES_LIC_EXP="Votre licence a expiré",
RES_LANGUAGE_LABEL='Langue :',
RES_LANGUAGE_AUTO='Auto.',
RES_CONFIG_PANEL='Configurez votre serveur en cliquant sur l&#039;icone Param&egrave;tres sur le panneau de gauche.',
RES_BASICAUTH='http Basic Authentication Access';