var RES_CHECKING='... Aan het controleren',
RES_CONFIRM_LABEL="Opslaan",
RES_CANCEL_LABEL="Annuleer",
RES_NEEDHELP='Hulp nodig?',
RES_SETTINGS='Instellingen',
RES_DEMO='Demo Server',
RES_OWNSERVER='Mijn SugarCRM server',
RES_TRIAL='Proeflicentie',
RES_CHECKTRIAL='Ongeldige licentiecode of verlopen proeflicentie<p>Klanten van de volledige versie moet het Proeflicentie leeglaten</p><p>Please visit <a href="#" id="VisitWeb">www.quickcrm.fr/mobile</a> to request a trial version</p>',
RES_VERSION='Deze applicatie vereist SugarCRM 6.2 of nieuwer<br><br>U kunt de web interface gebruiken en met uw internet browser verbinden met:<br> ',
RES_PRO_VERSION='De applicatie is gelimiteerd tot de Basic versie',
RES_URL='URL SugarCRM: ',
RES_CHECKURL='<p>Ongeldige SugarCRM URL</p>',
RES_QUICKCRMCONF='QuickCRM Installatie',
RES_CHECKQUICKCRM='<p>Deze applicatie vereist dat QuickCRM Mobile Basic of Full 3.2 is geinstalleerd in SugarCRM.</p><p>U kunt meer informatie krijgen over QuickCRM Mobile via&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p><br>Als QuickCRM Mobile als is geinstalleerd, cotroleer please a.u.b. de permissies op @ en de custom/QuickCRM directories',
RES_USERCONF='Gebruikerslogin',
RES_CHECKUSER='<p>Inlognaam of wachtwoord incorrect</p>',
RES_EDITIONCONF='QuickCRM editie',
RES_CHECKEDITION='<p>QuickCRM Mobile Full biedt extra functies, zoals het beheren van custom velden, zoeken op alle velden en het invoeren en wijzigen van gegevens.<br>Bezoek <a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a> voor meer informatie.</p>',
RES_CONFOK='<h3>Configuratie succesvol</h3>',
RES_CONFNOK='<h3>Configuratie mislukt</h3>',
RES_OLD_APP='Uw applicatie moet worden geupgraded naar de nieuwste versie om volledig compatibel te zijn met SugarCRM en QuickCRM Mobile.',
RES_CHECKCONF='<p>Controleer a.u.b. uw SugarCRM URL en controleer dat QuickCRM Mobile is geinstalleerd.</p><p>U kunt meer informatie krijgen over QuickCRM Mobile Full op&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>';
var RES_MUST_SYNC='SugarCRM moet gesynchroniseerd zijn voor @',
 RES_MAX_OFFLINE='Maximale offline periode verlopen',
 RES_NO_LIC='Geen licentiesleutel',
 RES_LIC_MAX='De licentiesleutel moet in SugarCRM worden ingegeven voor @',
 RES_LIC_WILL_EXP='Uw licentie zal verlopen op @',
 RES_LIC_EXP='Licentie verlopen',
 RES_LANGUAGE_LABEL='Taal:',
	RES_LANGUAGE_AUTO='Auto.',
	RES_CONFIG_PANEL='U kunt uw server configureren door te klikken op het Instellingen icoon in het linker paneel.',
	RES_BASICAUTH='http basic authenticatie toegang';