var RES_CONFIRM_LABEL="Zapisz",
RES_CANCEL_LABEL="Anuluj",
RES_NEEDHELP='Potrzebujesz pomocy?',
RES_SETTINGS='Ustawienia',
RES_DEMO='Serwer demonstracyjny',
RES_OWNSERVER='M\u00f3j serwer',
RES_TRIAL='Kod pr\u00f3bny',
RES_CHECKTRIAL='Niew\u0142a\u015bciwy Klucz licencyjny lub zako\u0144czony okres testowy<p>Posiadacze wersji Full powinni pozostawi\u0107 pole Kod pr\u00f3bny puste</p><p>Zapraszamy na stron\u0119 <a href="#" id="VisitWeb">www.quickcrm.fr/mobile</a> aby uzyska\u0107 wersj\u0119 pr\u00f3bn\u0105</p>',
RES_VERSION='Ta aplikacja wymaga SgraCRM w wersji 6.2 lub wy\u017cszej<br><br>Mo\u017cesz u\u017cy\u0107 aplikacji webowej i otworzy\u0107 w przegl\u0105darce internetowej:<br>  ',
RES_PRO_VERSION='Aplikacja zostanie ograniczona do wersji podstawowej',
RES_URL='URL twojego serwera CRM :',
RES_CHECKURL='<p>B\u0142\u0119dny URL serwera CRM</p>',
RES_CHECKQUICKCRM='<p>Ta aplikacja wymaga modu\u0142u QuickCRM Mobile Basic lub Full w wersji 3.2 lub p\u00f3\u017aniejszej zainstalowanego na serwerze CRM.</p><p>Wi\u0119cej informacji na temat QuickCRM Mobile pod adresem&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p><br>Je\u015bli QuickCRM Mobile zosta\u0142 ju\u017c zainstalowany, prosz\u0119 sprawdzi\u0107 uprawnienia @ oraz w katalogach custom/QuickCRM',
RES_CHECKUSER='<p>Nieprawid\u0142owy login lub has\u0142o</p>',
RES_EDITIONCONF='Wersja QuickCRM',
RES_OLD_APP='Twoja aplikacja musi zosta\u0107 zaktualizowana do najnowszej wersji dla uzyskania pe\u0142nej kompatybilno\u015bci z CRM oraz QuickCRM Mobile.',
RES_CHECKCONF='<p>Prosz\u0119 sprawdzi\u0107 URL serwera CRM oraz upewni\u0107 si\u0119, \u017ce QuickCRM Mobile jest zainstalowany.</p><p>Wi\u0119cej informacji na temat QuickCRM Mobile Full znajdziesz na&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>',
RES_MUST_SYNC='CRM musi zosta\u0107 zsynchronizowany przed @',
RES_MAX_OFFLINE='Maksymalny czas niedost\u0119pno\u015bci zosta\u0142 przekroczony',
RES_NO_LIC='Brak klucza licencyjnego',
RES_LIC_MAX='Klucz licencyjny musi zosta\u0107 wpisany w CRM zanim @',
RES_LIC_WILL_EXP='Twoja licencja wyga\u015bnie @',
RES_LIC_EXP='Licencja wygas\u0142a',
RES_LANGUAGE_LABEL='J\u0119zyk:',
RES_LANGUAGE_AUTO='Automatyczny',
RES_CONFIG_PANEL='Mo\u017cesz skonfigurowa\u0107 serwer klikaj\u0105c na ikon\u0119 Ustawie\u0144 na lewym panelu.',
RES_BASICAUTH='http Basic Authentication Access';
