var RES_CHECKING='... Verificant',
RES_CONFIRM_LABEL="Guardar",
RES_CANCEL_LABEL="Cancelar",
RES_NEEDHELP='Necessita ajuda?',
RES_SETTINGS='Configuració',
RES_DEMO='Servidor Demo',
RES_OWNSERVER='El meu Servidor SugarCRM',
RES_TRIAL='Codi de prova',
RES_CHECKTRIAL='Codi no vàlid o període de prova expirat<p>Els clients de la versió completa han de deixar el codi de prova buit</p><p>Pot obtenir més informació sobre QuickCRM Mobile en <a href="#" id="VisitWeb">www.quickcrm.fr/mobile</a></p>',
RES_VERSION='Aquesta aplicació requereix SugarCRM 6.2 o posterior<br><br>Vostè pot utilitzar l\'aplicació web i connectar-se amb el seu navegador d\'Internet a:<br>  ',
RES_PRO_VERSION='L\'aplicació estarà limitada a Versió Basic',
RES_URL='URL SugarCRM :',
RES_CHECKURL='<p>URL SugarCRM invàlida</p>',
RES_QUICKCRMCONF='Instal·lació QuickCRM',
RES_CHECKQUICKCRM='<p>Aquesta aplicació requereix la versió 3.2 de QuickCRM Mobile Basic or Full instal·lada en SugarCRM.</p><p>Pot obtenir més informació sobre QuickCRM Mobile a&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p><br>Si QuickCRM Mobile ja està instal·lat, comprovi els permisos en els directoris @ i custom/QuickCRM',
RES_USERCONF='Login d\'usuari',
RES_CHECKUSER='<p>Usuari o contrasenya incorrecta</p>',
RES_CONFOK='<h3>Configuració exitosa</h3>',
RES_CONFNOK='<h3>Error de configuració</h3>',
RES_OLD_APP='La seva aplicació haurà de ser actualitzada a l\'última versió per a ser totalment compatible amb SugarCRM i QuickCRM Mobile.',
RES_CHECKCONF='<p>Si us plau verifiqui la seva URL SugarCRM i asseguri\'s que QuickCRM Mobile està instal·lat.</p><p>Pot obtenir més informació sobre QuickCRM Mobile Full a&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>';
var RES_MUST_SYNC='SugarCRM ha de ser sincronitzat abans de @',
 RES_MAX_OFFLINE='Desconnectat període màxim de venciment',
 RES_NO_LIC='No Clau de llicència',
 RES_LIC_MAX='Clau de llicència ha de contraure\'s SugarCRM abans de @',
 RES_LIC_WILL_EXP='Llicència caducarà el @',
 RES_LIC_EXP="Llicència vençuda";
 var RES_LANGUAGE_LABEL='idioma :',
	RES_LANGUAGE_AUTO='Auto.',
	RES_CONFIG_PANEL='Per a configurar el seu servidor, fagi clic en l\'icona Configuració en el panell esquerra.',
	RES_BASICAUTH='http Basic Authentication Access';
