var RES_CHECKING='... 檢查',
RES_CONFIRM_LABEL="保存",
RES_CANCEL_LABEL="取消",
RES_NEEDHELP='需要協助?',
RES_SETTINGS='設定',
RES_DEMO='示範伺服器',
RES_OWNSERVER='我的SugarCRM伺服器',
RES_TRIAL='試用版驗証碼',
RES_CHECKTRIAL='驗證驗無效 或 試用版已過期<p>Customers of the Full version should leave the Trial Code field empty</p><p>Please visit <a href="#" id="VisitWeb">www.quickcrm.fr/mobile</a> to request a trial version</p>',
RES_VERSION='這程式需求SugarCRM 6.2 或以上版本。您可使用網絡應用程式來連接網絡瀏覽器',
RES_PRO_VERSION='此程式只限於Basic版本',
RES_URL='URL SugarCRM :',
RES_CHECKURL='<p>SugarCRM URL 無效</p>',
RES_QUICKCRMCONF='安裝QuickCRM',
RES_CHECKQUICKCRM='<p>需要在SugarCRM已經安裝了QuickCRM Mobile Basic 或 Full 3.2才能執行此程式.</p><p>更多相關資料，可於QuickCRM Mobile瀏覽 &nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p><br>如QuickCRM Mobile經已安裝，請檢查是否已給予@ 和 custom/QuickCRM directories權限',
RES_USERCONF='使用者登入',
RES_CHECKUSER='<p>使用者名稱或密碼不正確</p>',
RES_EDITIONCONF='QuickCRM 編輯器',
RES_CHECKEDITION='<p>QuickCRM Mobile Full 有更多的功能，例如自訂區域管理、在任何欄或建立/編輯進行搜尋.<br>瀏覽<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a> 獲取更多訊息.</p>',
RES_CONFOK='<h3>設置成功</h3>',
RES_CONFNOK='<h3>設置失敗</h3>',
RES_OLD_APP='您的程式需升級到最新版本才能與SugarCRM和QuickCRM Mobile完全相容.',
RES_CHECKCONF='<p>請檢查您的SugarCRM URL及確認QuickCRM Mobile經已安裝.</p><p>更多QuickCRM Mobile Full的資料，請瀏覽&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>';
var RES_MUST_SYNC='SugarCRM 需於@之前同步',
 RES_MAX_OFFLINE='已過了最大離線時間',
 RES_NO_LIC='沒有註冊號碼',
 RES_LIC_MAX='需把註冊號碼於@之前驗入SugarCRM',
 RES_LIC_WILL_EXP='您的註冊號碼將於@過期',
 RES_LIC_EXP='註冊號碼已過期';
 var RES_LANGUAGE_LABEL='語',
	RES_LANGUAGE_AUTO='Auto.',
	RES_CONFIG_PANEL='在左側面板中點擊“設置”圖標，你可以配置你的服務器。',
	RES_BASICAUTH='http Basic Authentication Access';