var RES_CONFIRM_LABEL="Save",
RES_CANCEL_LABEL="Cancel",
RES_NEEDHELP='Need help?',
RES_SETTINGS='Settings',
RES_DEMO='Demo Server',
RES_OWNSERVER='My SugarCRM Server',
RES_TRIAL='Trial Code',
RES_CHECKTRIAL='Invalid Code or expired trial<p>Customers of the Full version should leave the Trial Code field empty</p><p>Please visit <a href="#" id="VisitWeb">www.quickcrm.fr/mobile</a> to request a trial version</p>',
RES_VERSION='This application requires SugarCRM 6.2 or later<br><br>You can use the web app and connect with your internet browser to:<br>  ',
RES_PRO_VERSION='The application will be limited to Basic Version',
RES_URL='URL SugarCRM :',
RES_CHECKURL='<p>Invalid SugarCRM URL</p>',
RES_CHECKQUICKCRM='<p>This application requires QuickCRM Mobile Basic or Full 3.2 or later installed in SugarCRM.</p><p>You can get more information on QuickCRM Mobile at&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p><br>If QuickCRM Mobile is already installed, please check permissions on @ and custom/QuickCRM directories',
RES_CHECKUSER='<p>Incorrect login or password</p>',
RES_EDITIONCONF='QuickCRM Edition',
RES_OLD_APP='Your application need to be updated to the latest version to be fully compatible with SugarCRM and QuickCRM Mobile.',
RES_CHECKCONF='<p>Please check your SugarCRM URL and make sure QuickCRM Mobile is installed.</p><p>You can get more information on QuickCRM Mobile Full at&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>',
RES_MUST_SYNC='SugarCRM must be synced before @',
RES_MAX_OFFLINE='Maximum Offline period expired',
RES_NO_LIC='No License key',
RES_LIC_MAX='License key must be entered into SugarCRM before @',
RES_LIC_WILL_EXP='Your License will expire on @',
RES_LIC_EXP='License expired',
RES_LANGUAGE_LABEL='Language:',
RES_LANGUAGE_AUTO='Auto.',
RES_CONFIG_PANEL='You can configure your server by clicking on the Settings icon in the left panel.',
RES_BASICAUTH='http Basic Authentication Access';
