var RES_CHECKING='... Prüfen',
RES_CONFIRM_LABEL="Speichern",
RES_CANCEL_LABEL="Abbrechen",
RES_NEEDHELP='Hilfe benötigt?',
RES_SETTINGS='Einstellungen',
RES_DEMO='Demo Server',
RES_OWNSERVER='Mein SugarCRM Server',
RES_TRIAL='Test Code',
RES_CHECKTRIAL='Falscher Code oder abgelaufene Testperiode<p>Kunden, die Vollversion soll das Feld Test Code leer lassen</p><p>Weitere Informationen zu QuickCRM Mobile : <a href="#" id="VisitWeb">www.quickcrm.fr/mobile</a><p>',
RES_VERSION='Diese Anwendung erfordert SugarCRM 6.2 oder höher<br><br>Nutzen Sie die Web Applikation und verbinden Sie sich mit Ihrem Browser zu:<br>  ',
RES_PRO_VERSION='Die Anwendung ist auf die Basic Version beschränkt',
RES_URL='SugarCRM URL:',
RES_CHECKURL='<p>Ungültige SugarCRM URL</p>',
RES_QUICKCRMCONF='QuickCRM Installation',
RES_CHECKQUICKCRM='<p>Diese Anwendung erfordert die Installation von QuickCRM Mobile Basic Basic oder Full 3.2 in SugarCRM.</p><p>Weitere Informationen zu QuickCRM Mobile erhalten Sie unter&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p><br>Bitte prüfen Sie die Berechtigungen der @ und custom/QuickCRM Verzeichnisse falls QuickCRM Mobile bereits installiert ist.',
RES_USERCONF='Benutzer Login',
RES_CHECKUSER='<p>Fehlerhafte Benutzerdaten</p>',
RES_EDITIONCONF='QuickCRM Edition',
RES_CHECKEDITION='<p>QuickCRM Mobile Full enthält weitere Leistungsmerkmale wie kundenspezifische Felder, Suchen nach beliebigen Feldinhalten und Erstellen/Bearbeiten.<br>Besuchen Sie <a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a> für weitere Informationen.</p>',
RES_CONFOK='<h3>Konfiguration erfolgreich</h3>',
RES_CONFNOK='<h3>Konfiguration gescheitert</h3>',
RES_OLD_APP='Aktualisieren Sie Ihre Anwendung für volle Kompatibilität mit SugarCRM and QuickCRM Mobile.',
RES_CHECKCONF='<p>Bitte prüfen Sie die SugarCRM URL und stellen Sie sicher daß QuickCRM Mobile installiert ist.</p><p>Weitere Informationen zu QuickCRM Mobile Full erhalten Sie unter&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>';
var RES_MUST_SYNC='SugarCRM müssen vor @ synchronisiert werden',
 RES_MAX_OFFLINE='Maximale Offline-Zeitraum abgelaufen',
 RES_NO_LIC='Keine Lizenz',
 RES_LIC_MAX='Lizenz-Schlüssel muss in SugarCRM vor @ eingegeben werden',
 RES_LIC_WILL_EXP='Lizenz wird auf @ auslaufen',
 RES_LIC_EXP='Lizenz abgelaufen';
var RES_LANGUAGE_LABEL='Sprache :',
	RES_LANGUAGE_AUTO='Auto.',
	RES_CONFIG_PANEL='Um Ihren Server konfigurieren, klicken Sie auf das Symbol Einstellungen in der linken Seite.',
	RES_BASICAUTH='http Basic Authentication Access';