var RES_CHECKING='... 检查',
RES_CONFIRM_LABEL="保存",
RES_CANCEL_LABEL="取消",
RES_NEEDHELP='需要协助?',
RES_SETTINGS='设定',
RES_DEMO='示范服务器',
RES_OWNSERVER='我的SugarCRM服务器',
RES_TRIAL='试用版验证码',
RES_CHECKTRIAL='验证验无效 或 试用版已过期<p>Customers of the Full version should leave the Trial Code field empty</p><p>Please visit <a href="#" id="VisitWeb">www.quickcrm.fr/mobile</a> to request a trial version</p>',
RES_VERSION='这程序需求SugarCRM 6.2 或以上版本。您可使用网络应用程序来连接网络浏览器',
RES_PRO_VERSION='此程序只限于Basic版本',
RES_URL='URL SugarCRM :',
RES_CHECKURL='<p>SugarCRM URL 无效</p>',
RES_QUICKCRMCONF='安装QuickCRM',
RES_CHECKQUICKCRM='<p>需要在SugarCRM已经安装了QuickCRM Mobile Basic 或 Full 3.2才能执行此程序.</p><p>更多相关数据，可于QuickCRM Mobile浏览 &nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p><br>如QuickCRM Mobile经已安装，请检查是否已给予@ 和 custom/QuickCRM directories权限',
RES_USERCONF='使用者登入',
RES_CHECKUSER='<p>用户名称或密码不正确</p>',
RES_EDITIONCONF='QuickCRM 编辑器',
RES_CHECKEDITION='<p>QuickCRM Mobile Full 有更多的功能，例如自定义区域管理、在任何栏或建立/编辑进行搜寻.<br>浏览<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a> 获取更多讯息.</p>',
RES_CONFOK='<h3>设置成功</h3>',
RES_CONFNOK='<h3>设置失败</h3>',
RES_OLD_APP='您的程序需升级到最新版本才能与SugarCRM和QuickCRM Mobile完全兼容.',
RES_CHECKCONF='<p>请检查您的SugarCRM URL及确认QuickCRM Mobile经已安装.</p><p>更多QuickCRM Mobile Full的数据，请浏览&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>';
var RES_MUST_SYNC='SugarCRM 需于@之前同步',
 RES_MAX_OFFLINE='已过了最大脱机时间',
 RES_NO_LIC='没有注册号码',
 RES_LIC_MAX='需把注册号码于@之前验入SugarCRM',
 RES_LIC_WILL_EXP='您的注册号码将于@过期',
 RES_LIC_EXP='注册号码已过期';
 var RES_LANGUAGE_LABEL='语',
	RES_LANGUAGE_AUTO='Auto.',
	RES_CONFIG_PANEL='在左侧面板中点击“设置”图标，你可以配置你的服务器。',
	RES_BASICAUTH='http Basic Authentication Access',
	RES_HELPTRIAL='<p>Customers of the Full version should leave the Trial Code field empty</p><p>Please go to <a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a> to request a trial version</p>';
	
