var RES_CHECKING='... Tikriname',
RES_CONFIRM_LABEL="Saugoti",
RES_CANCEL_LABEL="Atšaukti",
RES_NEEDHELP='Ar reikalinga pagalba?',
RES_SETTINGS='Nustatymai',
RES_DEMO='Demo Serveris',
RES_OWNSERVER='Mano SugarCRM Serveris',
RES_TRIAL='Bandomasios versijos kodas',
RES_CHECKTRIAL='Netesingas kodas arba baigėsi bandomoji versija<p>Customers of the Full version should leave the Trial Code field empty</p><p>Please visit <a href="#" id="VisitWeb">www.quickcrm.fr/mobile</a> to request a trial version</p>',
RES_VERSION='Šiai aplikacijai reikia SugarCRM 6.2 versijos arba vėlesnės<br><br>Naudokite šį adresą prisijungimui iš naršyklės:<br>  ',
RES_PRO_VERSION='Ši aplikacija taikoma tik Basic versijai',
RES_URL='SugarCRM adresas:',
RES_CHECKURL='<p>Neteisingas SugarCRM adresas</p>',
RES_QUICKCRMCONF='QuickCRM Instaliacija',
RES_CHECKQUICKCRM='<p>Šiai aplikacijai reikia SugarCRM modulio QuickCRM Mobile Basic arba Full 3.2.</p><p>Daugiau informacijos apie QuickCRM Mobile, svetainėje&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p><br>Jei QuickCRM Mobile jau instaluota, pasitikrinkite leidimus į custom/QuickCRM aplankus',
RES_USERCONF='Vartotojo prisijungimas',
RES_CHECKUSER='<p>neteisingas prisijungimas ar slaptažodis</p>',
RES_EDITIONCONF='QuickCRM versija',
RES_CHECKEDITION='<p>QuickCRM Mobile Full galima pridėti naujų laukų, ieškoti bet kokį lauką ir kūrimas ,bei modifikacijos.<br>Jei norite daugiau informacijos, apsilankykite <a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>',
RES_CONFOK='<h3>Sėkmingi nustatymai</h3>',
RES_CONFNOK='<h3>Klaidingi nustatymai</h3>',
RES_OLD_APP='Jūsų sistemą reikia atnaujinti.',
RES_CHECKCONF='<p>Pasitikrinkite ar QuickCRM Mobile sėkmingai įdiegta.</p><p>Daugiau indormacijos QuickCRM Mobile Full at&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>';
var RES_MUST_SYNC='SugarCRM turi būti susinchrinizuoti prieš @',
 RES_MAX_OFFLINE='Maksimulus aktyvumo laikotarpis baigėsi',
 RES_NO_LIC='Nenurodytas licencijos kodas',
 RES_LIC_MAX='Naujas licencijos kodas turi būti įvestas @',
 RES_LIC_WILL_EXP='Licencijos kodas baigsis iki @',
 RES_LIC_EXP='Licencija baigėsi';
var RES_LANGUAGE_LABEL='Kalba:',
	RES_LANGUAGE_AUTO='Automatinė.',
	RES_CONFIG_PANEL='Spauskite nustatymų ikonėlę kairėje, jei norite konfiguruoti serverį.',
	RES_BASICAUTH='http Bazinis prisijungimo atpažinimas';