var RES_CHECKING='... Verifiando',
RES_CONFIRM_LABEL="Guardar",
RES_CANCEL_LABEL="Cancelar",
RES_NEEDHELP='Necesita ayuda?',
RES_SETTINGS='Configuración',
RES_DEMO='Servidor Demo',
RES_OWNSERVER='Mi Servidor SugarCRM',
RES_TRIAL='Código de prueba',
RES_CHECKTRIAL='Código no válido o periodo de prueba expirado<p>Los clientes de la versión completa deben dejar el código de prueba vacía</p><p>Puede obtener más información sobre QuickCRM Mobile en <a href="#" id="VisitWeb">www.quickcrm.fr/mobile</a></p>',
RES_VERSION='Esta aplicación requiere SugarCRM 6.2 o posterior<br><br>Usted puede utilizar la aplicación web y conectarse con su navegador de Internet a:<br>  ',
RES_PRO_VERSION='La aplicación estará limitada a Versión Basic',
RES_URL='URL SugarCRM :',
RES_CHECKURL='<p>URL SugarCRM inválida</p>',
RES_QUICKCRMCONF='Instalación QuickCRM',
RES_CHECKQUICKCRM='<p>Esta aplicación requiere la versión 3.2 de QuickCRM Mobile Basic or Full instalada en SugarCRM.</p><p>Puede obtener más información sobre QuickCRM Mobile en&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p><br>Si QuickCRM Mobile ya está instalado, compruebe los permisos en los directorios @ y custom/QuickCRM',
RES_USERCONF='Login de usuario',
RES_CHECKUSER='<p>Usuario o contraseña incorrecta</p>',
RES_CONFOK='<h3>Configuración exitosa</h3>',
RES_CONFNOK='<h3>Error de configuración</h3>',
RES_OLD_APP='Su aplicación deberá ser actualizado a la última versión para ser totalmente compatible con SugarCRM y QuickCRM Mobile.',
RES_CHECKCONF='<p>Por favor verifique su URL SugarCRM y asegúrese que QuickCRM Mobile está instalado.</p><p>Puede obtener más información sobre QuickCRM Mobile Full en&nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>';
var RES_MUST_SYNC='SugarCRM debe ser sincronizado antes de @',
 RES_MAX_OFFLINE='Desconectado período máximo de vencimiento',
 RES_NO_LIC='No Clave de licencia',
 RES_LIC_MAX='Clave de licencia debe contraerse SugarCRM antes de @',
 RES_LIC_WILL_EXP='Licencia caducará el @',
 RES_LIC_EXP="Licencia vencida";
 var RES_LANGUAGE_LABEL='idioma :',
	RES_LANGUAGE_AUTO='Auto.',
	RES_CONFIG_PANEL='Para configurar su servidor, haga clic en el icono Configuración en el panel izquierdo.',
	RES_BASICAUTH='http Basic Authentication Access';
