var RES_CHECKING='... Verifica in corso',
RES_CONFIRM_LABEL="Salva",
RES_CANCEL_LABEL="Annulla",
RES_NEEDHELP='Aiuto',
RES_SETTINGS='Impostazioni',
RES_DEMO='Server di Prova',
RES_OWNSERVER='URL di SugarCRM',
RES_TRIAL='Codice di Prova',
RES_CHECKTRIAL='Codice non valido o periodo di prova scaduto<p>I Clienti della versione Full devono lasciare vuoto il campo Codice di Prova</p><p>Visitare <a href="#" id="VisitWeb">www.quickcrm.fr/mobile</a> per richiedere un Codice di Prova</p>',
RES_VERSION='Quest\'applicazione richiede SugarCRM versione 6.2 o superiore<br><br>E\' possibile utilizzare l\'applicazione web e collegarsi con il proprio browser a:<br>  ',
RES_PRO_VERSION='L\'applicazione sarà limitata alla versione Basic',
RES_URL='URL di SugarCRM :',
RES_CHECKURL='<p>URL di SugarCRM non valido</p>',
RES_CHECKQUICKCRM='<p>Quest\'applicazione richiede QuickCRM Mobile Basic o Full versione 3.2 o superiore installata in SugarCRM.</p><p>Ulteriori informazioni su QuickCRM Mobile sono reperibili all\'indirizzo &nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p><br>Se QuickCRM è già installato, verificare i permessi di accesso ai file in @ e nelle directory contenute in custom/QuickCRM ',
RES_CHECKUSER='<p>Username o Password non validi</p>',
RES_OLD_APP='L\'applicazione deve essere aggiornata all\'ultima versione per essere completamente compatibile con SugarCRM e QuickCRM Mobile.',
RES_CHECKCONF='<p>Verificare l\'URL di SugarCRM e verificare che QuickCRM Mobile sia installato.</p><p>Ulteriori informazioni su QuickCRM Mobile sono reperibili all\'indirizzo &nbsp;&nbsp;<a href="#" onclick="OpenQuickCRM()" >www.quickcrm.fr/mobile</a>.</p>',
RES_MUST_SYNC='SugarCRM must deve essere sincronizzato prima del @',
RES_MAX_OFFLINE='Il periodo Massimo di Offline è stato superato',
RES_NO_LIC='Nessuna chiave di licenza',
RES_LIC_MAX='La chiave di licenza deve essere inserita in SugarCRM prima del @',
RES_LIC_WILL_EXP='La chiave di licenza scadrà il @',
RES_LIC_EXP='Licenza scaduta',
RES_LANGUAGE_LABEL='Lingua:',
RES_LANGUAGE_AUTO='Auto.',
RES_CONFIG_PANEL='E\'possibile configurare il server cliccando sull\'icona impostazioni nel pannello di sinistra.',
RES_BASICAUTH='Autenticazione http base';
